MiXiM: Decider80211MultiChannel Class Reference
Decider80211MultiChannel Class Reference
Extends Decider80211 by multi channel support.
#include <Decider80211MultiChannel.h>
Public Member Functions
Decider80211MultiChannel (DeciderToPhyInterface *phy, double sensitivity, int myIndex, bool debug)
Standard Decider constructor.
virtual void channelChanged (int newChannel)
Called by phy layer to indicate that the channel this radio currently listens to has changed.
Protected Member Functions
virtual DeciderResult * createResult (const airframe_ptr_t frame) const
Checks if the passed completed AirFrame was received correctly.
Detailed Description
Extends Decider80211 by multi channel support.
Filters processing of AirFrames depending on the channel they were sent on and the channel this deciders radio is currently set to. All AirFrames on another channel than the currently used one are ignored totally, they are neither received nor considered as interference. If the channel changed during the reception of an AirFrame the AirFrame is considered lost, independent from the size of the part which was lost due to channel change.
NOTE: This decider does not model interference between adjacent channels!
Author:
Karl Wessel
Member Function Documentation
void Decider80211MultiChannel::channelChanged (int newChannel) [virtual]
Called by phy layer to indicate that the channel this radio currently listens to has changed.
Sub-classing deciders which support multiple channels should override this method to handle the effects of channel changes on ongoing receptions.
Parameters:
newChannel The new channel the radio has changed to.
Reimplemented from BaseDecider.
References Decider80211::centerFrequency.
{
  assert(1 <= newChannel && newChannel <= 14);
  centerFrequency = CENTER_FREQUENCIES[newChannel];
  Decider80211Battery::channelChanged(newChannel);
}
DeciderResult * Decider80211MultiChannel::createResult (const airframe_ptr_t frame) const [protected, virtual]
Checks if the passed completed AirFrame was received correctly.
Returns the result as a DeciderResult. If the channel changed during transmission the AirFrame is considered broken.
Returns:
The result of the decider for the passed AirFrame.
Reimplemented from Decider80211.
References DeciderResult80211::getBitrate(), DeciderToPhyInterface::getCurrentRadioChannel(), DeciderResult80211::getSnr(), DeciderResult::isSignalCorrect(), and Decider::phy.
{
    DeciderResult80211* result = static_cast<DeciderResult80211*>(Decider80211Battery::createResult(frame));
  if(result->isSignalCorrect() && frame->getChannel() != phy->getCurrentRadioChannel()) {
    deciderEV << "Channel changed during reception. packet is lost!\n";
    DeciderResult80211* oldResult = result;
    result = new DeciderResult80211(false, oldResult->getBitrate(), oldResult->getSnr());
    delete oldResult;
  }
  return result;
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/phy/Decider80211MultiChannel.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/phy/Decider80211MultiChannel.cc