MiXiM: BreakpointPathlossModel Class Reference
BreakpointPathlossModel Class Reference
analogueModels - AnalogueModel implementations
Basic implementation of a BreakpointPathlossModel. This class can be used to implement the ieee802154 path loss model.
#include <BreakpointPathlossModel.h>
Public Member Functions
BreakpointPathlossModel ()
Initializes the analogue model. playgroundSize need to be valid as long as this instance exists.
virtual bool initFromMap (const ParameterMap &)
Initialize the analog model from XML map data.
virtual void filterSignal (airframe_ptr_t, const Coord &, const Coord &)
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
virtual bool isActiveAtDestination ()
virtual bool isActiveAtOrigin ()
Protected Attributes
double PL01
Model to use for distances below breakpoint distance.
double PL02
double PL01_real
initial path loss
double PL02_real
double alpha1
pathloss exponents
double alpha2
double breakpointDistance
Breakpoint distance squared.
double carrierFrequency
Carrier frequency in Hz.
bool useTorus
Information needed about the playground.
Coord playgroundSize
The size of the playground.
bool debug
Whether debug messages should be displayed.
cOutVector pathlosses
Detailed Description
Basic implementation of a BreakpointPathlossModel. This class can be used to implement the ieee802154 path loss model.
Constructor & Destructor Documentation
BreakpointPathlossModel::BreakpointPathlossModel () [inline]
Initializes the analogue model. playgroundSize need to be valid as long as this instance exists.
The constructor needs some specific knowledge in order to create its mapping properly:
Parameters:
alpha the coefficient alpha (specified e.g. in config.xml and passed in constructor call)
carrierFrequency the carrier frequency
useTorus information about the playground the host is moving in
playgroundSize information about the playground the host is moving in
debug display debug messages?
    : AnalogueModel()
    , PL01(0)
    , PL02(0)
    , PL01_real(0)
    , PL02_real(0)
    , alpha1(alpha1)
    , alpha2(alpha2)
    , breakpointDistance(breakpointDistance)
    , carrierFrequency(carrierFrequency)
    , useTorus(useTorus)
    , playgroundSize(playgroundSize)
    , debug(debug)
    , pathlosses()
  {
    pathlosses.setName("pathlosses");
  }
Member Function Documentation
void BreakpointPathlossModel::filterSignal (airframe_ptr_t frame, const Coord & sendersPos, const Coord & receiverPos) [virtual]
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Calculate the distance factor
Implements AnalogueModel.
References Signal::addAttenuation(), alpha1, breakpointDistance, debug, pathlosses, PL01_real, playgroundSize, TimeMapping< Interpolator >::setValue(), Coord::sqrdist(), Coord::sqrTorusDist(), and useTorus.
{
  Signal& signal = frame->getSignal();
  double distance = useTorus ? receiverPos.sqrTorusDist(sendersPos, playgroundSize)
                  : receiverPos.sqrdist(sendersPos);
  distance = sqrt(distance);
  debugEV << "distance is: " << distance << endl;
  if(distance <= 1.0) {
    //attenuation is negligible
    return;
  }
  double attenuation = 1;
  // PL(d) = PL0 + 10 alpha log10 (d/d0)
  // 10 ^ { PL(d)/10 } = 10 ^{PL0 + 10 alpha log10 (d/d0)}/10
  // 10 ^ { PL(d)/10 } = 10 ^ PL0/10 * 10 ^ { 10 log10 (d/d0)^alpha }/10
  // 10 ^ { PL(d)/10 } = 10 ^ PL0/10 * 10 ^ { log10 (d/d0)^alpha }
  // 10 ^ { PL(d)/10 } = 10 ^ PL0/10 * (d/d0)^alpha
  if(distance < breakpointDistance) {
    attenuation = attenuation * PL01_real;
    attenuation = attenuation * pow(distance, alpha1);
  } else {
    attenuation = attenuation * PL02_real;
    attenuation = attenuation * pow(distance/breakpointDistance, alpha2);
  }
  attenuation = 1/attenuation;
  debugEV << "attenuation is: " << attenuation << endl;
  if(debug) {
    pathlosses.record(10*log10(attenuation)); // in dB
  }
  //const DimensionSet& domain = DimensionSet::timeDomain;
  Argument arg; // default constructor initializes with a single dimension, time, and value 0 (offset from signal start)
  TimeMapping<Linear>* attMapping = new TimeMapping<Linear> (); // mapping performs a linear interpolation from our single point -> constant
  attMapping->setValue(arg, attenuation);
  /* at last add the created attenuation mapping to the signal */
  signal.addAttenuation(attMapping);
}
bool BreakpointPathlossModel::initFromMap (const ParameterMap & params) [virtual]
Initialize the analog model from XML map data.
This method should be defined for generic analog model initialization.
Parameters:
params The parameter map which was filled by XML reader.
Returns:
true if the initialization was successfully.
Reimplemented from AnalogueModel.
References alpha1, breakpointDistance, carrierFrequency, debug, PL01, PL01_real, playgroundSize, and useTorus.
{
    ParameterMap::const_iterator it;
    bool                         bInitSuccess = true;
    if ((it = params.find("seed")) != params.end()) {
        srand( ParameterMap::mapped_type(it->second).longValue() );
    }
    if ((it = params.find("alpha1")) != params.end()) {
        alpha1 = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No alpha1 defined in config.xml for BreakpointPathlossModel!");
    }
    if ((it = params.find("alpha2")) != params.end()) {
        alpha2 = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No alpha1 defined in config.xml for BreakpointPathlossModel!");
    }
    if ((it = params.find("L01")) != params.end()) {
        PL01      = ParameterMap::mapped_type(it->second).doubleValue();
        PL01_real = pow(10, PL01/10);
    }
    else {
        bInitSuccess = false;
        opp_warning("No L01 defined in config.xml for BreakpointPathlossModel!");
    }
    if ((it = params.find("L02")) != params.end()) {
        PL02      = ParameterMap::mapped_type(it->second).doubleValue();
        PL02_real = pow(10, PL02/10);
    }
    else {
        bInitSuccess = false;
        opp_warning("No L02 defined in config.xml for BreakpointPathlossModel!");
    }
    if ((it = params.find("breakpointDistance")) != params.end()) {
        breakpointDistance = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No breakpointDistance defined in config.xml for BreakpointPathlossModel!");
    }
    if ((it = params.find("useTorus")) != params.end()) {
        useTorus = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No useTorus defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("PgsX")) != params.end()) {
        playgroundSize.x = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No PgsX defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("PgsY")) != params.end()) {
        playgroundSize.y = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No PgsY defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("PgsZ")) != params.end()) {
        playgroundSize.z = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No PgsZ defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("debug")) != params.end()) {
        debug = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        debug = false;
    }
    if ((it = params.find("carrierFrequency")) != params.end()) {
        carrierFrequency = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No carrierFrequency defined in config.xml for SimplePathlossModel!");
    }
    return AnalogueModel::initFromMap(params) && bInitSuccess;
}
Member Data Documentation
cOutVector BreakpointPathlossModel::pathlosses [protected]
logs computed pathlosses.
Referenced by filterSignal().
double BreakpointPathlossModel::PL01 [protected]
Model to use for distances below breakpoint distance.
Model to use for distances larger than the breakpoint distance initial path loss in dB
Referenced by initFromMap().
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/BreakpointPathlossModel.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/BreakpointPathlossModel.cc