MiXiM: DeciderUWBIRED Class Reference
DeciderUWBIRED Class Reference
IEEE 802.15.4A - Classes that implement the IEEE 802.15.4A UWB PHY. | decider - decider modules
This class implements a model of an energy detection receiver that demodulates UWB-IR burst position modulation as defined in the IEEE802154A standard (mandatory mode, high PRF).
#include <DeciderUWBIRED.h>
Public Types
enum UWBIRED_CTRL_KIND { SYNC_SUCCESS = MacToPhyInterface::LAST_BASE_PHY_KIND+1, SYNC_FAILURE }
Control message kinds specific to DeciderUWBIRED. Currently defines a message kind that informs the MAC of a successful SYNC event at PHY layer.
Public Member Functions
DeciderUWBIRED (DeciderToPhyInterface *phy, double sensitivity, int myIndex, bool debug)
virtual bool initFromMap (const ParameterMap &params)
Initialize the decider from XML map data.
double getAvgThreshold () const
virtual void cancelProcessSignal ()
Cancels processing a AirFrame.
virtual void finish ()
Method to be called by an OMNeT-module during its own finish(), to enable a decider to do some things.
virtual ChannelState getChannelState () const
A function that returns information about the channel state.
Static Public Member Functions
static double getNoiseValue ()
Static Public Attributes
static const simsignalwrap_t catUWBIRPacketSignal = simsignalwrap_t("org.mixim.modules.utility.uwbirpacket")
Signal for emitting UWBIR packets.
static const double noiseVariance = 101.085E-12
static const double peakPulsePower = 1.3E-3
Protected Types
typedef std::map< Signal *, int > tSignalMap
typedef ConcatConstMapping
< std::multiplies< double > > MultipliedMapping
Protected Member Functions
virtual eSignalState getNextSignalState (eSignalState CurState) const
Returns the next signal state (END, HEADER, NEW).
virtual simtime_t getNextSignalHandleTime (const airframe_ptr_t frame) const
Returns the next handle time for scheduler.
virtual simtime_t processSignalHeader (airframe_ptr_t frame)
Processes the end of the header of a received Signal.
virtual DeciderResult * createResult (const airframe_ptr_t frame) const
Checks if the passed completed AirFrame was received correctly.
std::pair< bool, double > decodePacket (const airframe_ptr_t frame, std::vector< bool > *receivedBits, const IEEE802154A::config &cfg) const
virtual bool attemptSync (const airframe_ptr_t frame)
Static Protected Member Functions
static std::pair< double, double > integrateWindow (int symbol, simtime_t_cref now, simtime_t_cref burst, const AirFrameVector &airFrameVector, const ConstMapping *const signalPower, const airframe_ptr_t frame, const IEEE802154A::config &cfg)
Protected Attributes
double syncThreshold
bool syncAlwaysSucceeds
bool channelSensing
bool synced
bool alwaysFailOnDataInterference
UWBIRPacket packet
cOutVector receivedPulses
cOutVector syncThresholds
PhyLayerUWBIR * uwbiface
int nbCancelReceptions
int nbFinishTrackingFrames
Private Member Functions
DeciderUWBIRED (const DeciderUWBIRED &)
Copy constructor is not allowed.
DeciderUWBIRED & operator= (const DeciderUWBIRED &)
Assignment operator is not allowed.
Private Attributes
bool trace
bool stats
long nbFailedSyncs
long nbSuccessfulSyncs
double nbSymbols
double allThresholds
double vsignal2
double pulseSnrs
Detailed Description
This class implements a model of an energy detection receiver that demodulates UWB-IR burst position modulation as defined in the IEEE802154A standard (mandatory mode, high PRF).
The code modeling the frame clock synchronization is implemented in attemptSync(). Simply subclass this class and redefine attemptSync() if you wish to consider more sophisticated synchronization models.
To implement a coherent receiver, the easiest way to start is to copy-paste this code into a new class and rename it accordingly. Then, redefine decodePacket().
Citation of the following publication is appreciated if you use the MiXiM UWB PHY model for a publication of your own. J. Rousselot, J.-D. Decotignie, An ultra-wideband impulse radio PHY layer model for network simulation. SIMULATION January 2011 vol. 87 no. 1-2 82-112.
For more information, see also:
[1] J. Rousselot, J.-D. Decotignie, An ultra-wideband impulse radio PHY layer model for network simulation. SIMULATION January 2011 vol. 87 no. 1-2 82-112. http://dx.doi.org/10.1177/0037549710377767 [2] J. Rousselot, Ultra Low Power Communication Protocols for UWB Impulse Radio Wireless Sensor Networks. EPFL Thesis 4720, 2010. http://infoscience.epfl.ch/record/147987 [3] A High-Precision Ultra Wideband Impulse Radio Physical Layer Model for Network Simulation, Jérôme Rousselot, Jean-Dominique Decotignie, Second International Omnet++ Workshop,Simu'TOOLS, Rome, 6 Mar 09. http://portal.acm.org/citation.cfm?id=1537714
Member Function Documentation
DeciderResult * DeciderUWBIRED::createResult (const airframe_ptr_t frame) const [protected, virtual]
Checks if the passed completed AirFrame was received correctly.
Returns the result as a DeciderResult
Returns:
The result of the decider for the passed AirFrame.
Reimplemented from BaseDecider.
References BaseDecider::currentSignal, and BaseDecider::tProcessingSignal::first.
{
  if (currentSignal.first == frame) {
    ++nbFinishTrackingFrames;
    vector<bool>*           receivedBits   = new vector<bool>();
    AirFrameUWBIR*          frameuwb       = check_and_cast<AirFrameUWBIR*>(frame);
    std::pair<bool, double> pairCorrectSnr = decodePacket(frame, receivedBits, frameuwb->getCfg());
    // we cannot compute bit error rate here
    // so we send the packet to the MAC layer which will compare receivedBits
    // with the actual bits sent (stored in the encapsulated UWBIRMacPkt object).
    DeciderResultUWBIR * result = new DeciderResultUWBIR(pairCorrectSnr.first && !frame->hasBitError(), receivedBits, pairCorrectSnr.second);
    uwbiface->switchRadioToSync();
    return result;
  }
  return NULL;
}
ChannelState DeciderUWBIRED::getChannelState () const [virtual]
A function that returns information about the channel state.
It is an alternative for the MACLayer in order to obtain information immediately (in contrast to sending a ChannelSenseRequest, i.e. sending a cMessage over the OMNeT-control-channel)
Reimplemented from BaseDecider.
{
  return ChannelState(true, 0);  // channel is always "sensed" free
}
simtime_t DeciderUWBIRED::getNextSignalHandleTime (const airframe_ptr_t frame) const [protected, virtual]
Returns the next handle time for scheduler.
Parameters:
frame The current frame which is in processing.
Returns:
The next scheduler handle time.
Reimplemented from BaseDecider.
References BaseDecider::currentSignal, BaseDecider::EXPECT_HEADER, BaseDecider::tProcessingSignal::first, BaseDecider::getSignalState(), IEEE802154A::mandatory_preambleLength, BaseDecider::NEW, and MappingUtils::pre().
{
    if (frame != currentSignal.first)
        return BaseDecider::getNextSignalHandleTime(frame);
    switch(getSignalState(frame)) {
        case NEW:           return BaseDecider::getNextSignalHandleTime(frame); break;
        case EXPECT_HEADER: {
            simtime_t tHandleTime = frame->getSignal().getReceptionStart() + IEEE802154A::mandatory_preambleLength;
            if (tHandleTime < frame->getSignal().getReceptionEnd())
                return tHandleTime;
            return MappingUtils::pre(frame->getSignal().getReceptionEnd());
        } break;
        default: break;
    }
    return BaseDecider::getNextSignalHandleTime(frame);
}
virtual eSignalState DeciderUWBIRED::getNextSignalState (eSignalState CurState) const [inline, protected, virtual]
Returns the next signal state (END, HEADER, NEW).
Parameters:
CurState The current signal state.
Returns:
The next signal state.
Reimplemented from BaseDecider.
References BaseDecider::EXPECT_HEADER, and BaseDecider::getNextSignalState().
Referenced by processSignalHeader().
{
    switch(CurState) {
      case NEW:           return EXPECT_HEADER;                             break;
      default:            break;
    }
    return BaseDecider::getNextSignalState(CurState);
  }
bool DeciderUWBIRED::initFromMap (const ParameterMap & params) [virtual]
Initialize the decider from XML map data.
This method should be defined for generic decider initialization.
Parameters:
params The parameter map which was filled by XML reader.
Returns:
true if the initialization was successfully.
Reimplemented from Decider.
Reimplemented in DeciderUWBIREDSyncOnAddress, and DeciderUWBIREDSync.
References catUWBIRPacketSignal, and simsignalwrap_t::initialize().
{
    bool                         bInitSuccess = true;
    ParameterMap::const_iterator it           = params.find("syncThreshold");
    if(it != params.end()) {
        syncThreshold = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No syncThreshold defined in config.xml for DeciderUWBIREDSync!");
    }
    it = params.find("stats");
    if(it != params.end()) {
        stats = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No stats defined in config.xml for DeciderUWBIREDSync!");
    }
    it = params.find("trace");
    if(it != params.end()) {
        trace = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No trace defined in config.xml for DeciderUWBIREDSync!");
    }
    it = params.find("syncAlwaysSucceeds");
    if(it != params.end()) {
        syncAlwaysSucceeds = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No syncAlwaysSucceeds defined in config.xml for DeciderUWBIREDSync!");
    }
    it = params.find("alwaysFailOnDataInterference");
    if(it != params.end()) {
        alwaysFailOnDataInterference = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        alwaysFailOnDataInterference = false;
    }
    catUWBIRPacketSignal.initialize();
    return BaseDecider::initFromMap(params) && bInitSuccess;
}
simtime_t DeciderUWBIRED::processSignalHeader (airframe_ptr_t) [protected, virtual]
Processes the end of the header of a received Signal.
Returns the time it wants to handle the signal again.
Default implementation does not handle signal headers.
Reimplemented from BaseDecider.
References catUWBIRPacketSignal, BaseDecider::currentSignal, BaseDecider::EXPECT_HEADER, getNextSignalState(), BasePhyLayer::getRadioState(), and DeciderToPhyInterface::sendControlMsgToMac().
{
  int currState = uwbiface->getRadioState();
  if (currentSignal.isProcessing() && currState == RadioUWBIR::SYNC) {
    // We are not tracking a signal currently.
    // Can we synchronize on this one ?
    bool isSyncSignalHigherThanThreshold;
    if(syncAlwaysSucceeds) {
      isSyncSignalHigherThanThreshold = true;
    } else {
      isSyncSignalHigherThanThreshold = attemptSync(frame);
    }
    packet.setNbSyncAttempts(packet.getNbSyncAttempts() + 1);
    if(isSyncSignalHigherThanThreshold) {
      ++nbSuccessfulSyncs;
      uwbiface->switchRadioToRX();
      packet.setNbSyncSuccesses(packet.getNbSyncSuccesses() + 1);
      // notify MAC layer through PHY layer
      cMessage* syncSuccessfulNotification = new cMessage("Ctrl_PHY2MAC_Sync_Success", SYNC_SUCCESS);
      phy->sendControlMsgToMac(syncSuccessfulNotification);
      // in any case, look at that frame again when it is finished
      // store this frame as signal to receive and set state
      setSignalState(frame, getNextSignalState(EXPECT_HEADER));
    } else {
      ++nbFailedSyncs;
      cMessage* syncFailureNotification = new cMessage("Ctrl_PHY2MAC_Sync_Failure", SYNC_FAILURE);
      phy->sendControlMsgToMac(syncFailureNotification);
      currentSignal.finishProcessing();
    }
    uwbiface->emit(catUWBIRPacketSignal, &packet);
  }
  return frame->getSignal().getReceptionEnd();
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/phy/DeciderUWBIRED.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/phy/DeciderUWBIRED.cc