MiXiM: DeciderToPhyInterface Class Reference
DeciderToPhyInterface Class Reference
decider - decider modules
This class is the interface for a Decider to the BasePhyLayer.
#include <DeciderToPhyInterface.h>
Public Types
typedef MiximAirFrame airframe_t
typedef airframe_t * airframe_ptr_t
typedef std::list< airframe_ptr_t > AirFrameVector
Type for container of AirFrames.
typedef std::map< std::string,
cMsgPar > ParameterMap
Used at initialization to pass the parameters to the AnalogueModel and Decider.
Public Member Functions
virtual void getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out) const =0
Fills the passed AirFrameVector with all air frames that intersect with the time interval [from, to] with same channel number.
virtual ConstMapping * getThermalNoise (simtime_t_cref from, simtime_t_cref to)=0
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
virtual void sendControlMsgToMac (cMessage *msg)=0
Called by the Decider to send a control message to the MACLayer.
virtual void sendUp (airframe_ptr_t packet, DeciderResult *result)=0
Called to send an AirFrame with DeciderResult to the MACLayer.
virtual simtime_t getSimTime () const =0
Returns the current simulation time.
virtual void cancelScheduledMessage (cMessage *msg)=0
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
virtual void rescheduleMessage (cMessage *msg, simtime_t_cref t)=0
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
virtual void drawCurrent (double amount, int activity)=0
Enables the Decider to draw Power from the phy layers power accounts.
virtual void recordScalar (const char *name, double value, const char *unit=NULL)=0
Utility method to enable a Decider, which isn't an OMNeT-module, to use the OMNeT-method 'recordScalar' with the help of and through its interface to BasePhyLayer.
virtual int getCurrentRadioChannel () const =0
Returns the channel currently used by the radio.
virtual int getNbRadioChannels () const =0
Returns the number of channels available in radio.
virtual bool isRadioInRX () const =0
Returns the true if the radio is in RX state.
virtual long getPhyHeaderLength () const =0
Returns the length of the phy header in bits.
Detailed Description
This class is the interface for a Decider to the BasePhyLayer.
The Decider can do the following things using it:
get the current simulation time
get the list of AirFrames that intersect with a specific time interval (to calculate SNR)
tell the BasePhyLayer to hand an AirFrame up to the MACLayer
tell the BasePhyLayer to send a control message to the MACLayer (to answer a ChannelSenseRequest)
Member Typedef Documentation
typedef std::list<airframe_ptr_t> DeciderToPhyInterface::AirFrameVector
Type for container of AirFrames.
Used as out-value in "getChannelInfo" method.
Member Function Documentation
virtual void DeciderToPhyInterface::cancelScheduledMessage (cMessage * msg) [pure virtual]
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
Used by the Decider if it doesn't need to handle an AirFrame or ControlMessage again anymore.
Implemented in BasePhyLayer.
Referenced by BaseDecider::channelStateChanged().
virtual void DeciderToPhyInterface::drawCurrent (double amount, int activity) [pure virtual]
Enables the Decider to draw Power from the phy layers power accounts.
Does nothing if no Battery module in simulation is present.
Implemented in BasePhyLayer, and PhyLayerBattery.
Referenced by Decider80211Battery::channelStateChanged().
virtual void DeciderToPhyInterface::getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector & out) const [pure virtual]
Fills the passed AirFrameVector with all air frames that intersect with the time interval [from, to] with same channel number.
Parameters:
[in] from The interval start time (included).
[in] to The interval end time (included).
[out] out The vector where the air frames shall be inserted.
Implemented in BasePhyLayer.
Referenced by BaseDecider::getChannelInfo().
virtual long DeciderToPhyInterface::getPhyHeaderLength () const [pure virtual]
Returns the length of the phy header in bits.
If the decider should handle frame header retrieval he did needs the length of the phy header for calculation of next air frame handle time.
Implemented in BasePhyLayer.
Referenced by BaseDecider::getNextSignalHandleTime().
virtual ConstMapping* DeciderToPhyInterface::getThermalNoise (simtime_t_cref from, simtime_t_cref to) [pure virtual]
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
The implementing class of this method keeps ownership of the Mapping.
Implemented in BasePhyLayer.
Referenced by BaseDecider::calculateRSSIMapping().
virtual void DeciderToPhyInterface::recordScalar (const char * name, double value, const char * unit = NULL) [pure virtual]
Utility method to enable a Decider, which isn't an OMNeT-module, to use the OMNeT-method 'recordScalar' with the help of and through its interface to BasePhyLayer.
The method-signature is taken from OMNeTs 'ccomponent.h' but made pure virtual here. See the original method-description below:
Records a double into the scalar result file.
Implemented in BasePhyLayer.
Referenced by DeciderUWBIRED::finish(), and BaseDecider::finish().
virtual void DeciderToPhyInterface::rescheduleMessage (cMessage * msg, simtime_t_cref t) [pure virtual]
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
Used by the Decider if it has to handle an AirFrame or an control message earlier than it has returned to the PhyLayer the last time the Decider handled that message.
Implemented in BasePhyLayer.
Referenced by BaseDecider::channelStateChanged().
virtual void DeciderToPhyInterface::sendControlMsgToMac (cMessage * msg) [pure virtual]
Called by the Decider to send a control message to the MACLayer.
This function can be used to answer a ChannelSenseRequest to the MACLayer
Implemented in BasePhyLayer.
Referenced by SNRThresholdDecider::answerCSR(), BaseDecider::answerCSR(), BaseDecider::processSignalEnd(), Decider802154Narrow::processSignalHeader(), and DeciderUWBIRED::processSignalHeader().
virtual void DeciderToPhyInterface::sendUp (airframe_ptr_t packet, DeciderResult * result) [pure virtual]
Called to send an AirFrame with DeciderResult to the MACLayer.
When a packet is completely received and not noise, the Decider call this function to send the packet together with the corresponding DeciderResult up to MACLayer
Implemented in BasePhyLayer.
Referenced by ThresholdDecider::handleSignalOver(), and BaseDecider::processSignalEnd().
The documentation for this class was generated from the following file:
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/DeciderToPhyInterface.h