MiXiM: Decider Class Reference
Decider Class Reference
decider - decider modules
The basic Decider class.
#include <Decider.h>
Public Types
typedef
DeciderToPhyInterface::airframe_ptr_t airframe_ptr_t
Public Member Functions
Decider (DeciderToPhyInterface *phy)
Initializes the Decider with a pointer to its PhyLayer.
virtual bool initFromMap (const ParameterMap &)
Initialize the decider from XML map data.
virtual simtime_t processSignal (airframe_ptr_t frame)
This function processes a AirFrame given by the PhyLayer and returns the time point when Decider wants to be given the AirFrame again.
virtual void cancelProcessSignal ()
Cancels processing a AirFrame.
virtual ChannelState getChannelState () const
A function that returns information about the channel state.
virtual simtime_t handleChannelSenseRequest (ChannelSenseRequest *request)
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
virtual void finish ()
Method to be called by an OMNeT-module during its own finish(), to enable a decider to do some things.
virtual void channelChanged (int)
Called by phy layer to indicate that the channel this radio currently listens to has changed.
Static Public Attributes
static const_simtime_t notAgain
simtime that tells the Phy-Layer not to pass an AirFrame again
Protected Types
typedef
DeciderToPhyInterface::AirFrameVector AirFrameVector
Defines what an AirFrameVector shall be here.
typedef
DeciderToPhyInterface::ParameterMap ParameterMap
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Protected Attributes
DeciderToPhyInterface *const phy
A pointer to the physical layer of this Decider.
Private Member Functions
Decider (const Decider &)
Copy constructor is not allowed.
Decider & operator= (const Decider &)
Assignment operator is not allowed.
Detailed Description
The basic Decider class.
The Deciders tasks are: 1. decide which packets should be handed up to the MAC Layer (primary task) 2. decide whether the channel is busy/idle at a time point or during a time interval (channel sensing)
BasePhyLayer hands every receiving AirFrame several times to the "processSignal()"-function and is returned a time point when to do so again.
Member Typedef Documentation
typedef DeciderToPhyInterface::airframe_ptr_t Decider::airframe_ptr_t
Defines the AirFrame pointer type which will be used as AirFrame.
Member Function Documentation
virtual void Decider::channelChanged (int) [inline, virtual]
Called by phy layer to indicate that the channel this radio currently listens to has changed.
Sub-classing deciders which support multiple channels should override this method to handle the effects of channel changes on ongoing receptions.
Parameters:
newChannel The new channel the radio has changed to.
Reimplemented in BaseDecider, and Decider80211MultiChannel.
Referenced by BasePhyLayer::setCurrentRadioChannel().
{}
ChannelState Decider::getChannelState () const [virtual]
A function that returns information about the channel state.
It is an alternative for the MACLayer in order to obtain information immediately (in contrast to sending a ChannelSenseRequest, i.e. sending a cMessage over the OMNeT-control-channel)
Reimplemented in BaseDecider, ThresholdDecider, SNRThresholdDecider, and DeciderUWBIRED.
Referenced by BasePhyLayer::getChannelState().
{
  return ChannelState();
}
simtime_t Decider::handleChannelSenseRequest (ChannelSenseRequest * request) [virtual]
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
The MACLayer is able to send a ChannelSenseRequest to the PhyLayer that calls this function with it and is returned a time point when to re-call this function with the specific ChannelSenseRequest.
The Decider puts the result (ChannelState) to the ChannelSenseRequest and "answers" by calling the "sendControlMsg"-function on the DeciderToPhyInterface, i.e. telling the PhyLayer to send it back.
Reimplemented in BaseDecider, and ThresholdDecider.
References notAgain.
Referenced by BasePhyLayer::handleChannelSenseRequest().
{
  return notAgain;
}
virtual bool Decider::initFromMap (const ParameterMap &) [inline, virtual]
Initialize the decider from XML map data.
This method should be defined for generic decider initialization.
Parameters:
params The parameter map which was filled by XML reader.
Returns:
true if the initialization was successfully.
Reimplemented in ThresholdDecider, SNRThresholdDecider, Decider802154Narrow, Decider80211, DeciderUWBIRED, DeciderUWBIREDSyncOnAddress, Decider80211Battery, and DeciderUWBIREDSync.
{ return true; }
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/Decider.h
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/Decider.cc