MiXiM: BasePhyLayer Class Reference
BasePhyLayer Class Reference
phyLayer - physical layer modules | baseModules - base module classes of MiXiM
The BasePhyLayer represents the physical layer of a nic.
#include <BasePhyLayer.h>
Public Member Functions
virtual ~BasePhyLayer ()
virtual void finish ()
Only calls the deciders finish method.
virtual cObject * setUpControlInfo (cMessage *const pMsg, DeciderResult *const pDeciderResult)
Attaches a "control info" (PhyToMac) structure (object) to the message pMsg.
MacToPhyInterface implementation
These methods implement the MacToPhyInterface.
virtual int getRadioState () const
Returns the current state the radio is in.
virtual bool isRadioInRX () const
Returns the true if the radio is in RX state.
virtual simtime_t setRadioState (int rs)
Tells the BasePhyLayer to switch to the specified radio state.
virtual ChannelState getChannelState () const
Returns the current state of the channel.
virtual long getPhyHeaderLength () const
Returns the length of the phy header in bits.
virtual void setCurrentRadioChannel (int newRadioChannel)
Sets the channel currently used by the radio.
virtual int getCurrentRadioChannel () const
Returns the channel currently used by the radio.
virtual int getNbRadioChannels () const
Returns the number of channels available on this radio.
DeciderToPhyInterface implementation
These methods implement the DeciderToPhyInterface.
virtual void getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out) const
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
virtual ConstMapping * getThermalNoise (simtime_t_cref from, simtime_t_cref to)
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
virtual void sendControlMsgToMac (cMessage *msg)
Called by the Decider to send a control message to the MACLayer.
virtual void sendUp (airframe_ptr_t packet, DeciderResult *result)
Called to send an AirFrame with DeciderResult to the MACLayer.
virtual simtime_t getSimTime () const
Returns the current simulation time.
virtual void cancelScheduledMessage (cMessage *msg)
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
virtual void rescheduleMessage (cMessage *msg, simtime_t_cref t)
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
virtual void drawCurrent (double amount, int activity)
Does nothing. For an actual power supporting phy see "PhyLayerBattery".
void recordScalar (const char *name, double value, const char *unit=NULL)
Records a double into the scalar result file.
Protected Types
enum ProtocolIds { GENERIC = 0 }
enum eAirFrameStates { START_RECEIVE = 1, RECEIVING, END_RECEIVE }
The states of the receiving process for AirFrames.
typedef std::vector
< AnalogueModel * > AnalogueModelList
Used to store the AnalogueModels to be used as filters.
Protected Member Functions
template<class T >
T readPar (const char *parName, const T defaultValue) const
Reads and returns the parameter with the passed name.
virtual void initialize (int stage)
OMNeT++ initialization function.
virtual void handleMessage (cMessage *msg)
OMNeT++ handle message function.
virtual MiximRadio * initializeRadio () const
Initializes and returns the radio class to use.
virtual AnalogueModel * getAnalogueModelFromName (const std::string &name, ParameterMap &params) const
Creates and returns an instance of the AnalogueModel with the specified name.
template<class _AMODEL_CLASS_ >
_AMODEL_CLASS_ * createAnalogueModel (const ParameterMap &params) const
Creates and returns an instance of the analogue model with the specified _AMODEL_CLASS_.
virtual Decider * getDeciderFromName (const std::string &name, ParameterMap &params)
Creates and returns an instance of the Decider with the specified name.
template<class _DECIDER_CLASS_ >
_DECIDER_CLASS_ * createDecider (const ParameterMap &params)
Creates and returns an instance of the Decider with the specified _DECIDER_CLASS_.
virtual airframe_ptr_t encapsMsg (cPacket *msg)
This function encapsulates messages from the upper layer into an AirFrame and sets all necessary attributes.
virtual void filterSignal (airframe_ptr_t frame)
Filters the passed AirFrame's Signal by every registered AnalogueModel.
virtual void finishRadioSwitching (bool bSendCtrlMsg=true)
Called the moment the simulated switching process of the MiximRadio is finished.
virtual int myProtocolId () const
Returns the identifier of the protocol this phy uses to send messages.
virtual bool isKnownProtocolId (int id) const
Returns true if the protocol with the passed identifier is decodeable by the decider.
template<>
simtime_t readPar (const char *parName, const simtime_t defaultValue) const
Handle Messages
virtual void handleAirFrame (airframe_ptr_t frame)
Handles messages received from the channel (probably AirFrames).
virtual void handleUpperMessage (cMessage *msg)
Handles messages received from the upper layer through the data gate.
virtual void handleUpperControlMessage (cMessage *msg)
Handles messages received from the upper layer through the control gate.
virtual void handleSelfMessage (cMessage *msg)
Handles self scheduled messages.
virtual void handleChannelSenseRequest (cMessage *msg)
Handles reception of a ChannelSenseRequest by forwarding it to the decider and scheduling it to the point in time returned by the decider.
void handleAirFrameFirstReceive (airframe_ptr_t msg)
Handles incoming AirFrames with the state FIRST_RECEIVE.
virtual void handleAirFrameStartReceive (airframe_ptr_t msg)
Handles incoming AirFrames with the state START_RECEIVE.
virtual void handleAirFrameReceiving (airframe_ptr_t msg)
Handles incoming AirFrames with the state RECEIVING.
virtual void handleAirFrameEndReceive (airframe_ptr_t msg)
Handles incoming AirFrames with the state END_RECEIVE.
Send Messages
void sendControlMessageUp (cMessage *msg)
Sends the passed control message to the upper layer.
void sendMacPktUp (cMessage *pkt)
Sends the passed MacPkt to the upper layer.
void sendMessageDown (airframe_ptr_t pkt)
Sends the passed AirFrame to the channel.
void sendSelfMessage (cMessage *msg, simtime_t_cref time)
Schedule self message to passed point in time.
Protected Attributes
int protocolId
ConstantSimpleConstMapping * thermalNoise
Defines the strength of the thermal noise.
double maxTXPower
The maximum transmission power a message can be send with.
double sensitivity
The sensitivity describes the minimum strength a signal must have to be received.
bool recordStats
Stores if tracking of statistics (esp. cOutvectors) is enabled.
ChannelInfo channelInfo
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
MiximRadio * radio
The state machine storing the current radio state (TX, RX, SLEEP).
Decider * decider
Pointer to the decider module.
AnalogueModelList analogueModels
List of the analogue models to use.
int upperLayerIn
The id of the in-data gate from the Mac layer.
int upperLayerOut
The id of the out-data gate to the Mac layer.
int upperControlOut
The id of the out-control gate to the Mac layer.
int upperControlIn
The id of the in-control gate from the Mac layer.
cMessage * radioSwitchingOverTimer
Self message scheduled to the point in time when the switching process of the radio is over.
cMessage * txOverTimer
Self message scheduled to the point in time when the transmission of an AirFrame is over.
long headerLength
Stores the length of the phy header in bits.
BaseWorldUtility * world
Pointer to the World Utility, to obtain some global information.
Static Protected Attributes
static short airFramePriority = 10
Defines the scheduling priority of AirFrames.
Private Member Functions
void getParametersFromXML (cXMLElement *xmlData, ParameterMap &outputMap) const
Utility function. Reads the parameters of a XML element and stores them in the passed ParameterMap reference.
void initializeAnalogueModels (cXMLElement *xmlConfig)
Initializes the AnalogueModels with the data from the passed XML-config data.
void initializeDecider (cXMLElement *xmlConfig)
Initializes the Decider with the data from the passed XML-config data.
BasePhyLayer (const BasePhyLayer &)
Copy constructor is not allowed.
BasePhyLayer & operator= (const BasePhyLayer &)
Assignment operator is not allowed.
Detailed Description
The BasePhyLayer represents the physical layer of a nic.
The BasePhyLayer is directly connected to the mac layer via OMNeT channels and is able to send messages to other physical layers through sub-classing from ChannelAcces.
The BasePhyLayer encapsulates two sub modules. The AnalogueModels, which are responsible for simulating the attenuation of received signals and the Decider which provides the main functionality of the physical layer like signal classification (noise or not noise) and demodulation (calculating transmission errors).
The BasePhyLayer itself is responsible for the OMNeT depended parts of the physical layer which are the following:
Module initialization:
read ned-parameters and initialize module, Decider and AnalogueModels.
Message handling:
receive messages from mac layer and hand them to the Decider or directly send them to the channel
receive AirFrames from the channel, hand them to the AnalogueModels for filtering, simulate delay and transmission duration, hand it to the Decider for evaluation and send received packets to the mac layer
keep track of currently active AirFrames on the channel (see ChannelInfo)
The actual evaluation of incoming signals is done by the Decider.
base class ConnectionManagerAccess:
provides access to the channel via the ConnectionManager
base class DeciderToPhyInterface:
interface for the Decider
base class MacToPhyInterface:
interface for the Mac
Member Enumeration Documentation
enum BasePhyLayer::eAirFrameStates [protected]
The states of the receiving process for AirFrames.
Enumerator:
START_RECEIVE
Start of actual receiving process of the AirFrame.
RECEIVING
AirFrame is being received.
END_RECEIVE
Receiving process over.
                       {
    START_RECEIVE = 1,
    RECEIVING,
    END_RECEIVE
  };
Constructor & Destructor Documentation
BasePhyLayer::~BasePhyLayer () [virtual]
Free the pointer to the decider and the AnalogueModels and the Radio.
References analogueModels, channelInfo, decider, ChannelInfo::getAirFrames(), MiximRadio::getAnalogueModel(), radio, radioSwitchingOverTimer, thermalNoise, and txOverTimer.
{
  //get AirFrames from ChannelInfo and delete
  //(although ChannelInfo normally owns the AirFrames it
  //is not able to cancel and delete them itself
  AirFrameVector channel;
  channelInfo.getAirFrames(0, simTime(), channel);
  for(AirFrameVector::iterator it = channel.begin();
    it != channel.end(); ++it)
  {
    cancelAndDelete(*it);
  }
  //free timer messages
  if(txOverTimer) {
    cancelAndDelete(txOverTimer);
  }
  if(radioSwitchingOverTimer) {
    cancelAndDelete(radioSwitchingOverTimer);
  }
  //free thermal noise mapping
  if(thermalNoise) {
    delete thermalNoise;
  }
  //free Decider
  if(decider != 0) {
    delete decider;
  }
  /*
   * get a pointer to the radios RSAM again to avoid deleting it,
   * it is not created by calling new (BasePhyLayer is not the owner)!
   */
  AnalogueModel* rsamPointer = radio ? radio->getAnalogueModel() : NULL;
  //free AnalogueModels
  for(AnalogueModelList::const_iterator it = analogueModels.begin();
    it != analogueModels.end(); ++it) {
    AnalogueModelList::value_type tmp = *it;
    // do not delete the RSAM, it's not allocated by new!
    if (tmp == rsamPointer) {
      rsamPointer = 0;
      continue;
    }
    if(tmp != 0) {
      delete tmp;
    }
  }
  // free radio
  if(radio != 0) {
    delete radio;
  }
}
Member Function Documentation
void BasePhyLayer::cancelScheduledMessage (cMessage * msg) [virtual]
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
Used by the Decider if it doesn't need to handle an AirFrame or ControlMessage again anymore.
Implements DeciderToPhyInterface.
Referenced by rescheduleMessage().
{
  if(msg->isScheduled()){
    cancelEvent(msg);
  } else {
    EV << "Warning: Decider wanted to cancel a scheduled message but message"
       << " wasn't actually scheduled. Message is: " << msg << endl;
  }
}
template<class _AMODEL_CLASS_ > _AMODEL_CLASS_* BasePhyLayer::createAnalogueModel (const ParameterMap & params) const [inline, protected]
Creates and returns an instance of the analogue model with the specified _AMODEL_CLASS_.
The returned Decider has to be generated with the "new" command.
Returns:
Instance of the Decider with the specified class type.
{
    _AMODEL_CLASS_ *const pAnalogueModel = new _AMODEL_CLASS_();
    if (pAnalogueModel != NULL && !pAnalogueModel->initFromMap(params)) {
      opp_warning("Analog model from config.xml could not be initialized correctly!");
    }
    return pAnalogueModel;
  }
template<class _DECIDER_CLASS_ > _DECIDER_CLASS_* BasePhyLayer::createDecider (const ParameterMap & params) [inline, protected]
Creates and returns an instance of the Decider with the specified _DECIDER_CLASS_.
The returned Decider has to be generated with the "new" command.
Returns:
Instance of the Decider with the specified class type.
References BaseModule::findHost().
{
    _DECIDER_CLASS_ *const pDecider = new _DECIDER_CLASS_(this, sensitivity, findHost()->getIndex(), coreDebug);
    if (pDecider != NULL && !pDecider->initFromMap(params)) {
      opp_warning("Decider from config.xml could not be initialized correctly!");
    }
    return pDecider;
  }
void BasePhyLayer::filterSignal (airframe_ptr_t frame) [protected, virtual]
Filters the passed AirFrame's Signal by every registered AnalogueModel.
claim the Move pattern of the sender from the Signal
References analogueModels, and ConnectionManagerAccess::getMobilityModule().
Referenced by handleAirFrameStartReceive().
{
  if (analogueModels.empty())
    return;
  ConnectionManagerAccess *const senderModule   = dynamic_cast<ConnectionManagerAccess *const>(frame->getSenderModule());
  ConnectionManagerAccess *const receiverModule = dynamic_cast<ConnectionManagerAccess *const>(frame->getArrivalModule());
  //const simtime_t      sStart         = frame->getSignal().getReceptionStart();
  assert(senderModule); assert(receiverModule);
  ChannelMobilityPtrType sendersMobility  = senderModule   ? senderModule->getMobilityModule()   : NULL;
  ChannelMobilityPtrType receiverMobility = receiverModule ? receiverModule->getMobilityModule() : NULL;
  const Coord sendersPos  = sendersMobility  ? sendersMobility->getCurrentPosition(/*sStart*/) : NoMobiltyPos;
  const Coord receiverPos = receiverMobility ? receiverMobility->getCurrentPosition(/*sStart*/): NoMobiltyPos;
  for(AnalogueModelList::const_iterator it = analogueModels.begin(); it != analogueModels.end(); ++it)
    (*it)->filterSignal(frame, sendersPos, receiverPos);
}
void BasePhyLayer::finishRadioSwitching (bool bSendCtrlMsg = true) [protected, virtual]
Called the moment the simulated switching process of the MiximRadio is finished.
The Radio is set the new RadioState and the MAC Layer is sent a confirmation message.
Parameters:
bSendCtrlMsg Flag for sending control message to MAC (in case of zero switch time this flag maybe false).
Reimplemented in PhyLayerBattery.
References MiximRadio::endSwitch(), radio, MacToPhyInterface::RADIO_SWITCHING_OVER, and sendControlMsgToMac().
Referenced by handleSelfMessage(), and setRadioState().
{
  radio->endSwitch(simTime());
  if (bSendCtrlMsg) {
      sendControlMsgToMac(new cMessage("Radio switching over", RADIO_SWITCHING_OVER));
  }
}
AnalogueModel * BasePhyLayer::getAnalogueModelFromName (const std::string & name, ParameterMap & params) const [protected, virtual]
Creates and returns an instance of the AnalogueModel with the specified name.
The returned AnalogueModel has to be generated with the "new" command. The BasePhyLayer keeps the ownership of the returned AnalogueModel.
This method is used by the BasePhyLayer during initialization to load the AnalogueModels which has been specified in the ned file.
This method has to be overridden if you want to be able to load your own AnalogueModels.
Is able to initialize the following AnalogueModels:
RadioStateAnalogueModel
Reimplemented in PhyLayerUWBIR, PhyLayer, and SamplePhyLayer.
References MiximRadio::getAnalogueModel(), and radio.
Referenced by initializeAnalogueModels().
{
  // add default analogue models here
  // case "RSAM", pointer is valid as long as the radio exists
  if (name == "RadioStateAnalogueModel") {
    return radio->getAnalogueModel();
  }
  return NULL;
}
ChannelState BasePhyLayer::getChannelState () const [virtual]
Returns the current state of the channel.
See ChannelState for details.
Implements MacToPhyInterface.
References decider, and Decider::getChannelState().
{
  Enter_Method_Silent();
  assert(decider);
  return decider->getChannelState();
}
Decider * BasePhyLayer::getDeciderFromName (const std::string & name, ParameterMap & params) [protected, virtual]
Creates and returns an instance of the Decider with the specified name.
The returned Decider has to be generated with the "new" command. The BasePhyLayer keeps the ownership of the returned Decider.
This method is used by the BasePhyLayer during Initialization to load the decider which has been specified in the config.xml file.
This method has to be overridden if you want to be able to load your own decider.
Returns:
Instance of the decider with the specified name.
Reimplemented in PhyLayerUWBIR, PhyLayerBattery, PhyLayer, and SamplePhyLayer.
Referenced by initializeDecider().
{
  return NULL;
}
long BasePhyLayer::getPhyHeaderLength () const [virtual]
Returns the length of the phy header in bits.
Both the MAC and the PHY needs the header length.
Implements DeciderToPhyInterface.
References headerLength.
{
  Enter_Method_Silent();
  if (headerLength < 0)
    return par("headerLength").longValue();
  return headerLength;
}
int BasePhyLayer::getRadioState () const [virtual]
Returns the current state the radio is in.
See RadioState for possible values.
This method is mainly used by the mac layer.
Implements MacToPhyInterface.
References MiximRadio::getCurrentState(), and radio.
Referenced by PhyLayerUWBIR::isRadioInRX(), isRadioInRX(), and DeciderUWBIRED::processSignalHeader().
{
  Enter_Method_Silent();
  assert(radio);
  return radio->getCurrentState();
}
ConstMapping * BasePhyLayer::getThermalNoise (simtime_t_cref from, simtime_t_cref to) [virtual]
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
The implementing class of this method keeps ownership of the Mapping.
This implementation returns a constant mapping with the value of the "thermalNoise" module parameter
Override this method if you want to define a more complex thermal noise.
Implements DeciderToPhyInterface.
References SimpleConstMapping::initializeArguments(), and thermalNoise.
{
  if(thermalNoise)
    thermalNoise->initializeArguments(Argument(from));
  return thermalNoise;
}
void BasePhyLayer::handleMessage (cMessage * msg) [protected, virtual]
OMNeT++ handle message function.
Classify and forward message to subroutines.
AirFrames from channel
self scheduled AirFrames
MacPackets from MAC layer
ControllMesasges from MAC layer
self messages like TX_OVER and RADIO_SWITCHED
Reimplemented in SamplePhyLayer.
References MacToPhyInterface::AIR_FRAME, handleAirFrame(), handleSelfMessage(), handleUpperControlMessage(), handleUpperMessage(), upperControlIn, and upperLayerIn.
{
  //self messages
  if(msg->isSelfMessage()) {
    handleSelfMessage(msg);
  //MacPkts <- MacToPhyControlInfo
  } else if(msg->getArrivalGateId() == upperLayerIn) {
    handleUpperMessage(msg);
  //controlmessages
  } else if(msg->getArrivalGateId() == upperControlIn) {
    handleUpperControlMessage(msg);
  //AirFrames
  } else if(msg->getKind() == AIR_FRAME){
    handleAirFrame(static_cast<airframe_ptr_t>(msg));
  //unknown message
  } else {
    ev << "Unknown message received." << endl;
    delete msg;
  }
}
void BasePhyLayer::initialize (int stage) [protected, virtual]
OMNeT++ initialization function.
Read simple parameters. Read and parse xml file for decider and analogue models configuration.
Reimplemented from ConnectionManagerAccess.
Reimplemented in PhyLayerUWBIR, PhyLayerBattery, and SamplePhyLayer.
References ConnectionManagerAccess::cc, FWMath::dBm2mW(), headerLength, initializeAnalogueModels(), initializeDecider(), initializeRadio(), maxTXPower, radio, MacToPhyInterface::RADIO_SWITCHING_OVER, radioSwitchingOverTimer, recordStats, sensitivity, thermalNoise, DimensionSet::timeDomain, MacToPhyInterface::TX_OVER, txOverTimer, upperControlIn, upperControlOut, upperLayerIn, upperLayerOut, and world.
{
  ConnectionManagerAccess::initialize(stage);
  if (stage == 0) {
    // if using sendDirect, make sure that messages arrive without delay
    gate("radioIn")->setDeliverOnReceptionStart(true);
    //get gate ids
    upperLayerIn = findGate("upperLayerIn");
    upperLayerOut = findGate("upperLayerOut");
    upperControlOut = findGate("upperControlOut");
    upperControlIn = findGate("upperControlIn");
    //read simple ned-parameters
    //  - initialize basic parameters
    if(par("useThermalNoise").boolValue()) {
      double thermalNoiseVal = FWMath::dBm2mW(par("thermalNoise").doubleValue());
      thermalNoise = new ConstantSimpleConstMapping(DimensionSet::timeDomain,
                              thermalNoiseVal);
    } else {
      thermalNoise = 0;
    }
    headerLength = par("headerLength").longValue();
    sensitivity = par("sensitivity").doubleValue();
    if (!isFiniteNumber(sensitivity) || sensitivity <= -999999)
        sensitivity = 0; // disabled
    else
        sensitivity = FWMath::dBm2mW(sensitivity);
    if (!isFiniteNumber(sensitivity))
        sensitivity = 0; // disabled
    maxTXPower = par("maxTXPower").doubleValue();
    recordStats = par("recordStats").boolValue();
    //  - initialize radio
    radio = initializeRadio();
    // get pointer to the world module
    world = FindModule<BaseWorldUtility*>::findGlobalModule();
        if (world == NULL) {
            opp_error("Could not find BaseWorldUtility module");
        }
        if(cc->hasPar("sat")
       && (sensitivity - FWMath::dBm2mW(cc->par("sat").doubleValue())) < -0.000001) {
            opp_error("Sensitivity can't be smaller than the "
            "signal attenuation threshold (sat) in ConnectionManager. "
            "Please adjust your omnetpp.ini file accordingly.");
    }
//  } else if (stage == 1){
    //read complex(xml) ned-parameters
    //  - analogue model parameters
    initializeAnalogueModels(par("analogueModels").xmlValue());
    //  - decider parameters
    initializeDecider(par("decider").xmlValue());
    //initialise timer messages
    radioSwitchingOverTimer = new cMessage("radio switching over", RADIO_SWITCHING_OVER);
    txOverTimer = new cMessage("transmission over", TX_OVER);
  }
}
MiximRadio * BasePhyLayer::initializeRadio () const [protected, virtual]
Initializes and returns the radio class to use.
Can be overridden by sub-classing phy layers to use their own Radio implementations.
Reimplemented in PhyLayerUWBIR.
References MiximRadio::createNewRadio(), radio, readPar(), recordStats, MiximRadio::RX, MiximRadio::setSwitchTime(), MiximRadio::SLEEP, and MiximRadio::TX.
Referenced by initialize().
{
  int    initialRadioState   = par("initialRadioState").longValue();
  double radioMinAtt         = par("radioMinAtt").doubleValue();
  double radioMaxAtt         = par("radioMaxAtt").doubleValue();
  int    nbRadioChannels     = readPar("nbRadioChannels",     1);
  int    initialRadioChannel = readPar("initialRadioChannel", 0);
  MiximRadio* radio = MiximRadio::createNewRadio(recordStats, initialRadioState,
                     radioMinAtt, radioMaxAtt,
                     initialRadioChannel, nbRadioChannels);
  //  - switch times to TX
  //if no RX to TX defined asume same time as sleep to TX
  radio->setSwitchTime(MiximRadio::RX, MiximRadio::TX, (hasPar("timeRXToTX") ? par("timeRXToTX") : par("timeSleepToTX")).doubleValue());
  //if no sleep to TX defined asume same time as RX to TX
  radio->setSwitchTime(MiximRadio::SLEEP, MiximRadio::TX, (hasPar("timeSleepToTX") ? par("timeSleepToTX") : par("timeRXToTX")).doubleValue());
  //  - switch times to RX
  //if no TX to RX defined asume same time as sleep to RX
  radio->setSwitchTime(MiximRadio::TX, MiximRadio::RX, (hasPar("timeTXToRX") ? par("timeTXToRX") : par("timeSleepToRX")).doubleValue());
  //if no sleep to RX defined asume same time as TX to RX
  radio->setSwitchTime(MiximRadio::SLEEP, MiximRadio::RX, (hasPar("timeSleepToRX") ? par("timeSleepToRX") : par("timeTXToRX")).doubleValue());
  //  - switch times to sleep
  //if no TX to sleep defined asume same time as RX to sleep
  radio->setSwitchTime(MiximRadio::TX, MiximRadio::SLEEP, (hasPar("timeTXToSleep") ? par("timeTXToSleep") : par("timeRXToSleep")).doubleValue());
  //if no RX to sleep defined asume same time as TX to sleep
  radio->setSwitchTime(MiximRadio::RX, MiximRadio::SLEEP, (hasPar("timeRXToSleep") ? par("timeRXToSleep") : par("timeTXToSleep")).doubleValue());
  return radio;
}
virtual bool BasePhyLayer::isKnownProtocolId (int id) const [inline, protected, virtual]
Returns true if the protocol with the passed identifier is decodeable by the decider.
If the protocol with the passed id is not understood by this phy layers decider the according AirFrame is not passed to the it but only is added to channel info to be available as interference to the decider.
Default implementation checks only if the passed id is the same as the one returned by "myProtocolId()".
Parameters:
id The identifier of the protocol of an AirFrame.
Returns:
Returns true if the passed protocol id is supported by this phy- layer.
Referenced by handleAirFrameStartReceive().
{ return id == myProtocolId(); }
virtual int BasePhyLayer::myProtocolId () const [inline, protected, virtual]
Returns the identifier of the protocol this phy uses to send messages.
Returns:
An integer representing the identifier of the used protocol.
Referenced by PhyLayerUWBIR::encapsMsg(), and encapsMsg().
{ return protocolId; }
template<class T > template double BasePhyLayer::readPar< double > (const char * parName, const T defaultValue) const [protected]
Reads and returns the parameter with the passed name.
If the parameter couldn't be found the value of defaultValue is returned.
Parameters:
parName - the name of the ned-parameter
defaultValue - the value to be returned if the parameter couldn't be found
Referenced by PhyLayerUWBIR::initializeRadio(), and initializeRadio().
{
  if(hasPar(parName))
    return par(parName);
  return defaultValue;
}
void BasePhyLayer::recordScalar (const char * name, double value, const char * unit = NULL) [virtual]
Records a double into the scalar result file.
Implements the method from DeciderToPhyInterface, method-calls are forwarded to OMNeT-method 'recordScalar'.
Implements DeciderToPhyInterface.
{
  ConnectionManagerAccess::recordScalar(name, value, unit);
}
void BasePhyLayer::rescheduleMessage (cMessage * msg, simtime_t_cref t) [virtual]
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
Used by the Decider if it has to handle an AirFrame or an control message earlier than it has returned to the PhyLayer the last time the Decider handled that message.
Implements DeciderToPhyInterface.
References cancelScheduledMessage().
{
  cancelScheduledMessage(msg);
  scheduleAt(t, msg);
}
void BasePhyLayer::sendControlMsgToMac (cMessage * msg) [virtual]
Called by the Decider to send a control message to the MACLayer.
This function can be used to answer a ChannelSenseRequest to the MACLayer
Implements DeciderToPhyInterface.
References MacToPhyInterface::CHANNEL_SENSE_REQUEST, channelInfo, ChannelInfo::isRecording(), sendControlMessageUp(), and ChannelInfo::stopRecording().
Referenced by finishRadioSwitching(), and handleSelfMessage().
{
  if(msg->getKind() == CHANNEL_SENSE_REQUEST) {
    if(channelInfo.isRecording()) {
      channelInfo.stopRecording();
    }
  }
  sendControlMessageUp(msg);
}
void BasePhyLayer::sendUp (airframe_ptr_t packet, DeciderResult * result) [virtual]
Called to send an AirFrame with DeciderResult to the MACLayer.
When a packet is completely received and not noise, the Decider call this function to send the packet together with the corresponding DeciderResult up to MACLayer
Implements DeciderToPhyInterface.
References sendMacPktUp(), and setUpControlInfo().
{
  coreEV << "Decapsulating MacPacket from Airframe with ID " << frame->getId() << " and sending it up to MAC." << endl;
  cMessage* packet = frame->decapsulate();
  assert(packet);
  setUpControlInfo(packet, result);
  sendMacPktUp(packet);
}
simtime_t BasePhyLayer::setRadioState (int rs) [virtual]
Tells the BasePhyLayer to switch to the specified radio state.
The switching process can take some time depending on the specified switching times in the ned file.
Returns:
Decider::notAgain: Error code if the Radio is currently switching else: switching time from the current RadioState to the new RadioState
Implements MacToPhyInterface.
Reimplemented in PhyLayerUWBIR, and PhyLayerBattery.
References finishRadioSwitching(), radio, radioSwitchingOverTimer, sendSelfMessage(), MiximRadio::switchTo(), and txOverTimer.
{
  Enter_Method_Silent();
  assert(radio);
  if(txOverTimer && txOverTimer->isScheduled()) {
    opp_warning("Switched radio while sending an AirFrame. The effects this would have on the transmission are not simulated by the BasePhyLayer!");
  }
  simtime_t switchTime = radio->switchTo(rs, simTime());
  //invalid switch time, we are probably already switching
  if(switchTime < SIMTIME_ZERO)
    return switchTime;
  // if switching is done in exactly zero-time no extra self-message is scheduled
  if (switchTime == SIMTIME_ZERO) {
    // In case of zero-time-switch, send no control-message to MAC!
    finishRadioSwitching(false);
  }
  else {
    sendSelfMessage(radioSwitchingOverTimer, simTime() + switchTime);
  }
  return switchTime;
}
cObject * BasePhyLayer::setUpControlInfo (cMessage *const pMsg, DeciderResult *const pDeciderResult) [virtual]
Attaches a "control info" (PhyToMac) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the decider result.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters:
pMsg The message where the "control info" shall be attached.
pSrcAddr The MAC address of the message receiver.
References PhyToMacControlInfo::setControlInfo().
Referenced by sendUp().
{
  return PhyToMacControlInfo::setControlInfo(pMsg, pDeciderResult);
}
Member Data Documentation
short BasePhyLayer::airFramePriority = 10 [static, protected]
Defines the scheduling priority of AirFrames.
AirFrames use a slightly higher priority than normal to ensure channel consistency. This means that before anything else happens at a time point t every AirFrame which ended at t has been removed and every AirFrame started at t has been added to the channel.
An example where this matters is a ChannelSenseRequest which ends at the same time as an AirFrame starts (or ends). Depending on which message is handled first the result of ChannelSenseRequest would differ.
Referenced by PhyLayerUWBIR::encapsMsg(), and encapsMsg().
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/BasePhyLayer.h
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/BasePhyLayer.cc