MiXiM: BaseConnectionManager Class Reference
BaseConnectionManager Class Reference
connectionManager - channel and connection related classes
Module to control the channel and handle all connection related stuff.
#include <BaseConnectionManager.h>
Classes
class CoordSet
Represents an minimalistic (hash)set of GridCoords.
class GridCoord
Represents a position inside a grid.
Public Member Functions
virtual int numInitStages () const
Needs two initialization stages.
virtual void initialize (int stage)
Reads init parameters and calculates a maximal interference distance.
bool registerNic (cModule *nic, ConnectionManagerAccess *chAccess, const Coord *nicPos)
Registers a nic to have its connections managed by ConnectionManager.
bool unregisterNic (cModule *nic)
Unregisters a NIC such that its connections aren't managed by the CM anymore.
void updateNicPos (NicEntry::t_nicid_cref nicID, const Coord *newPos)
Updates the position information of a registered nic.
const NicEntry::GateList & getGateList (NicEntry::t_nicid_cref nicID) const
Returns the ingates of all nics in range.
const cGate * getOutGateTo (const NicEntry *nic, const NicEntry *targetNic) const
Returns the ingate of the with id==targetID, or 0 if not in range.
Protected Types
typedef std::map
< NicEntry::t_nicid, NicEntry * > NicEntries
Type for map from nic-module id to nic-module pointer.
typedef std::vector< NicEntries > RowVector
Type for 1-dimensional array of NicEntries.
typedef std::vector< RowVector > NicMatrix
Type for 2-dimensional array of NicEntries.
typedef std::vector< NicMatrix > NicCube
Type for 3-dimensional array of NicEntries.
Protected Member Functions
virtual double calcInterfDist ()=0
Calculate interference distance.
virtual void registerNicExt (NicEntry::t_nicid_cref nicID)
Called by "registerNic()" after the nic has been unregistered. That means that the NicEntry for the nic has already been disconnected and removed from nic map.
virtual void unregisterNicExt (NicEntry::t_nicid_cref nicID)
Called by "unregisterNic()" after the nic has been registered. That means that the NicEntry for the nic has already been created and added to nics map.
virtual void updateConnections (NicEntry::t_nicid_cref nicID, const Coord *oldPos, const Coord *newPos)
Updates the connections of the nic with "nicID".
virtual bool isInRange (NicEntries::mapped_type pFromNic, NicEntries::mapped_type pToNic)
Check if the two nic's are in range.
Protected Attributes
NicEntries nics
Map from nic-module ids to nic-module pointers.
bool coreDebug
Set debugging for the basic module.
bool sendDirect
Does the ConnectionManager use sendDirect or not?
const Coord * playgroundSize
Stores the size of the playground.
double maxInterferenceDistance
the biggest interference distance in the network.
double maxDistSquared
Square of maxInterferenceDistance cache a value that is often used.
bool useTorus
Stores the useTorus flag of the WorldUtility.
bool drawMIR
Stores if maximum interference distance should be displayed in TkEnv.
NicCube nicGrid
Register of all nics.
Coord findDistance
Distance that helps to find a node under a certain position.
GridCoord gridDim
The size of the grid.
Private Member Functions
void updateNicConnections (NicEntries &nmap, NicEntries::mapped_type nic)
Manages the connections of a registered nic.
void checkGrid (GridCoord &oldCell, GridCoord &newCell, NicEntry::t_nicid_cref id)
Check connections of a nic in the grid.
GridCoord getCellForCoordinate (const Coord &c) const
Calculates the corresponding cell of a coordinate.
NicEntries & getCellEntries (const GridCoord &cell)
Returns the NicEntries of the cell with specified coordinate.
int wrapIfTorus (int value, int max) const
void fillUnionWithNeighbors (CoordSet &gridUnion, const GridCoord &cell) const
Adds every direct Neighbor of a GridCoord to a union of coords.
BaseConnectionManager (const BaseConnectionManager &)
Copy constructor is not allowed.
BaseConnectionManager & operator= (const BaseConnectionManager &)
Assignment operator is not allowed.
Detailed Description
Module to control the channel and handle all connection related stuff.
The central module that coordinates the connections between all nodes, and handles dynamic gate creation. BaseConnectionManager therefore periodically communicates with the ConnectionManagerAccess modules
You may not instantiate BaseConnectionManager! Use ConnectionManager instead.
Author:
Steffen Sroka, Daniel Willkomm, Karl Wessel
Christoph Sommer ("unregisterNic()"-method)
See also:
ConnectionManagerAccess
Member Function Documentation
virtual double BaseConnectionManager::calcInterfDist () [protected, pure virtual]
Calculate interference distance.
Called by BaseConnectionManager already during initialization stage 0. Implementations therefore have to make sure that everything necessary for calculation is either already initialized or has to be initialized in this method!
This method has to be overridden by any derived class.
Implemented in UnitDisk, and ConnectionManager.
Referenced by initialize().
bool BaseConnectionManager::isInRange (NicEntries::mapped_type pFromNic, NicEntries::mapped_type pToNic) [protected, virtual]
Check if the two nic's are in range.
This function will be used to decide if two nic's shall be connected or not. It is simple to overload this function to enhance the decision for connection or not.
Parameters:
pFromNic Nic source point which should be checked.
pToNic Nic target point which should be checked.
Returns:
true if the nic's are in range and can be connected, false if not.
References maxDistSquared, playgroundSize, and useTorus.
Referenced by updateNicConnections().
{
  double dDistance = 0.0;
    if(useTorus) {
      dDistance = pFromNic->pos.sqrTorusDist(pToNic->pos, *playgroundSize);
    } else {
      dDistance = pFromNic->pos.sqrdist(pToNic->pos);
    }
    return (dDistance <= maxDistSquared);
}
bool BaseConnectionManager::registerNic (cModule * nic, ConnectionManagerAccess * chAccess, const Coord * nicPos)
Registers a nic to have its connections managed by ConnectionManager.
If you want to do your own stuff at the registration of a nic see "registerNicExt()".
References coreDebug, drawMIR, maxInterferenceDistance, nics, registerNicExt(), sendDirect, and updateConnections().
Referenced by ConnectionManagerAccess::receiveSignal().
{
  assert(nic != NULL);
  const NicEntry::t_nicid nicID = nic->getId();
  ccEV << " registering nic #" << nicID << endl;
  // create new NicEntry
  NicEntries::mapped_type nicEntry;
  cModule *const          pHostModule = FindModule<>::findHost(nic);
  if(sendDirect)
    nicEntry = new NicEntryDirect(coreDebug);
  else
    nicEntry = new NicEntryDebug(coreDebug);
  // fill nicEntry
  nicEntry->nicPtr = nic;
  nicEntry->nicId = nicID;
  nicEntry->hostId   = pHostModule ? pHostModule->getId() : 0;
  nicEntry->pos      = *nicPos;
  nicEntry->chAccess = chAccess;
  // add to map
  nics[nicID] = nicEntry;
  registerNicExt(nicID);
  updateConnections(nicID, nicPos, nicPos);
  if(drawMIR && pHostModule) {
    cDisplayString& Displ = pHostModule->getDisplayString();
    if (!Displ.containsTag("r"))
      Displ.setTagArg("r", 0, maxInterferenceDistance);
  }
  return sendDirect;
}
void BaseConnectionManager::registerNicExt (NicEntry::t_nicid_cref nicID) [protected, virtual]
Called by "registerNic()" after the nic has been unregistered. That means that the NicEntry for the nic has already been disconnected and removed from nic map.
You better know what you are doing if you want to override this method. Most time you won't need to.
See BaseConnectionManager::registerNicExt() for an example.
Parameters:
nicID - the id of the NicEntry
References getCellEntries(), getCellForCoordinate(), BaseConnectionManager::GridCoord::info(), and nics.
Referenced by registerNic().
{
  NicEntries::mapped_type nicEntry = nics[nicID];
  GridCoord cell = getCellForCoordinate(nicEntry->pos);
  ccEV <<" registering (ext) nic at loc " << cell.info() << std::endl;
  // add to matrix
  NicEntries& cellEntries = getCellEntries(cell);
    cellEntries[nicID] = nicEntry;
}
bool BaseConnectionManager::unregisterNic (cModule * nic)
Unregisters a NIC such that its connections aren't managed by the CM anymore.
NOTE: This method asserts that the passed NIC module was previously registered with this ConnectionManager!
This method should be used for dynamic networks were hosts can actually disappear.
Parameters:
nic the NIC module to be unregistered
Returns:
returns true if the NIC was unregistered successfully
References BaseConnectionManager::CoordSet::add(), fillUnionWithNeighbors(), getCellEntries(), getCellForCoordinate(), gridDim, BaseConnectionManager::GridCoord::info(), BaseConnectionManager::CoordSet::next(), nics, and unregisterNicExt().
{
  assert(nicModule != 0);
  // find nicEntry
  const NicEntry::t_nicid nicID      = nicModule->getId();
  NicEntries::iterator    nicEntryIt = nics.find(nicID);
  ccEV << " unregistering nic #" << nicID << endl;
  if (nicEntryIt == nics.end()) {
    assert(false);
    return false;
  }
  NicEntries::mapped_type nicEntry = nicEntryIt->second;
  // get all affected grid squares
  CoordSet gridUnion(74);
  GridCoord cell = getCellForCoordinate(nicEntry->pos);
  if((gridDim.x == 1) && (gridDim.y == 1) && (gridDim.z == 1)) {
    gridUnion.add(cell);
  } else {
    fillUnionWithNeighbors(gridUnion, cell);
  }
  // disconnect from all NICs in these grid squares
  GridCoord* c = gridUnion.next();
  while(c != 0) {
    ccEV << "Update cons in [" << c->info() << "]" << endl;
    NicEntries& nmap = getCellEntries(*c);
    for(NicEntries::iterator i = nmap.begin(); i != nmap.end(); ++i) {
      NicEntries::mapped_type other = i->second;
      if (other == nicEntry)
        continue;
      if (other->isConnected(nicEntry)) {
        other->disconnectFrom(nicEntry);
      }
      if (nicEntry->isConnected(other)) {
        nicEntry->disconnectFrom(other);
      }
    }
    c = gridUnion.next();
  }
  // erase from grid
  NicEntries& cellEntries = getCellEntries(cell);
  cellEntries.erase(nicID);
  unregisterNicExt(nicID);
  // erase from list of known nics
  nics.erase(nicEntryIt);
  delete nicEntry;
  return true;
}
void BaseConnectionManager::unregisterNicExt (NicEntry::t_nicid_cref nicID) [protected, virtual]
Called by "unregisterNic()" after the nic has been registered. That means that the NicEntry for the nic has already been created and added to nics map.
You better know what you are doing if you want to override this method. Most time you won't need to.
See BaseConnectionManager::unregisterNicExt() for an example.
Parameters:
nicID - the id of the NicEntry
Referenced by unregisterNic().
{
  (void)nicID;
}
void BaseConnectionManager::updateConnections (NicEntry::t_nicid_cref nicID, const Coord * oldPos, const Coord * newPos) [protected, virtual]
Updates the connections of the nic with "nicID".
This method is called by "updateNicPos()" after the new Position is stored in the corresponding nic.
Most time you won't need to override this method.
Parameters:
nicID the id of the NicEntry
oldPos the old position of the nic
newPos the new position of the nic
References checkGrid(), and getCellForCoordinate().
Referenced by registerNic(), and updateNicPos().
{
  GridCoord oldCell = getCellForCoordinate(*oldPos);
    GridCoord newCell = getCellForCoordinate(*newPos);
  checkGrid(oldCell, newCell, nicID );
}
int BaseConnectionManager::wrapIfTorus (int value, int max) const [private]
If the value is outside of its bounds (zero and max) this function returns -1 if useTorus is false and the wrapped value if useTorus is true. Otherwise its just returns the value unchanged.
References useTorus.
Referenced by fillUnionWithNeighbors().
{
  if(value < 0) {
    if(useTorus) {
      return max + value;
    } else {
      return -1;
    }
  } else if(value >= max) {
    if(useTorus) {
      return value - max;
    } else {
      return -1;
    }
  } else {
    return value;
  }
}
Member Data Documentation
Coord BaseConnectionManager::findDistance [protected]
Distance that helps to find a node under a certain position.
Can be larger then
See also:
maxInterferenceDistance to allow nodes to be placed into the same square if the playground is too small for the grid speedup to work.
Referenced by initialize().
NicCube BaseConnectionManager::nicGrid [protected]
Register of all nics.
This matrix keeps all nics according to their position. It allows to restrict the position update to a subset of all nics.
Referenced by initialize().
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/base/connectionManager/BaseConnectionManager.h
D:/Projects/MiXiM/extsrc/mixim/src/base/connectionManager/BaseConnectionManager.cc