MiXiM: ConstantSimpleConstMapping Class Reference
ConstantSimpleConstMapping Class Reference
mapping - classes representing mathematical mappings
Represents a constant mathematical mapping (f(x) = c)
#include <MappingUtils.h>
Public Member Functions
ConstantSimpleConstMapping (const DimensionSet &dims, argument_value_cref_t val)
ConstantSimpleConstMapping (const DimensionSet &dims, const Argument &key, argument_value_cref_t val)
ConstantSimpleConstMapping (const ConstantSimpleConstMapping &o)
virtual argument_value_t getValue (const Argument &) const
Returns the value of the mapping at the passed position.
argument_value_cref_t getValue () const
Returns the value of this constant mapping.
void setValue (argument_value_cref_t val)
Sets the value of this constant mapping.
ConstMapping * constClone () const
creates a clone of this mapping.
Protected Attributes
argument_value_t value
Detailed Description
Represents a constant mathematical mapping (f(x) = c)
Returns the same value for every point in any dimension.
Author:
Karl Wessel
Member Function Documentation
ConstMapping* ConstantSimpleConstMapping::constClone () const [inline, virtual]
creates a clone of this mapping.
This method has to be implemented by every subclass.
Implements SimpleConstMapping.
{
    return new ConstantSimpleConstMapping(dimensions, value);
  }
virtual argument_value_t ConstantSimpleConstMapping::getValue (const Argument & pos) const [inline, virtual]
Returns the value of the mapping at the passed position.
This method has to be implemented by every subclass and should only have constant complexity.
Implements SimpleConstMapping.
Referenced by MultiDimMapping< Linear >::createSubSignal(), MultiDimMapping< Linear >::MultiDimMapping(), and MultiDimMapping< Linear >::operator=().
{
    return value;
  }
The documentation for this class was generated from the following file:
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/MappingUtils.h