MiXiM: BaseNetwLayer Class Reference
BaseNetwLayer Class Reference
netwLayer - network layer modules | baseModules - base module classes of MiXiM
Base class for the network layer.
#include <BaseNetwLayer.h>
Public Types
enum BaseNetwMessageKinds { LAST_BASE_NETW_MESSAGE_KIND = 24000 }
Message kinds used by this layer.
enum BaseNetwControlKinds { LAST_BASE_NETW_CONTROL_KIND = 24500 }
Control message kinds used by this layer.
typedef NetwPkt * netwpkt_ptr_t
network packet pointer type.
Public Member Functions
BaseNetwLayer (unsigned stacksize)
virtual void initialize (int)
Initialization of the module and some variables.
Protected Member Functions
virtual cMessage * decapsMsg (netwpkt_ptr_t)
decapsulate higher layer message from NetwPkt
virtual netwpkt_ptr_t encapsMsg (cPacket *)
Encapsulate higher layer packet into an NetwPkt.
virtual cObject * setDownControlInfo (cMessage *const pMsg, const LAddress::L2Type &pDestAddr)
Attaches a "control info" (NetwToMac) structure (object) to the message pMsg.
virtual cObject * setUpControlInfo (cMessage *const pMsg, const LAddress::L3Type &pSrcAddr)
Attaches a "control info" (NetwToUpper) structure (object) to the message pMsg.
Handle Messages
Functions to redefine by the programmer
These are the functions provided to add own functionality to your modules. These functions are called whenever a self message or a data message from the upper or lower layer arrives respectively.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleLowerMsg (cMessage *msg)
Handle messages from lower layer.
virtual void handleSelfMsg (cMessage *)
Handle self messages.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *)
Handle control messages from lower layer.
Protected Attributes
int headerLength
Length of the NetwPkt header Read from omnetpp.ini.
ArpInterface * arp
Pointer to the arp module.
LAddress::L3Type myNetwAddr
cached variable of my networ address
bool coreDebug
Enables debugging of this module.
Private Member Functions
BaseNetwLayer (const BaseNetwLayer &)
Copy constructor is not allowed.
BaseNetwLayer & operator= (const BaseNetwLayer &)
Assignment operator is not allowed.
Detailed Description
Base class for the network layer.
Author:
Daniel Willkomm
Member Enumeration Documentation
enum BaseNetwLayer::BaseNetwControlKinds
Control message kinds used by this layer.
Enumerator:
LAST_BASE_NETW_CONTROL_KIND
Stores the id on which classes extending BaseNetw should continue their own control kinds.
{
    LAST_BASE_NETW_CONTROL_KIND = 24500,
  };
enum BaseNetwLayer::BaseNetwMessageKinds
Message kinds used by this layer.
Enumerator:
LAST_BASE_NETW_MESSAGE_KIND
Stores the id on which classes extending BaseNetw should continue their own message kinds.
{
    LAST_BASE_NETW_MESSAGE_KIND = 24000,
  };
Member Function Documentation
cMessage * BaseNetwLayer::decapsMsg (netwpkt_ptr_t msg) [protected, virtual]
decapsulate higher layer message from NetwPkt
Decapsulates the packet from the received Network packet
Reimplemented in ProbabilisticBroadcast, and DummyRoute.
References setUpControlInfo().
Referenced by handleLowerMsg(), and Flood::handleLowerMsg().
{
    cMessage *m = msg->decapsulate();
    setUpControlInfo(m, msg->getSrcAddr());
    // delete the netw packet
    delete msg;
    return m;
}
BaseNetwLayer::netwpkt_ptr_t BaseNetwLayer::encapsMsg (cPacket * appPkt) [protected, virtual]
Encapsulate higher layer packet into an NetwPkt.
Encapsulates the received ApplPkt into a NetwPkt and set all needed header fields.
Reimplemented in Flood, ProbabilisticBroadcast, and DummyRoute.
References arp, NetwControlInfo::getAddressFromControlInfo(), ArpInterface::getMacAddr(), headerLength, LAddress::isL3Broadcast(), LAddress::L2BROADCAST, LAddress::L3BROADCAST, myNetwAddr, and setDownControlInfo().
Referenced by handleUpperMsg().
{
    LAddress::L2Type macAddr;
    LAddress::L3Type netwAddr;
    coreEV <<"in encaps...\n";
    netwpkt_ptr_t pkt = new NetwPkt(appPkt->getName(), appPkt->getKind());
    pkt->setBitLength(headerLength);
    cObject* cInfo = appPkt->removeControlInfo();
    if(cInfo == NULL){
  EV << "warning: Application layer did not specifiy a destination L3 address\n"
     << "\tusing broadcast address instead\n";
  netwAddr = LAddress::L3BROADCAST;
    } else {
  coreEV <<"CInfo removed, netw addr="<< NetwControlInfo::getAddressFromControlInfo( cInfo ) << std::endl;
        netwAddr = NetwControlInfo::getAddressFromControlInfo( cInfo );
  delete cInfo;
    }
    pkt->setSrcAddr(myNetwAddr);
    pkt->setDestAddr(netwAddr);
    coreEV << " netw "<< myNetwAddr << " sending packet" <<std::endl;
    if(LAddress::isL3Broadcast( netwAddr )) {
        coreEV << "sendDown: nHop=L3BROADCAST -> message has to be broadcasted"
           << " -> set destMac=L2BROADCAST\n";
        macAddr = LAddress::L2BROADCAST;
    }
    else{
        coreEV <<"sendDown: get the MAC address\n";
        macAddr = arp->getMacAddr(netwAddr);
    }
    setDownControlInfo(pkt, macAddr);
    //encapsulate the application packet
    pkt->encapsulate(appPkt);
    coreEV <<" pkt encapsulated\n";
    return pkt;
}
void BaseNetwLayer::handleLowerControl (cMessage * msg) [protected, virtual]
Handle control messages from lower layer.
Redefine this function if you want to process control messages from lower layers.
This function currently handles one messagetype: TRANSMISSION_OVER. If such a message is received in the network layer it is deleted. This is done as this type of messages is passed on by the BaseMacLayer.
It may be used by network protocols to determine when the lower layers are finished sending a message.
Implements BaseLayer.
Reimplemented in WiseRoute, ProbabilisticBroadcast, and DummyRoute.
References BaseMacLayer::TX_OVER.
{
  switch (msg->getKind())
  {
  case BaseMacLayer::TX_OVER:
    delete msg;
    break;
  default:
    EV << "BaseNetwLayer does not handle control messages called "
       << msg->getName() << std::endl;
    delete msg;
    break;
  }
}
void BaseNetwLayer::handleLowerMsg (cMessage * msg) [protected, virtual]
Handle messages from lower layer.
Redefine this function if you want to process messages from lower layers before they are forwarded to upper layers
If you want to forward the message to upper layers please use sendUp which will take care of decapsulation and thelike
Implements BaseLayer.
Reimplemented in WiseRoute, Flood, ProbabilisticBroadcast, DummyRoute, and AdaptiveProbabilisticBroadcast.
References decapsMsg(), and BaseLayer::sendUp().
{
    netwpkt_ptr_t m = static_cast<netwpkt_ptr_t>(msg);
    coreEV << " handling packet from " << m->getSrcAddr() << std::endl;
    sendUp(decapsMsg(m));
}
void BaseNetwLayer::handleUpperMsg (cMessage * msg) [protected, virtual]
Handle messages from upper layer.
Redefine this function if you want to process messages from upper layers before they are send to lower layers.
For the BaseNetwLayer we just use the destAddr of the network message as a nextHop
To forward the message to lower layers after processing it please use sendDown. It will take care of anything needed
Implements BaseLayer.
Reimplemented in WiseRoute, Flood, ProbabilisticBroadcast, and DummyRoute.
References encapsMsg(), and BaseLayer::sendDown().
{
  assert(dynamic_cast<cPacket*>(msg));
    sendDown(encapsMsg(static_cast<cPacket*>(msg)));
}
cObject * BaseNetwLayer::setDownControlInfo (cMessage *const pMsg, const LAddress::L2Type & pDestAddr) [protected, virtual]
Attaches a "control info" (NetwToMac) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the destination MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters:
pMsg The message where the "control info" shall be attached.
pDestAddr The MAC address of the message receiver.
Attaches a "control info" structure (object) to the down message pMsg.
References NetwToMacControlInfo::setControlInfo().
Referenced by DummyRoute::encapsMsg(), ProbabilisticBroadcast::encapsMsg(), Flood::encapsMsg(), encapsMsg(), ProbabilisticBroadcast::handleLowerMsg(), Flood::handleLowerMsg(), WiseRoute::handleLowerMsg(), ProbabilisticBroadcast::handleSelfMsg(), WiseRoute::handleSelfMsg(), and WiseRoute::handleUpperMsg().
{
  return NetwToMacControlInfo::setControlInfo(pMsg, pDestAddr);
}
cObject * BaseNetwLayer::setUpControlInfo (cMessage *const pMsg, const LAddress::L3Type & pSrcAddr) [protected, virtual]
Attaches a "control info" (NetwToUpper) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the destination MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters:
pMsg The message where the "control info" shall be attached.
pSrcAddr The MAC address of the message receiver.
Attaches a "control info" structure (object) to the up message pMsg.
References NetwControlInfo::setControlInfo().
Referenced by DummyRoute::decapsMsg(), decapsMsg(), and WiseRoute::decapsMsg().
{
  return NetwControlInfo::setControlInfo(pMsg, pSrcAddr);
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/base/modules/BaseNetwLayer.h
D:/Projects/MiXiM/extsrc/mixim/src/base/modules/BaseNetwLayer.cc