MiXiM: BaseDecider Class Reference
BaseDecider Class Reference
decider - decider modules | baseModules - base module classes of MiXiM
Provides some base functionality for most common deciders.
#include <BaseDecider.h>
Classes
struct tCSRInfo
Data about an currently ongoing ChannelSenseRequest.
struct tProcessingSignal
Pair of a AirFrame and the state it is in.
Public Types
enum BaseDeciderControlKinds { PACKET_DROPPED = 22100, LAST_BASE_DECIDER_CONTROL_KIND }
The kinds of ControlMessages this Decider sends.
Public Member Functions
BaseDecider (DeciderToPhyInterface *phy, double sensitivity, int myIndex, bool debug)
Initializes the decider with the passed values.
virtual simtime_t processSignal (airframe_ptr_t frame)
Processes an AirFrame given by the PhyLayer.
virtual void cancelProcessSignal ()
Cancels processing a AirFrame.
virtual ChannelState getChannelState () const
A function that returns information about the channel state.
virtual simtime_t handleChannelSenseRequest (ChannelSenseRequest *request)
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
virtual void channelChanged (int newChannel)
Called by phy layer to indicate that the channel this radio currently listens to has changed.
virtual void finish ()
Method to be called by an OMNeT-module during its own finish(), to enable a decider to do some things.
Protected Types
enum eSignalState { NEW, EXPECT_HEADER, EXPECT_END }
The current state of processing for a signal.
typedef struct
BaseDecider::tProcessingSignal ReceivedSignal
Pair of a AirFrame and the state it is in.
typedef struct
BaseDecider::tCSRInfo CSRInfo
Data about an currently ongoing ChannelSenseRequest.
typedef std::pair< double,
simtime_t > channel_sense_rssi_t
Return type of BaseDecider::calcChannelSenseRSSI function.
typedef std::pair< Mapping
*, channel_sense_rssi_t::second_type > rssi_mapping_t
Return type of BaseDecider::calculateRSSIMapping function.
Protected Member Functions
virtual double getFrameReceivingPower (airframe_ptr_t frame) const
Calculates the receive power of given frame.
virtual eSignalState getNextSignalState (eSignalState CurState) const
Returns the next signal state (END, HEADER, NEW).
virtual simtime_t getNextSignalHandleTime (const airframe_ptr_t frame) const
Returns the next handle time for scheduler.
virtual simtime_t processNewSignal (airframe_ptr_t frame)
Processes a new Signal. Returns the time it wants to handle the signal again.
virtual simtime_t processSignalHeader (airframe_ptr_t)
Processes the end of the header of a received Signal.
virtual DeciderResult * createResult (const airframe_ptr_t frame) const
Creates the DeciderResult from frame.
virtual simtime_t processSignalEnd (airframe_ptr_t frame)
Processes the end of a received Signal.
virtual simtime_t processUnknownSignal (airframe_ptr_t frame)
Processes any Signal for which no state could be found. (is an error case).
virtual eSignalState getSignalState (const airframe_ptr_t frame) const
Returns the SignalState for the passed AirFrame.
virtual eSignalState setSignalState (const airframe_ptr_t frame, eSignalState newState)
virtual simtime_t handleNewSenseRequest (ChannelSenseRequest *request)
Handles a new incoming ChannelSenseRequest and returns the next (or latest) time to handle the request again.
virtual void handleSenseRequestEnd (CSRInfo &requestInfo)
Handles the timeout or end of a ChannelSenseRequest by calculating the ChannelState and returning the request to the mac layer.
virtual simtime_t canAnswerCSR (const CSRInfo &requestInfo) const
Returns point in time when the ChannelSenseRequest of the passed CSRInfo can be answered (e.g. because channel state changed or timeout is reached).
virtual channel_sense_rssi_t calcChannelSenseRSSI (simtime_t_cref start, simtime_t_cref end) const
Calculates the RSSI value for the passed interval.
virtual void answerCSR (CSRInfo &requestInfo)
Answers the ChannelSenseRequest (CSR) from the passed CSRInfo.
virtual void channelStateChanged ()
Checks if the changed channel state enables us to answer any ongoing ChannelSenseRequests.
virtual void getChannelInfo (simtime_t_cref start, simtime_t_cref end, AirFrameVector &out) const
Collects the AirFrame on the channel during the passed interval.
virtual Mapping * calculateSnrMapping (const airframe_ptr_t frame) const
Calculates a SNR-Mapping for a Signal.
virtual rssi_mapping_t calculateRSSIMapping (simtime_t_cref start, simtime_t_cref end, const airframe_ptr_t exclude=NULL) const
Calculates a RSSI-Mapping (or Noise-Strength-Mapping) for a Signal.
Protected Attributes
double sensitivity
Sensitivity value for receiving an AirFrame if it <= 0 then no sensitivity check will be done.
ReceivedSignal currentSignal
Pointer to the currently received AirFrame.
CSRInfo currentChannelSenseRequest
pointer to the currently running ChannelSenseRequest and its start-time
int myIndex
index for this Decider-instance given by Phy-Layer (mostly Host-index)
bool debug
toggles display of debugging messages
Tracked statistic values.
unsigned long nbFramesWithInterference
unsigned long nbFramesWithoutInterference
unsigned long nbFramesWithInterferencePartial
unsigned long nbFramesWithoutInterferencePartial
unsigned long nbFramesWithInterferenceDropped
unsigned long nbFramesWithoutInterferenceDropped
Detailed Description
Provides some base functionality for most common deciders.
Forwards the AirFrame from "processSignal" to "processNewSignal", "processSignalHeader" or "processSignalEnd" depending on the state for that AirFrame returned by "getSignalState".
Provides answering of ChannelSenseRequests (instantaneous and over time).
Subclasses should define when they consider the channel as idle by calling "setChannelIdleStatus" because BaseDecider uses that to answer ChannelSenseRequests.
If a subclassing Decider only tries to receive one signal at a time it can use BaseDeciders "currentSignal" member which is a pair of the signal to receive and the state for that signal. The state is then used by BaseDeciders "getSignalState" to decide to which "process***" method to forward the signal. If a subclassing Decider needs states for more than one Signal it has to store these states by itself and should probably override the "getSignalState" method.
Member Typedef Documentation
typedef std::pair<double, simtime_t> BaseDecider::channel_sense_rssi_t [protected]
Return type of BaseDecider::calcChannelSenseRSSI function.
The pair consists in first part the RSSI value and in second part the maximum reception time of all air frames in requested range.
typedef std::pair<Mapping*, channel_sense_rssi_t::second_type> BaseDecider::rssi_mapping_t [protected]
Return type of BaseDecider::calculateRSSIMapping function.
The pair consists in first part the RSSI map pointer and in second part the maximum reception time of all air frames in requested range.
Member Enumeration Documentation
enum BaseDecider::BaseDeciderControlKinds
The kinds of ControlMessages this Decider sends.
Sub-classing decider should begin their own kind enumeration at the value of "LAST_BASE_DECIDER_CONTROL_KIND".
Enumerator:
PACKET_DROPPED
The phy has recognized a bit error in the packet.
LAST_BASE_DECIDER_CONTROL_KIND
Sub-classing decider should begin their own kinds at this value.
{
    PACKET_DROPPED = 22100,
    LAST_BASE_DECIDER_CONTROL_KIND
  };
enum BaseDecider::eSignalState [protected]
The current state of processing for a signal.
Enumerator:
NEW
Signal is received the first time.
EXPECT_HEADER
Waiting for the header of the signal.
EXPECT_END
Waiting for the end of the signal.
                    {
    NEW,
    EXPECT_HEADER,
    EXPECT_END,
  };
Constructor & Destructor Documentation
BaseDecider::BaseDecider (DeciderToPhyInterface * phy, double sensitivity, int myIndex, bool debug) [inline]
Initializes the decider with the passed values.
Needs a pointer to its physical layer, the sensitivity, the index of the host and the debug flag.
    : Decider(phy)
    , nbFramesWithInterference(0)
    , nbFramesWithoutInterference(0)
    , nbFramesWithInterferencePartial(0)
    , nbFramesWithoutInterferencePartial(0)
    , nbFramesWithInterferenceDropped(0)
    , nbFramesWithoutInterferenceDropped(0)
    , sensitivity(sensitivity)
    , currentSignal(NULL, NEW)
    , currentChannelSenseRequest()
    , myIndex(myIndex)
    , debug(debug)
  {
    currentChannelSenseRequest.clear();
  }
Member Function Documentation
void BaseDecider::answerCSR (CSRInfo & requestInfo) [protected, virtual]
Answers the ChannelSenseRequest (CSR) from the passed CSRInfo.
Calculates the rssi value and the channel idle state and sends the CSR together with the result back to the mac layer.
Reimplemented in SNRThresholdDecider.
References calcChannelSenseRSSI(), currentSignal, DeciderToPhyInterface::getSimTime(), Decider::phy, and DeciderToPhyInterface::sendControlMsgToMac().
Referenced by channelStateChanged(), handleNewSenseRequest(), and handleSenseRequestEnd().
{
    simtime_t            now            = phy->getSimTime(); // maybe better requestInfo.getAnswerTime()
    channel_sense_rssi_t pairRssiMaxEnd = calcChannelSenseRSSI(requestInfo.getSenseStart(), now);
  // put the sensing-result to the request and
  // send it to the Mac-Layer as Control-message (via Interface)
  requestInfo.getRequest()->setResult( ChannelState(!currentSignal.isProcessing() && (!bUseNewSense || pairRssiMaxEnd.second <= now), pairRssiMaxEnd.first) );
    deciderEV << "answerCSR: channel_sense_rssi_t(" << pairRssiMaxEnd.first << ", " << pairRssiMaxEnd.second << ")@[" << SIMTIME_STR(requestInfo.getSenseStart()) << ", " << SIMTIME_STR(now) << "] ChannelState(" << requestInfo.getRequest()->getResult().isIdle() << ", " << requestInfo.getRequest()->getResult().getRSSI() << ")" << std::endl;
  phy->sendControlMsgToMac(requestInfo.getRequest());
  requestInfo.clear();
}
BaseDecider::channel_sense_rssi_t BaseDecider::calcChannelSenseRSSI (simtime_t_cref start, simtime_t_cref end) const [protected, virtual]
Calculates the RSSI value for the passed interval.
This method is called by BaseDecider when it answers a ChannelSenseRequest or calculates the channel state. Can be overridden by sub classing Deciders.
Default implementation returns the maximum RSSI value inside the passed interval.
Reimplemented in Decider80211.
References calculateRSSIMapping(), MappingUtils::findMax(), and Argument::MappedZero.
Referenced by answerCSR(), channelChanged(), Decider802154Narrow::createResult(), and getChannelState().
{
    rssi_mapping_t pairMapMaxEnd = calculateRSSIMapping(start, end);
  // the sensed RSSI-value is the maximum value between (and including) the interval-borders
  Mapping::argument_value_t rssi = MappingUtils::findMax(*pairMapMaxEnd.first, Argument(start), Argument(end), Argument::MappedZero /* the value if no maximum will be found */);
  delete pairMapMaxEnd.first;
  return std::make_pair(rssi, pairMapMaxEnd.second);
}
BaseDecider::rssi_mapping_t BaseDecider::calculateRSSIMapping (simtime_t_cref start, simtime_t_cref end, const airframe_ptr_t exclude = NULL) const [protected, virtual]
Calculates a RSSI-Mapping (or Noise-Strength-Mapping) for a Signal.
This method can be used to calculate a RSSI-Mapping in case the parameter exclude is omitted OR to calculate a Noise-Strength-Mapping in case the AirFrame of the received Signal is passed as parameter exclude.
Returns:
The mapping and the maximum reception end of all air frames in rang [start,end].
References MappingUtils::createMapping(), getChannelInfo(), Signal::getReceivingPower(), Signal::getReceptionEnd(), Signal::getReceptionStart(), DeciderToPhyInterface::getThermalNoise(), Argument::MappedZero, Decider::notAgain, Decider::phy, and DimensionSet::timeDomain.
Referenced by Decider80211::calcChannelSenseRSSI(), calcChannelSenseRSSI(), calculateSnrMapping(), and SNRThresholdDecider::canAnswerCSR().
{
  if(exclude) {
    deciderEV << "Creating RSSI map for range [" << SIMTIME_STR(start) << "," << SIMTIME_STR(end) << "] excluding AirFrame with id " << exclude->getId() << endl;
  }
  else {
    deciderEV << "Creating RSSI map for range [" << SIMTIME_STR(start) << "," << SIMTIME_STR(end) << "]" << endl;
  }
  AirFrameVector airFrames;
  simtime_t      MaxReceptionEnd = notAgain;
  // collect all AirFrames that intersect with [start, end]
  getChannelInfo(start, end, airFrames);
  // create an empty mapping
  Mapping* resultMap = MappingUtils::createMapping(Argument::MappedZero, DimensionSet::timeDomain);
  //add thermal noise
  ConstMapping* thermalNoise = phy->getThermalNoise(start, end);
  if(thermalNoise) {
    Mapping* tmp = resultMap;
    resultMap = MappingUtils::add(*resultMap, *thermalNoise);
    delete tmp;
  }
  // otherwise, iterate over all AirFrames (except exclude)
  // and sum up their receiving-power-mappings
  for (AirFrameVector::const_iterator it = airFrames.begin(); it != airFrames.end(); ++it) {
    // the vector should not contain pointers to 0
    assert (*it != 0);
        simtime_t ReceptionEnd = (*it)->getSignal().getReceptionEnd();
        if (ReceptionEnd > MaxReceptionEnd) {
            MaxReceptionEnd = ReceptionEnd;
        }
    // if iterator points to exclude (that includes the default-case 'exclude == 0')
    // then skip this AirFrame
    if ( *it == exclude ) {
      if (thermalNoise && exclude) {
        // suggested by David Eckhoff:
        // Instead of ignoring the want-to-receive AirFrame when
        // building up the NoiseMap i add the thermalNoise for the time and
        // frequencies of this airframe. There's probably a better way to do it but
        // i did it like this:
        const ConstMapping *const recvPowerMap = (*it)->getSignal().getReceivingPower();
        if (recvPowerMap) {
                    deciderEV << "Adding mapping of Airframe with ID " << (*it)->getId()
                              << ". Starts at "  << SIMTIME_STR((*it)->getSignal().getReceptionStart())
                              << " and ends at " << SIMTIME_STR((*it)->getSignal().getReceptionEnd()) << endl;
          Mapping* rcvPowerPlusThermalNoise = MappingUtils::add(      *recvPowerMap,             *thermalNoise );
          Mapping* resultMapTmp             = MappingUtils::subtract( *rcvPowerPlusThermalNoise, *recvPowerMap );
          Mapping* resultMapNew             = MappingUtils::add(      *resultMap,                *resultMapTmp );
          delete rcvPowerPlusThermalNoise;
          delete resultMapTmp;
          delete resultMap;
          resultMap    = resultMapNew;
          resultMapNew = NULL;
        }
      }
      continue;
    }
    // otherwise get the Signal and its receiving-power-mapping
    Signal& signal = (*it)->getSignal();
    // backup pointer to result map
    // Mapping* resultMapOld = resultMap;
    // add the Signal's receiving-power-mapping to resultMap in [start, end],
    // the operation Mapping::add returns a pointer to a new Mapping
    const ConstMapping *const recvPowerMap = signal.getReceivingPower();
    assert(recvPowerMap);
    deciderEV << "Adding mapping of Airframe with ID " << (*it)->getId()
              << ". Starts at "  << SIMTIME_STR(signal.getReceptionStart())
              << " and ends at " << SIMTIME_STR(signal.getReceptionEnd()) << endl;
    Mapping* resultMapNew = MappingUtils::add( *recvPowerMap, *resultMap, Argument::MappedZero );
    // discard old mapping
    delete resultMap;
    resultMap    = resultMapNew;
    resultMapNew = NULL;
  }
  return std::make_pair(resultMap, MaxReceptionEnd);
}
Mapping * BaseDecider::calculateSnrMapping (const airframe_ptr_t frame) const [protected, virtual]
Calculates a SNR-Mapping for a Signal.
A Noise-Strength-Mapping is calculated (by using the "calculateRSSIMapping()"-method) for the time-interval of the Signal and the Signal-Strength-Mapping is divided by the Noise-Strength-Mapping.
Note: 'divided' means here the special element-wise operation on mappings.
References calculateRSSIMapping(), Signal::getReceivingPower(), Signal::getReceptionEnd(), Signal::getReceptionStart(), and Argument::MappedZero.
Referenced by SNRThresholdDecider::createResult(), Decider802154Narrow::createResult(), and Decider80211::createResult().
{
  /* calculate Noise-Strength-Mapping */
  const Signal& signal = frame->getSignal();
  simtime_t     start = signal.getReceptionStart();
  simtime_t     end   = signal.getReceptionEnd();
  Mapping*                  noiseMap     = calculateRSSIMapping(start, end, frame).first;
  const ConstMapping *const recvPowerMap = signal.getReceivingPower();
    assert(noiseMap);
  assert(recvPowerMap);
  //TODO: handle noise of zero (must not devide with zero!)
  Mapping* snrMap = MappingUtils::divide( *recvPowerMap, *noiseMap, Argument::MappedZero );
  delete noiseMap;
  noiseMap = NULL;
  return snrMap;
}
void BaseDecider::channelChanged (int newChannel) [virtual]
Called by phy layer to indicate that the channel this radio currently listens to has changed.
Sub-classing deciders which support multiple channels should override this method to handle the effects of channel changes on ongoing receptions.
Parameters:
newChannel The new channel the radio has changed to.
Reimplemented from Decider.
Reimplemented in Decider80211MultiChannel.
References BaseDecider::tProcessingSignal::busyUntilTime, calcChannelSenseRSSI(), channelStateChanged(), currentSignal, DeciderToPhyInterface::getSimTime(), and Decider::phy.
{
    currentSignal.clear();
    simtime_t            now            = phy->getSimTime();
    channel_sense_rssi_t pairRssiMaxEnd = calcChannelSenseRSSI(now, now);
    currentSignal.busyUntilTime = pairRssiMaxEnd.second;
    channelStateChanged();
}
void BaseDecider::channelStateChanged () [protected, virtual]
Checks if the changed channel state enables us to answer any ongoing ChannelSenseRequests.
This method is ment to update only an already ongoing ChannelSenseRequests it can't handle a new one.
Reimplemented in Decider80211Battery.
References answerCSR(), canAnswerCSR(), DeciderToPhyInterface::cancelScheduledMessage(), currentChannelSenseRequest, Decider::phy, and DeciderToPhyInterface::rescheduleMessage().
Referenced by channelChanged(), and processSignal().
{
  if(!currentChannelSenseRequest.getRequest())
    return;
  //check if the point in time when we can answer the request has changed
  simtime_t canAnswerAt = canAnswerCSR(currentChannelSenseRequest);
  //check if answer time has changed
  if(canAnswerAt != currentChannelSenseRequest.getAnswerTime()) {
    //can we answer it now?
    if(canAnswerAt <= phy->getSimTime()) {
      phy->cancelScheduledMessage(currentChannelSenseRequest.getRequest());
      answerCSR(currentChannelSenseRequest);
    } else {
            currentChannelSenseRequest.setAnswerTime( canAnswerAt );
      phy->rescheduleMessage( currentChannelSenseRequest.getRequest()
                            , currentChannelSenseRequest.getAnswerTime());
    }
  }
}
DeciderResult * BaseDecider::createResult (const airframe_ptr_t frame) const [protected, virtual]
Creates the DeciderResult from frame.
Parameters:
frame The processed frame.
Returns:
The result for frame.
Reimplemented in DeciderUWBIRED, Decider80211, Decider802154Narrow, SNRThresholdDecider, and Decider80211MultiChannel.
Referenced by processSignalEnd().
{
    return new DeciderResult(!frame->hasBitError());
}
void BaseDecider::getChannelInfo (simtime_t_cref start, simtime_t_cref end, AirFrameVector & out) const [protected, virtual]
Collects the AirFrame on the channel during the passed interval.
Forwards to DeciderToPhyInterfaces "getChannelInfo" method. Subclassing deciders can override this method to filter the returned AirFrames for their own criteria.
Parameters:
[in] start The start of the interval to collect AirFrames from.
[in] end The end of the interval to collect AirFrames from.
[out] out The output vector in which to put the AirFrames.
References DeciderToPhyInterface::getChannelInfo(), and Decider::phy.
Referenced by calculateRSSIMapping(), and Decider802154Narrow::createResult().
{
  phy->getChannelInfo(start, end, out);
}
ChannelState BaseDecider::getChannelState () const [virtual]
A function that returns information about the channel state.
It is an alternative for the MACLayer in order to obtain information immediately (in contrast to sending a ChannelSenseRequest, i.e. sending a cMessage over the OMNeT-control-channel)
Reimplemented from Decider.
Reimplemented in SNRThresholdDecider, and DeciderUWBIRED.
References calcChannelSenseRSSI(), currentSignal, DeciderToPhyInterface::getSimTime(), and Decider::phy.
{
  simtime_t            now            = phy->getSimTime();
  channel_sense_rssi_t pairRssiMaxEnd = calcChannelSenseRSSI(now, now);
  return ChannelState(!currentSignal.isProcessing() && (!bUseNewSense || pairRssiMaxEnd.second <= now), pairRssiMaxEnd.first);
}
double BaseDecider::getFrameReceivingPower (airframe_ptr_t frame) const [protected, virtual]
Calculates the receive power of given frame.
Default implementation use only the arrival time point for signal receive power calculation.
Reimplemented in Decider80211.
References Signal::getReceivingPower(), Signal::getReceptionStart(), and MappingUtils::post().
Referenced by processNewSignal().
{
  // get the receiving power of the Signal at start-time
  //Note: We assume the transmission power is represented by a rectangular function
  //which discontinuities (at start and end of the signal) are represented
  //by two key entries with different values very close to each other (see
  //MappingUtils "addDiscontinuity" method for details). This means
  //the transmission- and therefore also the receiving-power-mapping is still zero
  //at the exact start of the signal and not till one time step after the start its
  //at its actual transmission(/receiving) power.
  //Therefore we use MappingUtils "post"-method to ask for the receiving power
  //at the correct position.
  Signal&   signal         = frame->getSignal();
  simtime_t receivingStart = MappingUtils::post(signal.getReceptionStart());
  return signal.getReceivingPower()->getValue(Argument(receivingStart));
}
simtime_t BaseDecider::getNextSignalHandleTime (const airframe_ptr_t frame) const [protected, virtual]
Returns the next handle time for scheduler.
Parameters:
frame The current frame which is in processing.
Returns:
The next scheduler handle time.
Reimplemented in DeciderUWBIRED.
References currentSignal, EXPECT_HEADER, BaseDecider::tProcessingSignal::first, Signal::getBitrate(), DeciderToPhyInterface::getPhyHeaderLength(), Signal::getReceptionStart(), getSignalState(), ConstMapping::getValue(), NEW, Decider::notAgain, Decider::phy, and MappingUtils::pre().
Referenced by processNewSignal(), and processSignalEnd().
{
    if (frame != currentSignal.first)
        return notAgain;
    switch(getSignalState(frame)) {
        case NEW:           return notAgain; break;
        case EXPECT_HEADER: {
            // we expect the header first, so we must return the time after header is arrived
            const Signal& FrameSignal = frame->getSignal();
            double        dBitrate    = FrameSignal.getBitrate()->getValue(Argument(FrameSignal.getReceptionStart()));
            assert(dBitrate != 0.0);
            // frame->getBitLength() should store the phy-header-length (@see BasePhyLayer::encapsMsg).
            //simtime_t    tHandleTime  = FrameSignal.getReceptionStart() + (static_cast<double>(frame->getBitLength()) / dBitrate);
            simtime_t    tHandleTime  = FrameSignal.getReceptionStart() + (static_cast<double>(phy->getPhyHeaderLength()) / dBitrate);
            if (tHandleTime < frame->getSignal().getReceptionEnd())
                return tHandleTime;
            return MappingUtils::pre(frame->getSignal().getReceptionEnd());
        } break;
        default: break;
    }
    return frame->getSignal().getReceptionEnd();
}
virtual eSignalState BaseDecider::getNextSignalState (eSignalState CurState) const [inline, protected, virtual]
Returns the next signal state (END, HEADER, NEW).
Parameters:
CurState The current signal state.
Returns:
The next signal state.
Reimplemented in DeciderUWBIRED, and Decider802154Narrow.
Referenced by Decider802154Narrow::getNextSignalState(), DeciderUWBIRED::getNextSignalState(), and processNewSignal().
{
      switch(CurState) {
            case NEW:           return EXPECT_END; break;
            case EXPECT_HEADER: return EXPECT_END; break;
            default:            return NEW;        break;
      }
      return NEW;
  }
BaseDecider::eSignalState BaseDecider::getSignalState (const airframe_ptr_t frame) const [protected, virtual]
Returns the SignalState for the passed AirFrame.
The default implementation checks if the passed AirFrame is the "currentSignal" and returns its state or if not "NEW".
References currentSignal, BaseDecider::tProcessingSignal::first, NEW, and BaseDecider::tProcessingSignal::second.
Referenced by DeciderUWBIRED::getNextSignalHandleTime(), getNextSignalHandleTime(), and processSignal().
{
  if (frame == currentSignal.first)
    return currentSignal.second;
  return NEW;
}
simtime_t BaseDecider::handleChannelSenseRequest (ChannelSenseRequest * request) [virtual]
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
The MACLayer is able to send a ChannelSenseRequest to the PhyLayer that calls this function with it and is returned a time point when to re-call this function with the specific ChannelSenseRequest.
The Decider puts the result (ChannelState) to the ChannelSenseRequest and "answers" by calling the "sendControlMsg"-function on the DeciderToPhyInterface, i.e. telling the PhyLayer to send it back.
Reimplemented from Decider.
References canAnswerCSR(), currentChannelSenseRequest, DeciderToPhyInterface::getSimTime(), handleNewSenseRequest(), handleSenseRequestEnd(), Decider::notAgain, and Decider::phy.
{
  assert(request);
  if (currentChannelSenseRequest.getRequest() == NULL) {
    return handleNewSenseRequest(request);
  }
  if (currentChannelSenseRequest.getRequest() != request) {
    opp_error("Got a new ChannelSenseRequest while already handling another one!");
    return notAgain;
  }
  simtime_t now = phy->getSimTime();
  if(now >= currentChannelSenseRequest.getAnswerTime()) {
      simtime_t canAnswerAt = canAnswerCSR(currentChannelSenseRequest);
      if (canAnswerAt > now) {
          currentChannelSenseRequest.setAnswerTime( canAnswerAt );
          return currentChannelSenseRequest.getAnswerTime();
      }
  }
  handleSenseRequestEnd(currentChannelSenseRequest);
  // say that we don't want to have it again
  return notAgain;
}
void BaseDecider::handleSenseRequestEnd (CSRInfo & requestInfo) [protected, virtual]
Handles the timeout or end of a ChannelSenseRequest by calculating the ChannelState and returning the request to the mac layer.
If this handler is reached the decider has to be able to answer the request. Either because the timeout is reached or because the channel state changed accordingly.
References answerCSR().
Referenced by handleChannelSenseRequest().
{
  //assert(canAnswerCSR(requestInfo) <= phy->getSimTime());
  answerCSR(requestInfo);
}
simtime_t BaseDecider::processNewSignal (airframe_ptr_t frame) [protected, virtual]
Processes a new Signal. Returns the time it wants to handle the signal again.
Default implementation checks if the signals receiving power is above the sensitivity of the radio and we are not already trying to receive another AirFrame. If thats the case it waits for the end of the signal.
References currentSignal, getFrameReceivingPower(), getNextSignalHandleTime(), getNextSignalState(), DeciderToPhyInterface::isRadioInRX(), NEW, Decider::notAgain, Decider::phy, and sensitivity.
Referenced by processSignal().
{
  if(currentSignal.isProcessing()) {
    deciderEV << "Already receiving another AirFrame!" << endl;
    currentSignal.interferenceWith(frame);
    return notAgain;
  }
  const bool   bCheckSensitivity = sensitivity > 0.;
  const double recvPower         = bCheckSensitivity ? getFrameReceivingPower(frame) : 0.;
  // check whether signal is strong enough to receive
  if ( bCheckSensitivity && recvPower < sensitivity ) {
    deciderEV << "Signal is to weak (" << recvPower << " < " << sensitivity
        << ") -> do not receive." << endl;
    // Signal too weak, we can't receive it, tell PhyLayer that we don't want it again
    return notAgain;
  }
  else if (bCheckSensitivity && recvPower != 0) {
    // Signal is strong enough, receive this Signal and schedule it
    deciderEV << "Signal is strong enough (" << recvPower << " > " << sensitivity
        << ") -> Trying to receive AirFrame." << endl;
  }
  if (!phy->isRadioInRX()) {
        frame->setBitError(true);
        deciderEV << "AirFrame with ID " << frame->getId() << " (" << recvPower << ") received, while not receiving. Setting BitErrors to true." << endl;
  }
  currentSignal.startProcessing(frame, getNextSignalState(NEW));
  return getNextSignalHandleTime(frame);
}
simtime_t BaseDecider::processSignal (airframe_ptr_t frame) [virtual]
Processes an AirFrame given by the PhyLayer.
Returns the time point when the decider wants to be given the AirFrame again.
Reimplemented from Decider.
References channelStateChanged(), currentSignal, EXPECT_END, EXPECT_HEADER, BaseDecider::tProcessingSignal::first, DeciderToPhyInterface::getCurrentRadioChannel(), BaseDecider::tProcessingSignal::getInterferenceCnt(), DeciderToPhyInterface::getNbRadioChannels(), getSignalState(), NEW, Decider::notAgain, Decider::phy, processNewSignal(), processSignalEnd(), processSignalHeader(), and processUnknownSignal().
{
  deciderEV << "Processing AirFrame with ID " << frame->getId() << "..." << endl;
  simtime_t HandleAgain = notAgain;
    if(phy->getNbRadioChannels() > 1 && frame->getChannel() != phy->getCurrentRadioChannel()) {
        // we cannot synchronize on a frame on another channel.
        return notAgain;
    }
    bool bInteruptedProcessing = currentSignal.isProcessing();
    bool bFinishProcessing     = false;
  switch(getSignalState(frame)) {
        case NEW: {
            deciderEV << "... AirFrame processing as NewSignal..." << endl;
            HandleAgain           = processNewSignal(frame);
            bInteruptedProcessing = bInteruptedProcessing && !currentSignal.isProcessing();
        } break;
        case EXPECT_HEADER: {
            deciderEV << "... AirFrame processing as SignalHeader..." << endl;
            HandleAgain           = processSignalHeader(frame);
            bInteruptedProcessing = bInteruptedProcessing && !currentSignal.isProcessing();
        } break;
        case EXPECT_END: {
            deciderEV << "... AirFrame processing as SignalEnd..." << endl;
            bFinishProcessing     = frame == currentSignal.first;
            HandleAgain           = processSignalEnd(frame);
            bFinishProcessing     = bFinishProcessing && bInteruptedProcessing && (HandleAgain < SIMTIME_ZERO);
            bInteruptedProcessing = false;
        } break;
        default: {
            deciderEV << "... AirFrame processing as UnknownSignal..." << endl;
            bFinishProcessing     = frame == currentSignal.first;
            HandleAgain           = processUnknownSignal(frame);
            bFinishProcessing     = bFinishProcessing && bInteruptedProcessing && (HandleAgain < SIMTIME_ZERO);
            bInteruptedProcessing = false;
        } break;
  }
  if (bFinishProcessing || bInteruptedProcessing) {
      if (!bFinishProcessing && bInteruptedProcessing) {
          if (currentSignal.getInterferenceCnt() > 0) {
              ++nbFramesWithInterferencePartial;
          }
          else {
              ++nbFramesWithoutInterferencePartial;
          }
      }
      else if (bFinishProcessing) {
          if (currentSignal.isProcessing())
              currentSignal.finishProcessing();
      }
  }
  // following call is important for channel sense request
  // handling, in the past this call was done in the process...
  // methods, but it shall be called always on processSignal
  // messages
  channelStateChanged();
  return HandleAgain;
}
simtime_t BaseDecider::processSignalEnd (airframe_ptr_t frame) [protected, virtual]
Processes the end of a received Signal.
Returns the time it wants to handle the signal again (most probably notAgain).
Default implementation just decides every signal as correct and passes it to the upper layer.
References createResult(), currentSignal, BaseDecider::tProcessingSignal::first, BaseDecider::tProcessingSignal::getInterferenceCnt(), getNextSignalHandleTime(), DeciderResult::isSignalCorrect(), Decider::notAgain, PACKET_DROPPED, Decider::phy, DeciderToPhyInterface::sendControlMsgToMac(), DeciderToPhyInterface::sendUp(), and PhyToMacControlInfo::setControlInfo().
Referenced by processSignal().
{
    if (frame != currentSignal.first)
        return notAgain; // it is not the frame which we are processing
  DeciderResult* pResult = createResult(frame);
  if (pResult != NULL && pResult->isSignalCorrect() && !frame->hasBitError()) {
        deciderEV << "AirFrame was received correctly, it is now handed to upper layer..." << endl;
        // go on with processing this AirFrame, send it to the Mac-Layer
        if (currentSignal.getInterferenceCnt() > 0) {
            ++nbFramesWithInterference;
        }
        else {
            ++nbFramesWithoutInterference;
        }
        phy->sendUp(frame, pResult);
    }
  else {
        deciderEV << "AirFrame was not received correctly, sending it as control message to upper layer" << endl;
        cPacket* pMacPacket = frame->decapsulate();
        if (currentSignal.getInterferenceCnt() > 0) {
            ++nbFramesWithInterferenceDropped;
        }
        else {
            ++nbFramesWithoutInterferenceDropped;
        }
        if (pMacPacket) {
            pMacPacket->setName("ERROR");
            pMacPacket->setKind(PACKET_DROPPED);
            if (pResult) {
                PhyToMacControlInfo::setControlInfo(pMacPacket, pResult);
            }
            phy->sendControlMsgToMac(pMacPacket);
        }
    }
    currentSignal.finishProcessing();
  return getNextSignalHandleTime(frame);
}
virtual simtime_t BaseDecider::processSignalHeader (airframe_ptr_t) [inline, protected, virtual]
Processes the end of the header of a received Signal.
Returns the time it wants to handle the signal again.
Default implementation does not handle signal headers.
Reimplemented in DeciderUWBIRED, and Decider802154Narrow.
References Decider::notAgain.
Referenced by processSignal().
{
    opp_error("BaseDecider does not handle Signal headers!");
    return notAgain;
  }
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/BaseDecider.h
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/BaseDecider.cc