MiXiM: DummyRoute Class Reference
DummyRoute Class Reference
netwLayer - network layer modules
Placeholder module that simply "translates" netwControlInfo to macControlInfo.
#include <DummyRoute.h>
Public Member Functions
virtual void initialize (int)
Initialization of the module and some variables.
virtual void finish ()
Called when the simulation has finished.
Protected Member Functions
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleLowerMsg (cMessage *msg)
Handle messages from lower layer.
virtual void handleSelfMsg (cMessage *)
Handle self messages.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from lower layer.
virtual netwpkt_ptr_t encapsMsg (cPacket *appPkt)
Encapsulate higher layer packet into an NetwPkt.
virtual cPacket * decapsMsg (netwpkt_ptr_t msg)
Decapsulate a message.
Protected Attributes
bool stats
bool trace
int networkID
Detailed Description
Placeholder module that simply "translates" netwControlInfo to macControlInfo.
Author:
Jerome Rousselot
Member Function Documentation
DummyRoute::netwpkt_ptr_t DummyRoute::encapsMsg (cPacket * appPkt) [protected, virtual]
Encapsulate higher layer packet into an NetwPkt.
Encapsulates the received ApplPkt into a NetwPkt and set all needed header fields.
Reimplemented from BaseNetwLayer.
References BaseNetwLayer::arp, NetwControlInfo::getAddressFromControlInfo(), ArpInterface::getMacAddr(), BaseNetwLayer::headerLength, LAddress::isL3Broadcast(), LAddress::L2BROADCAST, LAddress::L3BROADCAST, BaseNetwLayer::myNetwAddr, and BaseNetwLayer::setDownControlInfo().
Referenced by handleUpperMsg().
{
    LAddress::L2Type macAddr;
    LAddress::L3Type netwAddr;
    debugEV <<"in encaps...\n";
    DummyRoutePkt *pkt = new DummyRoutePkt(appPkt->getName(), appPkt->getKind());
    pkt->setBitLength(headerLength);
    cObject* cInfo = appPkt->removeControlInfo();
    if(cInfo == NULL){
    EV << "warning: Application layer did not specifiy a destination L3 address\n"
     << "\tusing broadcast address instead\n";
    netwAddr = LAddress::L3BROADCAST;
    } else {
    debugEV <<"CInfo removed, netw addr="<< NetwControlInfo::getAddressFromControlInfo( cInfo ) << endl;
    netwAddr = NetwControlInfo::getAddressFromControlInfo( cInfo );
    delete cInfo;
    }
    pkt->setNetworkID(networkID);
    pkt->setSrcAddr(myNetwAddr);
    pkt->setDestAddr(netwAddr);
    debugEV << " netw "<< myNetwAddr << " sending packet" <<endl;
    if(LAddress::isL3Broadcast(netwAddr)) {
        debugEV << "sendDown: nHop=L3BROADCAST -> message has to be broadcasted"
           << " -> set destMac=L2BROADCAST\n";
        macAddr = LAddress::L2BROADCAST;
    }
    else{
        debugEV <<"sendDown: get the MAC address\n";
        macAddr = arp->getMacAddr(netwAddr);
    }
    setDownControlInfo(pkt, macAddr);
    //encapsulate the application packet
    pkt->encapsulate(appPkt);
    debugEV <<" pkt encapsulated\n";
    return pkt;
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/netw/DummyRoute.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/netw/DummyRoute.cc