MiXiM: Decider802154Narrow Class Reference
Decider802154Narrow Class Reference
decider - decider modules | IEEE 802.15.4 - Classes for the IEEE 802.15.4 implementation of MiXiM
Decider for the 802.15.4 Narrow band module.
#include <Decider802154Narrow.h>
Public Types
enum Decider802154NarrowControlKinds { RECEPTION_STARTED = LAST_BASE_DECIDER_CONTROL_KIND, LAST_DECIDER802154NARROW_CONTROL_KIND }
Public Member Functions
Decider802154Narrow (DeciderToPhyInterface *phy, double sensitivity, int myIndex, bool debug)
Standard Decider constructor.
virtual bool initFromMap (const ParameterMap &params)
Initialize the decider from XML map data.
Static Public Member Functions
static double n_choose_k (int n, int k)
Helper function to compute BER from SNR using analytical formulas.
Protected Member Functions
virtual eSignalState getNextSignalState (eSignalState CurState) const
Returns the next signal state (END, HEADER, NEW).
virtual simtime_t processSignalHeader (airframe_ptr_t frame)
Processes the end of the header of a received Signal.
virtual DeciderResult * createResult (const airframe_ptr_t frame) const
Creates the DeciderResult from frame.
double getBERFromSNR (double snr) const
bool syncOnSFD (airframe_ptr_t frame) const
double evalBER (airframe_ptr_t frame) const
Protected Attributes
int sfdLength
Start Frame Delimiter length in bits.
double BER_LOWER_BOUND
Minimum bit error rate. If SNIR is high, computed ber could be higher than maximum radio performance. This value is an upper bound to the performance.
std::string modulation
modulation type
cOutVector snirDropped
cOutVector snirReceived
cOutVector snrlog
cOutVector berlog
bool recordStats
Detailed Description
Decider for the 802.15.4 Narrow band module.
Author:
Jerome Rousselot, Amre El-Hoiydi, Marc Loebbers, Karl Wessel (port for MiXiM)
Member Function Documentation
DeciderResult * Decider802154Narrow::createResult (const airframe_ptr_t frame) const [protected, virtual]
Creates the DeciderResult from frame.
Parameters:
frame The processed frame.
Returns:
The result for frame.
Reimplemented from BaseDecider.
References berlog, BaseDecider::calcChannelSenseRSSI(), BaseDecider::calculateSnrMapping(), ConstMapping::createConstIterator(), Signal::getBitrate(), BaseDecider::getChannelInfo(), ConstMappingIterator::getNextPosition(), ConstMappingIterator::getPosition(), Signal::getReceptionEnd(), Signal::getReceptionStart(), Argument::getTime(), ConstMappingIterator::getValue(), ConstMapping::getValue(), ConstMappingIterator::hasNext(), ConstMappingIterator::next(), MappingUtils::post(), snirReceived, and snrlog.
{
  ConstMapping* snrMapping = calculateSnrMapping(frame);
  const Signal& s          = frame->getSignal();
  simtime_t     start      = s.getReceptionStart();
  simtime_t     end        = s.getReceptionEnd();
  AirFrameVector channel;
  getChannelInfo(start, end, channel);
  double bitrate  = s.getBitrate()->getValue(Argument(start));
  double avgBER   = 0;
  double bestBER  = 0.5;
  double snirAvg  = 0;
  bool   noErrors = true;
  double ber;
  double errorProbability;
  double maxErrProb = 0.0;
  simtime_t             receivingStart = MappingUtils::post(start);
  Argument              argStart(receivingStart);
  ConstMappingIterator* iter    = snrMapping->createConstIterator(argStart);
  double                snirMin = iter->getValue();
  // Evaluate bit errors for each snr value
  // and stops as soon as we have an error.
  simtime_t curTime = iter->getPosition().getTime();
  simtime_t snrDuration;
  while(curTime < end) {
    //get SNR for this interval
    double snr = iter->getValue();
    //determine end of this interval
    simtime_t nextTime = end; //either the end of the signal...
    if(iter->hasNext()) {   //or the position of the next entry
      const Argument& argNext = iter->getNextPosition();
      nextTime = std::min(argNext.getTime(), nextTime);
      iter->next(); //the iterator will already point to the next entry
    }
    if (noErrors) {
      snrDuration = nextTime - curTime;
      int nbBits = int (SIMTIME_DBL(snrDuration) * bitrate);
      // non-coherent detection of m-ary orthogonal signals in an AWGN
      // Channel
      // Digital Communications, John G. Proakis, section 4.3.2
      // p. 212, (4.3.32)
      //  Pm = sum(n=1,n=M-1){(-1)^(n+1)choose(M-1,n) 1/(n+1) exp(-nkgamma/(n+1))}
      // Pb = 2^(k-1)/(2^k - 1) Pm
      ber     = getBERFromSNR(snr);
      avgBER  = ber*nbBits;
      snirAvg = snirAvg + snr*SIMTIME_DBL(snrDuration);
            if(recordStats) {
              berlog.record(ber);
              snrlog.record(MW2DBM(snr));
            }
      if(ber < bestBER) {
        bestBER = ber;
      }
      errorProbability = 1.0 - pow((1.0 - ber), nbBits);
      noErrors         = errorProbability < uniform(0, 1);
            if(errorProbability > maxErrProb)
                maxErrProb = errorProbability;
    }
    if (snr < snirMin)
      snirMin = snr;
    curTime = nextTime;
  }
  delete iter;
  delete snrMapping;
  avgBER  = avgBER / frame->getBitLength();
  snirAvg = snirAvg / (end - start);
    if(recordStats) {
      snirReceived.record(MW2DBM(snirMin));  // in dB
    }
  return new DeciderResult802154Narrow(noErrors && !frame->hasBitError(), bitrate, snirMin, avgBER, calcChannelSenseRSSI(start, end).first, maxErrProb);
}
virtual eSignalState Decider802154Narrow::getNextSignalState (eSignalState CurState) const [inline, protected, virtual]
Returns the next signal state (END, HEADER, NEW).
Parameters:
CurState The current signal state.
Returns:
The next signal state.
Reimplemented from BaseDecider.
References BaseDecider::EXPECT_HEADER, and BaseDecider::getNextSignalState().
Referenced by processSignalHeader().
{
    switch(CurState) {
      case NEW:           return EXPECT_HEADER;                             break;
      default:            return BaseDecider::getNextSignalState(CurState); break;
    }
    return BaseDecider::getNextSignalState(CurState);
  }
bool Decider802154Narrow::initFromMap (const ParameterMap & params) [virtual]
Initialize the decider from XML map data.
This method should be defined for generic decider initialization.
Parameters:
params The parameter map which was filled by XML reader.
Returns:
true if the initialization was successfully.
Reimplemented from Decider.
References BER_LOWER_BOUND, modulation, and sfdLength.
{
    bool                         bInitSuccess = true;
    ParameterMap::const_iterator it           = params.find("sfdLength");
    if(it != params.end()) {
        sfdLength = ParameterMap::mapped_type(it->second).longValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No sfdLength defined in config.xml for Decider802154Narrow!");
    }
    it = params.find("berLowerBound");
    if(it != params.end()) {
        BER_LOWER_BOUND = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No berLowerBound defined in config.xml for Decider802154Narrow!");
    }
    it = params.find("modulation");
    if(it != params.end()) {
        modulation = ParameterMap::mapped_type(it->second).stringValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No modulation defined in config.xml for Decider802154Narrow!");
    }
    it = params.find("recordStats");
    if(it != params.end()) {
        recordStats = ParameterMap::mapped_type(it->second).boolValue();
    }
    return BaseDecider::initFromMap(params) && bInitSuccess;
}
simtime_t Decider802154Narrow::processSignalHeader (airframe_ptr_t) [protected, virtual]
Processes the end of the header of a received Signal.
Returns the time it wants to handle the signal again.
Default implementation does not handle signal headers.
Reimplemented from BaseDecider.
References BaseDecider::currentSignal, BaseDecider::EXPECT_HEADER, getNextSignalState(), Decider::notAgain, Decider::phy, and DeciderToPhyInterface::sendControlMsgToMac().
{
  if (!syncOnSFD(frame)) {
    currentSignal.finishProcessing();
    return notAgain;
  }
  // store this frame as signal to receive and set state
  setSignalState(frame, getNextSignalState(EXPECT_HEADER));
  //TODO: publish rssi and channel state
  // Inform the MAC that we started receiving a frame
  phy->sendControlMsgToMac(new cMessage("start_rx",RECEPTION_STARTED));
  return frame->getSignal().getReceptionEnd();
}
Member Data Documentation
cOutVector Decider802154Narrow::berlog [mutable, protected]
log ber value each time we enter getBERFromSNR
Referenced by createResult().
cOutVector Decider802154Narrow::snirDropped [protected]
log minimum snir values of dropped packets
cOutVector Decider802154Narrow::snirReceived [mutable, protected]
log minimum snir values of received packets
Referenced by createResult().
cOutVector Decider802154Narrow::snrlog [mutable, protected]
log snr value each time we enter getBERFromSNR
Referenced by createResult().
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/phy/Decider802154Narrow.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/phy/Decider802154Narrow.cc