MiXiM: ConnectionManagerAccess Class Reference
ConnectionManagerAccess Class Reference
connectionManager - channel and connection related classes | phyLayer - physical layer modules | baseModules - base module classes of MiXiM
Basic class for all physical layers, please don't touch!!
#include <ConnectionManagerAccess.h>
Public Member Functions
ConnectionManagerAccess (unsigned sz)
virtual void initialize (int stage)
Register with ConnectionManager.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signalling mechanism to inform of changes.
virtual ChannelMobilityPtrType getMobilityModule ()
Returns the host's mobility module.
Static Public Member Functions
static BaseConnectionManager * getConnectionManager (const cModule *nic)
Returns a pointer to the ConnectionManager responsible for the passed NIC module.
Protected Member Functions
simtime_t calculatePropagationDelay (const NicEntry *nic)
Calculates the propagation delay to the passed receiving nic.
void sendToChannel (cPacket *msg)
Sends a message to all nics connected to this one.
const cModule * getNic () const
Pointer to nic Module.
cModule * getNic ()
Protected Attributes
bool useSendDirect
use sendDirect or not?
BaseConnectionManager * cc
Pointer to the PropagationModel module.
bool coreDebug
debug this core module?
bool usePropagationDelay
Defines if the physical layer should simulate propagation delay.
bool isRegistered
Is this module already registered with ConnectionManager?
Static Protected Attributes
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
A signal used to subscribe to mobility state changes.
Private Member Functions
ConnectionManagerAccess (const ConnectionManagerAccess &)
Copy constructor is not allowed.
ConnectionManagerAccess & operator= (const ConnectionManagerAccess &)
Assignment operator is not allowed.
Detailed Description
Basic class for all physical layers, please don't touch!!
This class is not supposed to work on its own, but it contains functions and lists that cooperate with ConnectionManager to handle the dynamically created gates. This means EVERY physical layer (the lowest layer in a host) has to be derived from this class!!!!
Please don't touch this class.
Author:
Marc Loebbers
Member Function Documentation
simtime_t ConnectionManagerAccess::calculatePropagationDelay (const NicEntry * nic) [protected]
Calculates the propagation delay to the passed receiving nic.
claim the Move pattern of the sender from the Signal
References NicEntry::chAccess, Coord::distance(), getMobilityModule(), BaseWorldUtility::speedOfLight, and usePropagationDelay.
Referenced by sendToChannel().
{
  if(!usePropagationDelay)
    return 0;
  ConnectionManagerAccess *const senderModule   = this;
  ConnectionManagerAccess *const receiverModule = nic->chAccess;
  //const simtime_t_cref sStart         = simTime();
  assert(senderModule);
  assert(receiverModule);
  Coord           sendersPos  = senderModule->getMobilityModule()->getCurrentPosition(/*sStart*/);
  Coord           receiverPos = receiverModule->getMobilityModule()->getCurrentPosition(/*sStart*/);
  // this time-point is used to calculate the distance between sending and receiving host
  return receiverPos.distance(sendersPos) / BaseWorldUtility::speedOfLight;
}
BaseConnectionManager * ConnectionManagerAccess::getConnectionManager (const cModule * nic) [static]
Returns a pointer to the ConnectionManager responsible for the passed NIC module.
Parameters:
nic a pointer to a NIC module
Returns:
a pointer to a connection manager module or NULL if an error occurred
Referenced by initialize().
{
  std::string cmName = nic->hasPar("connectionManagerName")
             ? nic->par("connectionManagerName").stringValue()
             : "";
  if (cmName != "") {
    cModule* ccModule = simulation.getModuleByPath(cmName.c_str());
    return dynamic_cast<BaseConnectionManager *>(ccModule);
  }
  else {
    return FindModule<BaseConnectionManager *>::findGlobalModule();
  }
}
void ConnectionManagerAccess::initialize (int stage) [virtual]
Register with ConnectionManager.
Upon initialization ConnectionManagerAccess registers the nic parent module to have all its connections handeled by ConnectionManager
Reimplemented from BaseModule.
Reimplemented in PhyLayerUWBIR, BasePhyLayer, PhyLayerBattery, and SamplePhyLayer.
References cc, coreDebug, BaseModule::findHost(), getConnectionManager(), getNic(), simsignalwrap_t::initialize(), isRegistered, mobilityStateChangedSignal, and usePropagationDelay.
{
  MiximBatteryAccess::initialize(stage);
    if( stage == 0 ){
        hasPar("coreDebug") ? coreDebug = par("coreDebug").boolValue() : coreDebug = false;
        findHost()->subscribe(mobilityStateChangedSignal.initialize(), this);
        cc = getConnectionManager(getNic());
        if( cc == NULL ) error("Could not find ConnectionManager module");
        isRegistered = false;
    }
    usePropagationDelay = par("usePropagationDelay");
}
void ConnectionManagerAccess::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj) [virtual]
Called by the signalling mechanism to inform of changes.
ConnectionManagerAccess is subscribed to position changes and informs the ConnectionManager.
Reimplemented from BaseModule.
References cc, getNic(), isRegistered, mobilityStateChangedSignal, BaseConnectionManager::registerNic(), BaseConnectionManager::updateNicPos(), and useSendDirect.
{
    if(signalID == mobilityStateChangedSignal) {
      ChannelMobilityPtrType const mobility = check_and_cast<ChannelMobilityPtrType>(obj);
        Coord                        pos      = mobility->getCurrentPosition();
        if(isRegistered) {
            cc->updateNicPos(getNic()->getId(), &pos);
        }
        else {
            // register the nic with ConnectionManager
            // returns true, if sendDirect is used
            useSendDirect = cc->registerNic(getNic(), this, &pos);
            isRegistered  = true;
        }
    }
}
void ConnectionManagerAccess::sendToChannel (cPacket * msg) [protected]
Sends a message to all nics connected to this one.
This function has to be called whenever a packet is supposed to be sent to the channel. Don't try to figure out what gates you have and which ones are connected, this function does this for you!
depending on which ConnectionManager module is used, the messages are send via sendDirect() or to the respective gates.
References calculatePropagationDelay(), cc, BaseConnectionManager::getGateList(), getNic(), and useSendDirect.
Referenced by BasePhyLayer::sendMessageDown().
{
    const NicEntry::GateList& gateList = cc->getGateList( getNic()->getId());
    NicEntry::GateList::const_iterator i = gateList.begin();
    if(useSendDirect){
        // use Andras stuff
        if( i != gateList.end() ){
          simtime_t delay = SIMTIME_ZERO;
            for(; i != --gateList.end(); ++i){
              //calculate delay (Propagation) to this receiving nic
              delay = calculatePropagationDelay(i->first);
                int radioStart = i->second->getId();
                int radioEnd = radioStart + i->second->size();
                for (int g = radioStart; g != radioEnd; ++g)
                    sendDirect(static_cast<cPacket*>(msg->dup()),
                               delay, msg->getDuration(), i->second->getOwnerModule(), g);
            }
            //calculate delay (Propagation) to this receiving nic
      delay = calculatePropagationDelay(i->first);
            int radioStart = i->second->getId();
            int radioEnd = radioStart + i->second->size();
            for (int g = radioStart; g != --radioEnd; ++g)
                sendDirect(static_cast<cPacket*>(msg->dup()),
                           delay, msg->getDuration(), i->second->getOwnerModule(), g);
            sendDirect(msg, delay, msg->getDuration(), i->second->getOwnerModule(), radioEnd);
        }
        else{
            coreEV << "Nic is not connected to any gates!" << endl;
            delete msg;
        }
    }
    else{
        // use our stuff
        coreEV <<"sendToChannel: sending to gates\n";
        if( i != gateList.end() ){
          simtime_t delay = SIMTIME_ZERO;
            for(; i != --gateList.end(); ++i){
              //calculate delay (Propagation) to this receiving nic
        delay = calculatePropagationDelay(i->first);
                sendDelayed( static_cast<cPacket*>(msg->dup()),
                             delay, i->second );
            }
            //calculate delay (Propagation) to this receiving nic
      delay = calculatePropagationDelay(i->first);
            sendDelayed( msg, delay, i->second );
        }
        else{
            coreEV << "Nic is not connected to any gates!" << endl;
            delete msg;
        }
    }
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/base/connectionManager/ConnectionManagerAccess.h
D:/Projects/MiXiM/extsrc/mixim/src/base/connectionManager/ConnectionManagerAccess.cc