MiXiM: FWMath Class Reference
FWMath Class Reference
utils - utility classes
Support functions for mathematical operations.
#include <FWMath.h>
Static Public Member Functions
static double mod (double dividend, double divisor)
static double div (double dividend, double divisor)
static double modulo (double a, double n)
static bool close (double one, double two)
static int stepfunction (double i)
static int sign (double i)
static int round (double d)
static double floorToZero (double d)
static double max (double a, double b)
static double dBm2mW (double dBm)
static double mW2dBm (double mW)
Detailed Description
Support functions for mathematical operations.
This class contains all kind of mathematical support functions
Author:
Christian Frank
Member Function Documentation
static bool FWMath::close (double one, double two) [inline, static]
Tests whether two doubles are close enough to be declared equal. Returns true if parameters are at most epsilon apart, false otherwise
Referenced by PostureTransition::isMarkovian().
{ return fabs(one-two)<EPSILON; }
static double FWMath::dBm2mW (double dBm) [inline, static]
Converts a dBm value into milliwatts
Referenced by WiseRoute::initialize(), Mac80211::initialize(), BasePhyLayer::initialize(), and LogNormalShadowing::randomLogNormalGain().
{ return pow(10.0, dBm/10.0); }
static double FWMath::div (double dividend, double divisor) [inline, static]
Returns the result of a whole-numbered division.
{
      double i;
      modf(dividend/divisor, &i);
      return i;
  }
static double FWMath::floorToZero (double d) [inline, static]
Discards the fractional part of the parameter, e.g. -3.8 becomes -3
{ return (d >= 0.0)? floor(d) : ceil(d); }
static double FWMath::max (double a, double b) [inline, static]
Returns the greater of the given parameters
{ return (a<b)? b : a; }
static double FWMath::mod (double dividend, double divisor) [inline, static]
Returns the rest of a whole-numbered division.
{
      double i;
      return modf(dividend/divisor, &i)*divisor;
  }
static double FWMath::modulo (double a, double n) [inline, static]
Returns the remainder r on division of dividend a by divisor n, using floored division. The remainder r has the same sign as the divisor n.
{ return (a - n * floor(a/n)); }
static double FWMath::mW2dBm (double mW) [inline, static]
Convert a mW value to dBm.
{ return (10 * log10(mW)); }
static int FWMath::round (double d) [inline, static]
Returns an integer that corresponds to rounded double parameter
{ return (int)(ceil(d-0.5)); }
static int FWMath::sign (double i) [inline, static]
Returns 1 if the parameter is greater or equal to zero, -1 otherwise
{ return (i>=0)? 1 : -1; };
static int FWMath::stepfunction (double i) [inline, static]
Returns 0 if i is close to 0, 1 if i is positive and greater than epsilon, or -1 if it is negative and less than epsilon.
{ return (i>EPSILON) ? 1 : close(i, 0) ? 0 :-1; };
The documentation for this class was generated from the following file:
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/util/FWMath.h