MiXiM: SensorApplLayer Class Reference
SensorApplLayer Class Reference
applLayer - application layer modules
Test class for the application layer.
#include <SensorApplLayer.h>
Public Types
enum APPL_MSG_TYPES { SEND_DATA_TIMER, STOP_SIM_TIMER, DATA_MESSAGE }
enum TRAFFIC_TYPES {
UNKNOWN = 0, PERIODIC, UNIFORM, EXPONENTIAL,
NB_DISTRIBUTIONS
}
Public Member Functions
virtual void initialize (int)
Initialization of the module and some variables.
virtual void finish ()
Called when the simulation has finished.
Protected Member Functions
virtual void handleSelfMsg (cMessage *)
Handle self messages such as timer...
virtual void handleLowerMsg (cMessage *)
Handle messages from lower layer.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *m)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *m)
Handle control messages from upper layer.
virtual void sendData ()
send a data packet to the next hop
virtual void initializeDistribution (const char *)
Recognize distribution name. Redefine this method to add your own distribution.
virtual void scheduleNextPacket ()
calculate time to wait before sending next packet, if required. You can redefine this method in a subclass to add your own distribution.
cStdDev & hostsLatency (const LAddress::L3Type &hostAddress)
Returns the latency statistics variable for the passed host address.
Protected Attributes
cMessage * delayTimer
LAddress::L3Type myAppAddr
LAddress::L3Type destAddr
int sentPackets
simtime_t initializationTime
simtime_t firstPacketGeneration
simtime_t lastPacketReception
int trafficType
double trafficParam
int nbPackets
long nbPacketsSent
long nbPacketsReceived
bool stats
bool trace
bool debug
Debug switch for all other modules.
bool broadcastPackets
std::map< LAddress::L3Type,
cStdDev > latencies
cStdDev latency
cOutVector latenciesRaw
Packet packet
int headerLength
BaseWorldUtility * world
int dataOut
int dataIn
int ctrlOut
int ctrlIn
Private Member Functions
SensorApplLayer (const SensorApplLayer &)
Copy constructor is not allowed.
SensorApplLayer & operator= (const SensorApplLayer &)
Assignment operator is not allowed.
Detailed Description
Test class for the application layer.
All nodes periodically generate a packet addressed to a sink. This class takes three arguments:
packets: the number of packets to be sent by this application.
trafficType: affects how the time interval between two packets is generated. Possible values are "periodic", "uniform", and "exponential".
trafficParam: parameter for traffic type. For "periodic" traffic this value is the constant time interval, for "uniform" traffic this is the maximum time interval between two packets and for "exponential" it is the mean value. These values are expressed in seconds.
Author:
Amre El-Hoiydi, Jérôme Rousselot
Member Function Documentation
void SensorApplLayer::handleLowerMsg (cMessage * msg) [protected, virtual]
Handle messages from lower layer.
Handling of messages arrived to destination.
Implements BaseLayer.
References BaseLayer::catPacketSignal, and hostsLatency().
{
  ApplPkt *m;
  switch (msg->getKind()) {
  case DATA_MESSAGE:
    m = static_cast<ApplPkt *> (msg);
    nbPacketsReceived++;
    packet.setPacketSent(false);
    packet.setNbPacketsSent(0);
    packet.setNbPacketsReceived(1);
    packet.setHost(myAppAddr);
    emit(BaseLayer::catPacketSignal, &packet);
    if (stats) {
      simtime_t theLatency = m->getArrivalTime() - m->getCreationTime();
      if(trace) {
        hostsLatency(m->getSrcAddr()).collect(theLatency);
        latenciesRaw.record(SIMTIME_DBL(theLatency));
      }
      latency.collect(theLatency);
      if (firstPacketGeneration < 0)
        firstPacketGeneration = m->getCreationTime();
      lastPacketReception = m->getArrivalTime();
      if(trace) {
        debugEV<< "Received a data packet from host[" << m->getSrcAddr()
        << "], latency=" << theLatency
        << ", collected " << hostsLatency(m->getSrcAddr()).
        getCount() << "mean is now: " << hostsLatency(m->getSrcAddr()).
        getMean() << endl;
      } else {
          debugEV<< "Received a data packet from host[" << m->getSrcAddr()
          << "], latency=" << theLatency << endl;
      }
    }
    delete msg;
    //  sendReply(m);
    break;
    default:
    EV << "Error! got packet with unknown kind: " << msg->getKind() << endl;
    delete msg;
    break;
  }
}
void SensorApplLayer::handleSelfMsg (cMessage * msg) [protected, virtual]
Handle self messages such as timer...
A timer with kind = SEND_DATA_TIMER indicates that a new data has to be send (sendData).
There are no other timers implemented for this module.
See also:
sendData
Implements BaseLayer.
References sendData().
{
  switch (msg->getKind()) {
  case SEND_DATA_TIMER:
    sendData();
    //delete msg;
    break;
  default:
    EV<< "Unkown selfmessage! -> delete, kind: " << msg->getKind() << endl;
    delete msg;
    break;
  }
}
virtual void SensorApplLayer::handleUpperMsg (cMessage * msg) [inline, protected, virtual]
Handle messages from upper layer.
This function is pure virtual here, because there is no reasonable guess what to do with it by default.
Implements BaseLayer.
        {
            delete m;
        }
cStdDev & SensorApplLayer::hostsLatency (const LAddress::L3Type & hostAddress) [protected]
Returns the latency statistics variable for the passed host address.
Parameters:
hostAddress the address of the host to return the statistics for.
Returns:
A reference to the hosts latency statistics.
Referenced by handleLowerMsg().
{
  using std::pair;
  if(latencies.count(hostAddress) == 0) {
    std::ostringstream oss;
    oss << hostAddress;
    cStdDev aLatency(oss.str().c_str());
    latencies.insert(pair<LAddress::L3Type, cStdDev>(hostAddress, aLatency));
  }
  return latencies[hostAddress];
}
void SensorApplLayer::initialize (int stage) [virtual]
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BasicModule.
Then we will set a timer to indicate the first time we will send a message
Reimplemented from BaseLayer.
References BaseLayer::catPacketSignal, debug, BaseModule::findHost(), simsignalwrap_t::initialize(), initializeDistribution(), and AddressingInterface::myNetwAddr().
{
    BaseLayer::initialize(stage);
  if (stage == 0) {
    BaseLayer::catPacketSignal.initialize();
    debugEV<< "in initialize() stage 0...";
    debug = par("debug");
    stats = par("stats");
    trace = par("trace");
    nbPackets = par("nbPackets");
    trafficParam = par("trafficParam");
    initializationTime = par("initializationTime");
    broadcastPackets = par("broadcastPackets");
    headerLength = par("headerLength");
    // application configuration
    const char *traffic = par("trafficType");
    destAddr = LAddress::L3Type(par("destAddr").longValue());
    nbPacketsSent = 0;
    nbPacketsReceived = 0;
    firstPacketGeneration = -1;
    lastPacketReception = -2;
    initializeDistribution(traffic);
    delayTimer = new cMessage("appDelay", SEND_DATA_TIMER);
    // get pointer to the world module
    world = FindModule<BaseWorldUtility*>::findGlobalModule();
  } else if (stage == 1) {
    debugEV << "in initialize() stage 1...";
    // Application address configuration: equals to host address
    cModule *const pHost = findHost();
    const cModule* netw  = FindModule<BaseNetwLayer*>::findSubModule(pHost);
    if(!netw) {
      netw = pHost->getSubmodule("netwl");
      if(!netw) {
        opp_error("Could not find network layer module. This means "
              "either no network layer module is present or the "
              "used network layer module does not subclass from "
              "BaseNetworkLayer.");
      }
    }
    const AddressingInterface *const addrScheme = FindModule<AddressingInterface*>::findSubModule(pHost);
    if(addrScheme) {
      myAppAddr = addrScheme->myNetwAddr(netw);
    } else {
      myAppAddr = LAddress::L3Type( netw->getId() );
    }
    sentPackets = 0;
    // first packet generation time is always chosen uniformly
    // to avoid systematic collisions
    if(nbPackets> 0)
      scheduleAt(simTime() +uniform(initializationTime, initializationTime + trafficParam), delayTimer);
    if (stats) {
      latenciesRaw.setName("rawLatencies");
      latenciesRaw.setUnit("s");
      latency.setName("latency");
    }
  }
}
void SensorApplLayer::sendData () [protected, virtual]
send a data packet to the next hop
This function creates a new data message and sends it down to the network layer.
References BaseLayer::catPacketSignal, LAddress::L3BROADCAST, scheduleNextPacket(), BaseLayer::sendDown(), and NetwControlInfo::setControlInfo().
Referenced by handleSelfMsg().
{
  ApplPkt *pkt = new ApplPkt("Data", DATA_MESSAGE);
  if(broadcastPackets) {
    pkt->setDestAddr(LAddress::L3BROADCAST);
  } else {
    pkt->setDestAddr(destAddr);
  }
  pkt->setSrcAddr(myAppAddr);
  pkt->setByteLength(headerLength);
  // set the control info to tell the network layer the layer 3 address
  NetwControlInfo::setControlInfo(pkt, pkt->getDestAddr());
  debugEV<< "Sending data packet!\n";
  sendDown(pkt);
  nbPacketsSent++;
  packet.setPacketSent(true);
  packet.setNbPacketsSent(1);
  packet.setNbPacketsReceived(0);
  packet.setHost(myAppAddr);
  emit(BaseLayer::catPacketSignal, &packet);
  sentPackets++;
  scheduleNextPacket();
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/application/SensorApplLayer.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/application/SensorApplLayer.cc