MiXiM: MACAddress Class Reference
MACAddress Class Reference
#include <MACAddress.h>
Public Member Functions
MACAddress ()
MACAddress (uint64 bits)
MACAddress (const char *hexstr)
MACAddress (const MACAddress &other)
MACAddress & operator= (const MACAddress &other)
unsigned int getAddressSize () const
unsigned char getAddressByte (unsigned int k) const
void setAddressByte (unsigned int k, unsigned char addrbyte)
bool tryParse (const char *hexstr)
void setAddress (const char *hexstr)
void getAddressBytes (unsigned char *addrbytes) const
void getAddressBytes (char *addrbytes) const
void setAddressBytes (unsigned char *addrbytes)
void setAddressBytes (char *addrbytes)
void setBroadcast ()
bool isBroadcast () const
bool isMulticast () const
bool isUnspecified () const
std::string str () const
uint64 getInt () const
bool equals (const MACAddress &other) const
bool operator== (const MACAddress &other) const
bool operator!= (const MACAddress &other) const
int compareTo (const MACAddress &other) const
InterfaceToken formInterfaceIdentifier () const
bool operator< (const MACAddress &other) const
bool operator> (const MACAddress &other) const
Static Public Member Functions
static MACAddress generateAutoAddress ()
Static Public Attributes
static const MACAddress UNSPECIFIED_ADDRESS
static const MACAddress BROADCAST_ADDRESS
static const MACAddress MULTICAST_PAUSE_ADDRESS
Private Attributes
uint64 address
Static Private Attributes
static unsigned int autoAddressCtr
Detailed Description
Stores an IEEE 802 MAC address (6 octets = 48 bits).
Constructor & Destructor Documentation
MACAddress::MACAddress () [inline]
Default constructor initializes address bytes to zero.
{ address = 0; }
MACAddress::MACAddress (uint64 bits) [inline, explicit]
Initializes the address from the lower 48 bits of the 64-bit argument
{ address = bits & MAC_ADDRESS_MASK; }
MACAddress::MACAddress (const char * hexstr) [inline, explicit]
Constructor which accepts a hex string (12 hex digits, may also contain spaces, hyphens and colons)
{ setAddress(hexstr); }
MACAddress::MACAddress (const MACAddress & other) [inline]
Copy constructor.
{ address = other.address; }
Member Function Documentation
int MACAddress::compareTo (const MACAddress & other) const
Returns -1, 0 or 1 as result of comparison of 2 addresses.
{
    return (address < other.address) ? -1 : (address == other.address) ? 0 : 1;  // note: "return address-other.address" is not OK because 64-bit result does not fit into the return type
}
bool MACAddress::equals (const MACAddress & other) const [inline]
Returns true if the two addresses are equal.
{ return address == other.address; }
InterfaceToken MACAddress::formInterfaceIdentifier () const
Create interface identifier (IEEE EUI-64) which can be used by IPv6 stateless address autoconfiguration.
{
    uint32 high = ((address>>16)|0xff)^0x02000000;
    uint32 low = (0xfe<<24)|(address&0xffffff);
    return InterfaceToken(low, high, 64);
}
MACAddress MACAddress::generateAutoAddress () [static]
Generates a unique address which begins with 0a:aa and ends in a unique suffix.
{
    ++autoAddressCtr;
    uint64 intAddr = 0x0AAA00000000L + (autoAddressCtr & 0xffffffffL);
    MACAddress addr(intAddr);
    return addr;
}
unsigned char MACAddress::getAddressByte (unsigned int k) const
Returns the kth byte of the address.
Referenced by getAddressBytes(), and str().
{
    if (k>=MAC_ADDRESS_SIZE) throw cRuntimeError("Array of size 6 indexed with %d", k);
    int offset = (MAC_ADDRESS_SIZE-k-1)*8;
    return 0xff&(address>>offset);
}
void MACAddress::getAddressBytes (unsigned char * addrbytes) const
Copies the address to the given pointer (array of 6 unsigned chars).
References getAddressByte().
{
    for (int i = 0; i < MAC_ADDRESS_SIZE; i++)
        addrbytes[i] = getAddressByte(i);
}
unsigned int MACAddress::getAddressSize () const [inline]
Returns the address size in bytes, that is, 6.
{ return MAC_ADDRESS_SIZE; }
uint64 MACAddress::getInt () const [inline]
Converts address to 48 bits integer.
{ return address; }
bool MACAddress::isBroadcast () const [inline]
Returns true if this is the broadcast address (hex ff:ff:ff:ff:ff:ff).
{ return address == MAC_ADDRESS_MASK; }
bool MACAddress::isMulticast () const [inline]
Returns true if this is a multicast logical address (first byte's lsb is 1).
{ return getAddressByte(0) & 0x01; };
bool MACAddress::isUnspecified () const [inline]
Returns true if all address bytes are zero.
{ return address == 0; }
bool MACAddress::operator!= (const MACAddress & other) const [inline]
Returns true if the two addresses are not equal.
{ return address != other.address; }
MACAddress& MACAddress::operator= (const MACAddress & other) [inline]
Assignment.
{ address = other.address; return *this; }
bool MACAddress::operator== (const MACAddress & other) const [inline]
Returns true if the two addresses are equal.
{ return address == other.address; }
void MACAddress::setAddress (const char * hexstr)
Converts address value from hex string (12 hex digits, may also contain spaces, hyphens and colons)
References tryParse().
{
    if (!tryParse(hexstr))
        throw cRuntimeError("MACAddress: wrong address syntax '%s': 12 hex digits expected, with optional embedded spaces, hyphens or colons", hexstr);
}
void MACAddress::setAddressByte (unsigned int k, unsigned char addrbyte)
Sets the kth byte of the address.
Referenced by setAddressBytes(), and tryParse().
{
    if (k>=MAC_ADDRESS_SIZE) throw cRuntimeError("Array of size 6 indexed with %d", k);
    int offset = (MAC_ADDRESS_SIZE-k-1)*8;
    address = (address&(~(((uint64)0xff)<<offset)))|(((uint64)addrbyte)<<offset);
}
void MACAddress::setAddressBytes (unsigned char * addrbytes)
Sets address bytes. The argument should point to an array of 6 unsigned chars.
References setAddressByte().
{
    address = 0; // clear top 16 bits too that setAddressByte() calls skip
    for (int i = 0; i < MAC_ADDRESS_SIZE; i++)
        setAddressByte(i, addrbytes[i]);
}
void MACAddress::setBroadcast () [inline]
Sets the address to the broadcast address (hex ff:ff:ff:ff:ff:ff).
{ address = MAC_ADDRESS_MASK; }
std::string MACAddress::str () const
Converts address to a hex string.
References getAddressByte().
{
    char buf[20];
    char *s = buf;
    for (int i=0; i<MAC_ADDRESS_SIZE; i++, s += 3)
        sprintf(s, "%2.2X-", getAddressByte(i));
    *(s-1) = '\0';
    return std::string(buf);
}
bool MACAddress::tryParse (const char * hexstr)
Sets the address and returns true if the syntax of the string is correct. (See setAddress() for the syntax.)
References setAddressByte().
Referenced by setAddress().
{
    if (!hexstr)
        return false;
    // check syntax
    int numHexDigits = 0;
    for (const char *s = hexstr; *s; s++) {
        if (isxdigit(*s))
            numHexDigits++;
        else if (*s!=' ' && *s!=':' && *s!='-')
            return false; // wrong syntax
    }
    if (numHexDigits != 2*MAC_ADDRESS_SIZE)
        return false;
    // Converts hex string into the address
    // if hext string is shorter, address is filled with zeros;
    // Non-hex characters are discarded before conversion.
    address = 0; // clear top 16 bits too that setAddressByte() calls skip
    int k = 0;
    const char *s = hexstr;
    for (int pos=0; pos<MAC_ADDRESS_SIZE; pos++)
    {
        if (!s || !*s)
        {
            setAddressByte(pos, 0);
        }
        else
        {
            while (*s && !isxdigit(*s)) s++;
            if (!*s) {setAddressByte(pos, 0); continue;}
            unsigned char d = isdigit(*s) ? (*s-'0') : islower(*s) ? (*s-'a'+10) : (*s-'A'+10);
            d = d<<4;
            s++;
            while (*s && !isxdigit(*s)) s++;
            if (!*s) {setAddressByte(pos, 0); continue;}
            d += isdigit(*s) ? (*s-'0') : islower(*s) ? (*s-'a'+10) : (*s-'A'+10);
            s++;
            setAddressByte(pos, d);
            k++;
        }
    }
    return true;
}
Member Data Documentation
const MACAddress MACAddress::BROADCAST_ADDRESS [static]
The broadcast MAC address, ff:ff:ff:ff:ff:ff
const MACAddress MACAddress::MULTICAST_PAUSE_ADDRESS [static]
The special multicast PAUSE MAC address, 01:80:C2:00:00:01
const MACAddress MACAddress::UNSPECIFIED_ADDRESS [static]
The unspecified MAC address, 00:00:00:00:00:00
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/linklayer/contract/MACAddress.h
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/linklayer/contract/MACAddress.cc