MiXiM: JakesFading Class Reference
JakesFading Class Reference
analogueModels - AnalogueModel implementations
Implements Rayleigh fading after Jakes' model.
#include <JakesFading.h>
Public Member Functions
JakesFading ()
Default constructor for the model, the initialization will be done in initFromMap.
virtual bool initFromMap (const ParameterMap &)
Initialize the analog model from XML map data.
virtual void filterSignal (airframe_ptr_t, const Coord &, const Coord &)
Has to be overriden by every implementation.
Protected Attributes
int fadingPaths
Number of fading paths used.
double * angleOfArrival
Angle of arrival on a fading path used for Doppler shift calculation.
simtime_t * delay
Delay on a fading path.
double carrierFrequency
Carrier frequency to be used.
Argument interval
The interval to set attenuation entries in.
Private Member Functions
JakesFading (const JakesFading &)
Copy constructor is not allowed.
JakesFading & operator= (const JakesFading &)
Assignment operator is not allowed.
Friends
class JakesFadingMapping
Detailed Description
Implements Rayleigh fading after Jakes' model.
An example config.xml for this AnalogueModel can be the following:
    <AnalogueModel type="JakesFading">
        <!-- Carrier frequency of the signal in Hz
             If ommited the carrier frequency from the
             connection manager is taken if available
             otherwise set to default frequency of 2.412e+9-->
        <parameter name="carrierFrequency" type="double" value="2.412e+9"/>
        <!-- Number of fading paths per host -->
        <parameter name="fadingPaths" type="long" value="3"/>
        <!-- f-selectivity: mean delay spread in seconds -->
        <parameter name="delayRMS" type="double" value="0.0001"/>
        <!-- Interval in which to define attenuation for in seconds -->
        <parameter name="interval" type="double" value="0.001"/>
    </AnalogueModel>
Author:
Hermann S. Lichte, Karl Wessel (port for MiXiM)
Member Function Documentation
void JakesFading::filterSignal (airframe_ptr_t frame, const Coord & sendersPos, const Coord & receiverPos) [virtual]
Has to be overriden by every implementation.
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Parameters:
frame The incomming frame.
sendersPos The position of the frame sender.
receiverPos The position of frame receiver.
Implements AnalogueModel.
References Signal::addAttenuation(), Signal::getReceptionEnd(), Signal::getReceptionStart(), and interval.
{
  Signal&                signal           = frame->getSignal();
  ChannelMobilityPtrType senderMobility   = dynamic_cast<ConnectionManagerAccess *>(frame->getSenderModule())->getMobilityModule();
  ChannelMobilityPtrType receiverMobility = dynamic_cast<ConnectionManagerAccess *>(frame->getArrivalModule())->getMobilityModule();
  const double           relSpeed         = (senderMobility->getCurrentSpeed() - receiverMobility->getCurrentSpeed()).length();
  signal.addAttenuation(new JakesFadingMapping(this, relSpeed,
                                               Argument(signal.getReceptionStart()),
                                               interval,
                                               Argument(signal.getReceptionEnd())));
}
bool JakesFading::initFromMap (const ParameterMap & params) [virtual]
Initialize the analog model from XML map data.
This method should be defined for generic analog model initialization.
Parameters:
params The parameter map which was filled by XML reader.
Returns:
true if the initialization was successfully.
Reimplemented from AnalogueModel.
References angleOfArrival, carrierFrequency, delay, fadingPaths, and interval.
{
    ParameterMap::const_iterator it;
    bool                         bInitSuccess = true;
    double                       delayRMS     = 0.0;
    if ((it = params.find("seed")) != params.end()) {
        srand( ParameterMap::mapped_type(it->second).longValue() );
    }
    if ((it = params.find("fadingPaths")) != params.end()) {
        fadingPaths = ParameterMap::mapped_type(it->second).longValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No fadingPaths defined in config.xml for JakesFading!");
    }
    if ((it = params.find("delayRMS")) != params.end()) {
        delayRMS = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No delayRMS defined in config.xml for JakesFading!");
    }
    if ((it = params.find("interval")) != params.end()) {
        interval = Argument(ParameterMap::mapped_type(it->second).doubleValue());
    }
    else {
        bInitSuccess = false;
        opp_warning("No interval defined in config.xml for JakesFading!");
    }
    if ((it = params.find("carrierFrequency")) != params.end()) {
        carrierFrequency = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No carrierFrequency defined in config.xml for JakesFading!");
    }
    if (bInitSuccess) {
  angleOfArrival = new double[fadingPaths];
  delay = new simtime_t[fadingPaths];
  for (int i = 0; i < fadingPaths; ++i) {
    angleOfArrival[i] = cos(uniform(0, M_PI));
    delay[i] = exponential(delayRMS);
  }
    }
    return AnalogueModel::initFromMap(params) && bInitSuccess;
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/JakesFading.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/JakesFading.cc