MiXiM: MappingUtils Class Reference
MappingUtils Class Reference
mapping - classes representing mathematical mappings
Provides several utility methods for Mappings.
#include <MappingUtils.h>
Public Types
typedef std::list< const
ConstMapping * > MappingBuffer
Static Public Member Functions
static Mapping * createMapping (const DimensionSet &domain=DimensionSet(Dimension::time), Mapping::InterpolationMethod intpl=Mapping::LINEAR)
Returns an appropriate changeable Mapping with the specified domain and the specified interpolation method.
static Mapping * createMapping (Mapping::argument_value_cref_t outOfRangeValue, const DimensionSet &domain=DimensionSet(Dimension::time), Mapping::InterpolationMethod intpl=Mapping::LINEAR)
Returns an appropriate changeable Mapping with the specified domain and the specified interpolation method.
template<class Operator >
static Mapping * applyElementWiseOperator (const ConstMapping &f1, const ConstMapping &f2, const Argument &intvlStart, const Argument &intvlEnd, Operator op)
template<class Operator >
static Mapping * applyElementWiseOperator (const ConstMapping &f1, const ConstMapping &f2, Operator op, Mapping::argument_value_cref_t outOfRangeVal=Argument::MappedZero, bool contOutOfRange=true)
static Mapping * multiply (const ConstMapping &f1, const ConstMapping &f2)
Multiplies the passed functions element-wise with each other and returns the result in a new Function.
static Mapping * add (const ConstMapping &f1, const ConstMapping &f2)
static Mapping * subtract (const ConstMapping &f1, const ConstMapping &f2)
static Mapping * divide (const ConstMapping &f1, const ConstMapping &f2)
static Mapping * multiply (const ConstMapping &f1, const ConstMapping &f2, Mapping::argument_value_cref_t outOfRangeVal)
static Mapping * add (const ConstMapping &f1, const ConstMapping &f2, Mapping::argument_value_cref_t outOfRangeVal)
static Mapping * subtract (const ConstMapping &f1, const ConstMapping &f2, Mapping::argument_value_cref_t outOfRangeVal)
static Mapping * divide (const ConstMapping &f1, const ConstMapping &f2, Mapping::argument_value_cref_t outOfRangeVal)
static Argument::mapped_type findMax (const ConstMapping &m, Argument::mapped_type_cref cRetNotFound=cMaxNotFound)
Iterates over the passed mapping and returns value at the key entry with the highest value.
static Argument::mapped_type findMax (const ConstMapping &m, const Argument &min, const Argument &max, Argument::mapped_type_cref cRetNotFound=cMaxNotFound)
Iterates over the passed mapping and returns the value at the key entry with the highest value in the range defined by the passed min and max parameter.
static Argument::mapped_type findMin (const ConstMapping &m, Argument::mapped_type_cref cRetNotFound=cMinNotFound)
Iterates over the passed mapping and returns value at the key entry with the smallest value.
static Argument::mapped_type findMin (const ConstMapping &m, const Argument &min, const Argument &max, Argument::mapped_type_cref cRetNotFound=cMinNotFound)
Iterates over the passed mapping and returns the value at the key entry with the smallest value in the range defined by the passed min and max parameter.
static void addDiscontinuity (Mapping *m, const Argument &pos, Argument::mapped_type_cref value, simtime_t_cref limitTime, Argument::mapped_type_cref limitValue)
Adds a discontinuity in time-dimension, i.e. its representation, to a passed mapping.
static simtime_t pre (simtime_t_cref t)
returns the closest value of simtime before passed value
static simtime_t post (simtime_t_cref t)
returns the closest value of simtime after passed values
static simtime_t incNextPosition (simtime_t_cref t)
returns the incremented position point (used in RSAMConstMappingIterator::setNextPosition).
Static Public Attributes
static const Argument::mapped_type cMinNotFound = std::numeric_limits<Argument::mapped_type>::infinity()
The default value for findMin() functions if it does not find a minimum element.
static const Argument::mapped_type cMaxNotFound = -std::numeric_limits<Argument::mapped_type>::infinity()
The default value for findMax() functions if it does not find a maximum element.
Static Private Member Functions
static const ConstMapping * createCompatibleMapping (const ConstMapping &src, const ConstMapping &dst)
static bool iterateToNext (ConstMappingIterator *it1, ConstMappingIterator *it2)
Detailed Description
Provides several utility methods for Mappings.
Author:
Karl Wessel
Member Function Documentation
void MappingUtils::addDiscontinuity (Mapping * m, const Argument & pos, Argument::mapped_type_cref value, simtime_t_cref limitTime, Argument::mapped_type_cref limitValue) [static]
Adds a discontinuity in time-dimension, i.e. its representation, to a passed mapping.
This is done by setting a regular entry and a limit-entry. The limit-entry shall be very close to the regular entry (on its left or right).
The implementation works simply by adding the limit-value as a separate entry at the position of the limit-time. This means that this methods adds a total of two entries to the passed mapping.
Note: One should use the methods 'pre' or 'post' provided by MappingUtils to calculate the limit-time for the discontinuity.
Parameters:
m The mapping the discontinuity will be added to.
pos The position of the regular entry.
value The value of the regular entry.
limitTime The time-point of the limit-entry.
limitValue The value of the limit-entry.
References Argument::getTime(), Argument::setTime(), and Mapping::setValue().
Referenced by BaseMacLayer::createRectangleMapping().
{
  // asserts/preconditions
  // make sure the time really differs at the discontinuity
  assert(limitTime != pos.getTime());
  // add (pos, value) to mapping
  m->setValue(pos, value);
  // create Argument limitPos for the limit-position, i.e. copy pos and set limitTime as its time
  Argument limitPos = pos;
  limitPos.setTime(limitTime);
  // add (limitPos, limitValue) to mapping
  m->setValue(limitPos, limitValue);
}
Mapping * MappingUtils::createMapping (const DimensionSet & domain = DimensionSet(Dimension::time), Mapping::InterpolationMethod intpl = Mapping::LINEAR) [static]
Returns an appropriate changeable Mapping with the specified domain and the specified interpolation method.
Note: The interpolation method is always linear, at the moment.
References DimensionSet::hasDimension(), Mapping::LINEAR, Mapping::NEAREST, DimensionSet::size(), Mapping::STEPS, and Dimension::time.
Referenced by BaseDecider::calculateRSSIMapping(), BaseMacLayer::createConstantMapping(), BaseMacLayer::createRectangleMapping(), Mac80211::createSignal(), BaseMacLayer::createSingleFrequencyMapping(), RandomFreqTimeModel::filterSignal(), RandomFrequencyOnlyModel::filterSignal(), and LogNormalShadowing::filterSignal().
{
  assert(domain.hasDimension(Dimension::time));
  if(domain.size() == 1){
    switch(intpl){
    case Mapping::LINEAR:
      return new TimeMapping<Linear>();
      break;
    case Mapping::NEAREST:
      return new TimeMapping<Nearest>();
      break;
    case Mapping::STEPS:
      return new TimeMapping<NextSmaller>();
      break;
    }
    return 0;
  } else {
    switch(intpl){
    case Mapping::LINEAR:
      return new MultiDimMapping<Linear>(domain);
      break;
    case Mapping::NEAREST:
      return new MultiDimMapping<Nearest>(domain);
      break;
    case Mapping::STEPS:
      return new MultiDimMapping<NextSmaller>(domain);
      break;
    }
    return 0;
  }
}
Mapping * MappingUtils::createMapping (Mapping::argument_value_cref_t outOfRangeValue, const DimensionSet & domain = DimensionSet(Dimension::time), Mapping::InterpolationMethod intpl = Mapping::LINEAR) [static]
Returns an appropriate changeable Mapping with the specified domain and the specified interpolation method.
Note: The interpolation method is always linear, at the moment.
References DimensionSet::hasDimension(), Mapping::LINEAR, Mapping::NEAREST, DimensionSet::size(), Mapping::STEPS, and Dimension::time.
{
  assert(domain.hasDimension(Dimension::time));
  if(domain.size() == 1){
    switch(intpl){
    case Mapping::LINEAR:
      return new TimeMapping<Linear>(outOfRangeVal);
      break;
    case Mapping::NEAREST:
      return new TimeMapping<Nearest>(outOfRangeVal);
      break;
    case Mapping::STEPS:
      return new TimeMapping<NextSmaller>(outOfRangeVal);
      break;
    }
    return 0;
  } else {
    switch(intpl){
    case Mapping::LINEAR:
      return new MultiDimMapping<Linear>(domain, outOfRangeVal);
      break;
    case Mapping::NEAREST:
      return new MultiDimMapping<Nearest>(domain, outOfRangeVal);
      break;
    case Mapping::STEPS:
      return new MultiDimMapping<NextSmaller>(domain, outOfRangeVal);
      break;
    }
    return 0;
  }
}
Mapping::argument_value_t MappingUtils::findMax (const ConstMapping & m, Argument::mapped_type_cref cRetNotFound = cMaxNotFound) [static]
Iterates over the passed mapping and returns value at the key entry with the highest value.
Parameters:
m The map where the maximum value shall be searched.
cRetNotFound The value which shall be returned if no maximum was found (default MappingUtils::cMaxNotFound).
Returns:
The value at the key entry with the highest value or cRetNotFound if map is empty.
References ConstMapping::createConstIterator(), ConstMappingIterator::getValue(), ConstMappingIterator::hasNext(), ConstMappingIterator::inRange(), and ConstMappingIterator::next().
Referenced by Decider80211::calcChannelSenseRSSI(), and BaseDecider::calcChannelSenseRSSI().
{
  ConstMappingIterator*     it       = m.createConstIterator();
  bool                      bIsFirst = true;
  Mapping::argument_value_t res;
  while(it->inRange()){
    Mapping::argument_value_cref_t val = it->getValue();
    if(bIsFirst || val > res) {
      res      = val;
      bIsFirst = false;
    }
    //std::cerr << "findMax(): " << val << " @ " << it->getPosition() << "; max is now: " << res << std::endl;
    if(!it->hasNext())
      break;
    it->next();
  }
  delete it;
  if (bIsFirst) {
    // no maximum available, maybe map is empty
    return cRetNotFound;
  }
  return res;
}
Mapping::argument_value_t MappingUtils::findMax (const ConstMapping & m, const Argument & min, const Argument & max, Argument::mapped_type_cref cRetNotFound = cMaxNotFound) [static]
Iterates over the passed mapping and returns the value at the key entry with the highest value in the range defined by the passed min and max parameter.
The area defined by the min and max parameter is the number of key entries which position in each dimension is bigger or equal than the value of the min parameter in that dimension and smaller or equal than max parameter in that dimension.
Parameters:
m The map where the maximum value shall be searched.
min The beginning of search range.
max The end of search range.
cRetNotFound The value which shall be returned if no maximum was found (default MappingUtils::cMaxNotFound).
Returns:
The value at the key entry with the highest value or cRetNotFound if map is empty or no element in range [min,max].
References Argument::begin(), ConstMapping::createConstIterator(), Argument::end(), Argument::getArgValue(), Argument::getDimensions(), ConstMapping::getDimensionSet(), Argument::getTime(), ConstMappingIterator::getValue(), and DimensionSet::isSubSet().
{
  const DimensionSet& rDimSet = m.getDimensionSet();
  //the passed interval should define a value for every dimension
  //of the mapping.
  assert(pRangeFrom.getDimensions().isSubSet(rDimSet));
  assert(pRangeTo.getDimensions().isSubSet(rDimSet));
  ConstMappingIterator*     it       = m.createConstIterator(pRangeFrom);
  bool                      bIsFirst = true;
  Mapping::argument_value_t res;
  //std::cerr << "findMax(m, " << pRangeFrom << ", " << pRangeTo << "): Map is" << std::endl << m;
  if (it->inRange()) {
    res      = it->getValue();
    bIsFirst = false;
    //std::cerr << "findMax(...):  " << " @ " << it->getPosition() << "; max is at beginning: " << res << std::endl;
  }
  while(it->hasNext() && it->getNextPosition().compare(pRangeTo, &rDimSet) < 0){
    it->next();
    const Argument& next    = it->getPosition();
    bool            inRange = pRangeFrom.getTime() <= next.getTime() && next.getTime() <= pRangeTo.getTime();
    if(inRange) {
      const Argument::const_iterator itAEnd = next.end();
      for(Argument::const_iterator itA = next.begin(); itA != itAEnd; ++itA) {
        if(pRangeFrom.getArgValue(itA->first) > itA->second || itA->second > pRangeTo.getArgValue(itA->first)) {
          inRange = false;
          break;
        }
      }
    }
    if(inRange) {
      Mapping::argument_value_cref_t val = it->getValue();
      if(bIsFirst || val > res) {
        res      = val;
        bIsFirst = false;
      }
      //std::cerr << "findMax(...): " << val << " @ " << it->getPosition() << "; max is now: " << res << std::endl;
    }
  }
  it->iterateTo(pRangeTo);
  if (it->inRange()) {
    Mapping::argument_value_cref_t val = it->getValue();
    if(bIsFirst || val > res) {
      res      = val;
      bIsFirst = false;
    }
    //std::cerr << "findMax(...): " << val << " @ " << it->getPosition() << "; max is finally: " << res << std::endl;
  }
  delete it;
  if (bIsFirst) {
    // no minimum available
    return cRetNotFound;
  }
  return res;
}
Mapping::argument_value_t MappingUtils::findMin (const ConstMapping & m, Argument::mapped_type_cref cRetNotFound = cMinNotFound) [static]
Iterates over the passed mapping and returns value at the key entry with the smallest value.
Parameters:
m The map where the minimum value shall be searched.
cRetNotFound The value which shall be returned if no minimum was found (default MappingUtils::cMinNotFound).
Returns:
The value at the key entry with the lowest value or cRetNotFound if map is empty.
References ConstMapping::createConstIterator(), ConstMappingIterator::getValue(), ConstMappingIterator::hasNext(), ConstMappingIterator::inRange(), and ConstMappingIterator::next().
Referenced by Decider80211::createResult().
{
  ConstMappingIterator*     it       = m.createConstIterator();
  bool                      bIsFirst = true;
  Mapping::argument_value_t res;
  while(it->inRange()) {
    Mapping::argument_value_cref_t val = it->getValue();
    if(bIsFirst || val < res) {
      res      = val;
      bIsFirst = false;
    }
    //std::cerr << "findMin(): " << val << " @ " << it->getPosition() << "; min is now: " << res << std::endl;
    if(!it->hasNext())
      break;
    it->next();
  }
  delete it;
  if (bIsFirst) {
    // no minimum available, maybe map is empty
    return cRetNotFound;
  }
  return res;
}
Mapping::argument_value_t MappingUtils::findMin (const ConstMapping & m, const Argument & min, const Argument & max, Argument::mapped_type_cref cRetNotFound = cMinNotFound) [static]
Iterates over the passed mapping and returns the value at the key entry with the smallest value in the range defined by the passed min and max parameter.
The area defined by the min and max parameter is the number of key entries which position in each dimension is bigger or equal than the value of the min parameter in that dimension and smaller or equal than max parameter in that dimension.
Parameters:
m The map where the minimum value shall be searched.
min The beginning of search range.
max The end of search range.
cRetNotFound The value which shall be returned if no minimum was found (default MappingUtils::cMinNotFound).
Returns:
The value at the key entry with the highest value or cRetNotFound if map is empty or no element in range [min,max].
References Argument::begin(), Argument::compare(), ConstMapping::createConstIterator(), Argument::end(), Argument::getArgValue(), Argument::getDimensions(), ConstMapping::getDimensionSet(), ConstMappingIterator::getNextPosition(), ConstMappingIterator::getPosition(), Argument::getTime(), ConstMappingIterator::getValue(), ConstMappingIterator::hasNext(), ConstMappingIterator::inRange(), DimensionSet::isSubSet(), ConstMappingIterator::iterateTo(), and ConstMappingIterator::next().
{
  const DimensionSet& rDimSet = m.getDimensionSet();
  //the passed interval should define a value for every dimension
  //of the mapping.
  assert(pRangeFrom.getDimensions().isSubSet(rDimSet));
  assert(pRangeTo.getDimensions().isSubSet(rDimSet));
  Mapping::argument_value_t res;
  bool                      bIsFirst = true;
  ConstMappingIterator*     it       = m.createConstIterator(pRangeFrom);
  //std::cerr << "findMin(m, " << pRangeFrom << ", " << pRangeTo << "): Map is" << std::endl << m;
  if (it->inRange()) {
    res      = it->getValue();
    bIsFirst = false;
    //std::cerr << "findMin(...):  " << " @ " << it->getPosition() << "; min is at beginning: " << res << std::endl;
  }
  while(it->hasNext() && it->getNextPosition().compare(pRangeTo, &rDimSet) < 0) {
    it->next();
    const Argument& next    = it->getPosition();
    bool            inRange = pRangeFrom.getTime() <= next.getTime()  && next.getTime() <= pRangeTo.getTime();
    if(inRange) {
      const Argument::const_iterator itAEnd = next.end();
      for(Argument::const_iterator itA = next.begin(); itA != itAEnd; ++itA) {
        if(pRangeFrom.getArgValue(itA->first) > itA->second || itA->second > pRangeTo.getArgValue(itA->first)) {
          inRange = false;
          break;
        }
      }
    }
    if(inRange) {
      Mapping::argument_value_cref_t val = it->getValue();
      if(bIsFirst || val < res) {
        res      = val;
        bIsFirst = false;
      }
      //std::cerr << "findMin(...): " << val << " @ " << it->getPosition() << "; min is now: " << res << std::endl;
    }
  }
  it->iterateTo(pRangeTo);
  if (it->inRange()) {
    Mapping::argument_value_cref_t val = it->getValue();
    if(bIsFirst || val < res) {
      res      = val;
      bIsFirst = false;
    }
    //std::cerr << "findMin(...): " << val << " @ " << it->getPosition() << "; min is finally: " << res << std::endl;
  }
  delete it;
  if (bIsFirst) {
    // no minimum available
    return cRetNotFound;
  }
  return res;
}
Mapping * MappingUtils::multiply (const ConstMapping & f1, const ConstMapping & f2) [static]
Multiplies the passed functions element-wise with each other and returns the result in a new Function.
The domain (DimensionSet) of the result is defined by the domain of the first operand. The domain of the second Mapping has to be a subset of the domain of the first mapping.
Referenced by ThresholdDecider::handleSignalOver().
{
  return applyElementWiseOperator(f1, f2, std::multiplies<Mapping::argument_value_t>());
}
Member Data Documentation
const Argument::mapped_type MappingUtils::cMaxNotFound = -std::numeric_limits<Argument::mapped_type>::infinity() [static]
The default value for findMax() functions if it does not find a maximum element.
It will be initialized with the negative infinity value.
const Argument::mapped_type MappingUtils::cMinNotFound = std::numeric_limits<Argument::mapped_type>::infinity() [static]
The default value for findMin() functions if it does not find a minimum element.
It will be initialized with the infinity value.
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/MappingUtils.h
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/MappingUtils.cc