MiXiM: NotificationBoard Class Reference
NotificationBoard Class Reference
#include <NotificationBoard.h>
Public Types
typedef std::vector
< INotifiable * > NotifiableVector
typedef std::map< int,
NotifiableVector > ClientMap
Public Member Functions
Methods for consumers of change notifications
virtual void subscribe (INotifiable *client, int category)
virtual void unsubscribe (INotifiable *client, int category)
virtual bool hasSubscribers (int category)
Methods for producers of change notifications
virtual void fireChangeNotification (int category, const cObject *details=NULL)
Protected Member Functions
virtual void initialize ()
virtual void handleMessage (cMessage *msg)
Protected Attributes
ClientMap clientMap
Friends
std::ostream & operator<< (std::ostream &, const NotifiableVector &)
Detailed Description
Acts as a intermediary between module where state changes can occur and modules which are interested in learning about those changes; "Notification Broker".
Notification events are grouped into "categories." Examples of categories are: NF_RADIOSTATE_CHANGED, NF_PP_TX_BEGIN, NF_PP_TX_END, NF_IPv4_ROUTE_ADDED, NF_BEACON_LOST, NF_NODE_FAILURE, NF_NODE_RECOVERY, etc. Each category is identified by an integer (right now it's assigned in the source code via an enum, in the future we'll convert to dynamic category registration).
To trigger a notification, the client must obtain a pointer to the NotificationBoard of the given host or router (explained later), and call its fireChangeNotification() method. The notification will be delivered to all subscribed clients immediately, inside the fireChangeNotification() call.
Clients that wish to receive notifications should implement (subclass from) the INotifiable interface, obtain a pointer to the NotificationBoard, and subscribe to the categories they are interested in by calling the subscribe() method of the NotificationBoard. Notifications will be delivered to the receiveChangeNotification() method of the client (redefined from INotifiable).
In cases when the category itself (an int) does not carry enough information about the notification event, one can pass additional information in a data class. There is no restriction on what the data class may contain, except that it has to be subclassed from cObject, and of course producers and consumers of notifications should agree on its contents. If no extra info is needed, one can pass a NULL pointer in the fireChangeNotification() method.
A module which implements INotifiable looks like this:
 class Foo : public cSimpleModule, public INotifiable {
     ...
     virtual void receiveChangeNotification(int category, const cObject *details) {..}
     ...
 };
Obtaining a pointer to the NotificationBoard module of that host/router:
 NotificationBoard *nb; // this is best made a module class member
 nb = NotificationBoardAccess().get();  // best done in initialize()
See NED file for additional info.
See also:
INotifiable
Author:
Andras Varga
Member Function Documentation
void NotificationBoard::fireChangeNotification (int category, const cObject * details = NULL) [virtual]
Tells NotificationBoard that a change of the given category has taken place. The optional details object may carry more specific information about the change (e.g. exact location, specific attribute that changed, old value, new value, etc).
Referenced by InterfaceTable::addInterface(), InterfaceTable::deleteInterface(), subscribe(), and unsubscribe().
{
    Enter_Method("fireChangeNotification(%s, %s)", notificationCategoryName(category),
                 details?details->info().c_str() : "n/a");
    ClientMap::iterator it = clientMap.find(category);
    if (it==clientMap.end())
        return;
    NotifiableVector& clients = it->second;
    for (NotifiableVector::iterator j=clients.begin(); j!=clients.end(); j++)
        (*j)->receiveChangeNotification(category, details);
}
void NotificationBoard::handleMessage (cMessage * msg) [protected, virtual]
Does nothing.
{
    error("NotificationBoard doesn't handle messages, it can be accessed via direct method calls");
}
bool NotificationBoard::hasSubscribers (int category) [virtual]
Returns true if any client has subscribed to the given category. This, by using a local boolean 'hasSubscriber' flag, allows performance-critical clients to leave out calls to fireChangeNotification() if there's no one subscribed anyway. The flag should be refreshed on each NF_SUBSCRIBERLIST_CHANGED notification.
{
    ClientMap::iterator it = clientMap.find(category);
    return it!=clientMap.end() && !it->second.empty();
}
void NotificationBoard::initialize () [protected, virtual]
Initialize.
{
    WATCH_MAP(clientMap);
}
void NotificationBoard::subscribe (INotifiable * client, int category) [virtual]
Subscribe to changes of the given category
References fireChangeNotification().
{
    Enter_Method("subscribe(%s)", notificationCategoryName(category));
    // find or create entry for this category
    NotifiableVector& clients = clientMap[category];
    // add client if not already there
    if (std::find(clients.begin(), clients.end(), client) == clients.end())
        clients.push_back(client);
    fireChangeNotification(NF_SUBSCRIBERLIST_CHANGED, NULL);
}
void NotificationBoard::unsubscribe (INotifiable * client, int category) [virtual]
Unsubscribe from changes of the given category
References fireChangeNotification().
{
    Enter_Method("unsubscribe(%s)", notificationCategoryName(category));
    // find (or create) entry for this category
    NotifiableVector& clients = clientMap[category];
    // remove client if there
    NotifiableVector::iterator it = std::find(clients.begin(), clients.end(), client);
    if (it!=clients.end())
        clients.erase(it);
    fireChangeNotification(NF_SUBSCRIBERLIST_CHANGED, NULL);
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/base/NotificationBoard.h
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/base/NotificationBoard.cc