MiXiM: SimplePathlossModel Class Reference
SimplePathlossModel Class Reference
analogueModels - AnalogueModel implementations
Basic implementation of a SimplePathlossModel that uses SimplePathlossConstMapping (that is subclassed from SimpleConstMapping) as attenuation-Mapping.
#include <SimplePathlossModel.h>
Public Member Functions
SimplePathlossModel ()
Initializes the analogue model. playgroundSize need to be valid as long as this instance exists.
virtual bool initFromMap (const ParameterMap &)
Initialize the analog model from XML map data.
virtual void filterSignal (airframe_ptr_t, const Coord &, const Coord &)
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
virtual double calcPathloss (const Coord &receiverPos, const Coord &sendersPos)
Method to calculate the attenuation value for pathloss.
Protected Attributes
double pathLossAlphaHalf
Path loss coefficient.
double carrierFrequency
carrier frequency needed for calculation
bool useTorus
Information needed about the playground.
Coord playgroundSize
The size of the playground.
bool debug
Whether debug messages should be displayed.
Friends
class SimplePathlossConstMapping
Detailed Description
Basic implementation of a SimplePathlossModel that uses SimplePathlossConstMapping (that is subclassed from SimpleConstMapping) as attenuation-Mapping.
An example config.xml for this AnalogueModel can be the following:
    <AnalogueModel type="SimplePathlossModel">
        <!-- Environment parameter of the pathloss formula
             If ommited default value is 3.5-->
        <parameter name="alpha" type="double" value="3.5"/>
        <!-- Carrier frequency of the signal in Hz
             If ommited the carrier frequency from the
             connection manager is taken if available
             otherwise set to default frequency of 2.412e+9-->
        <parameter name="carrierFrequency" type="double" value="2.412e+9"/>
    </AnalogueModel>
Constructor & Destructor Documentation
SimplePathlossModel::SimplePathlossModel () [inline]
Initializes the analogue model. playgroundSize need to be valid as long as this instance exists.
The constructor needs some specific knowledge in order to create its mapping properly:
Parameters:
alpha the coefficient alpha (specified e.g. in config.xml and passed in constructor call)
carrierFrequency the carrier frequency
useTorus information about the playground the host is moving in
playgroundSize information about the playground the host is moving in
debug display debug messages?
      : pathLossAlphaHalf(0)
      , carrierFrequency(0)
      , useTorus(false)
      , playgroundSize()
      , debug(false)
  { }
Member Function Documentation
double SimplePathlossModel::calcPathloss (const Coord & receiverPos, const Coord & sendersPos) [virtual]
Method to calculate the attenuation value for pathloss.
Functionality is similar to pathloss-calculation in BasicSnrEval from Mobility-frame work.
Note: This method is not used directly anymore. Instead the actual pathloss is calculated in SimplePathlossConstMappings "getValue()" method.
References carrierFrequency, pathLossAlphaHalf, playgroundSize, BaseWorldUtility::speedOfLight, Coord::sqrdist(), Coord::sqrTorusDist(), and useTorus.
{
  /*
   * maybe we can reuse an already calculated value for the square-distance
   * at this point.
   *
   */
  double sqrdistance = 0.0;
  if (useTorus)
  {
    sqrdistance = receiverPos.sqrTorusDist(sendersPos, playgroundSize);
  } else
  {
    sqrdistance = receiverPos.sqrdist(sendersPos);
  }
  splmEV << "sqrdistance is: " << sqrdistance << endl;
  double attenuation = 1.0;
  // wavelength in metres
  double wavelength = (BaseWorldUtility::speedOfLight/carrierFrequency);
  splmEV << "wavelength is: " << wavelength << endl;
  if (sqrdistance > 1.0)
  {
    attenuation = (wavelength * wavelength) / (16.0 * M_PI * M_PI)
            * (pow(sqrdistance, -1.0*pathLossAlphaHalf));
  }
  splmEV << "attenuation is: " << attenuation << endl;
  return attenuation;
}
void SimplePathlossModel::filterSignal (airframe_ptr_t frame, const Coord & sendersPos, const Coord & receiverPos) [virtual]
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Calculate the distance factor
Implements AnalogueModel.
References Signal::addAttenuation(), carrierFrequency, Dimension::frequency, ConstMapping::getDimensionSet(), Signal::getTransmissionPower(), DimensionSet::hasDimension(), pathLossAlphaHalf, playgroundSize, BaseWorldUtility::speedOfLight, Coord::sqrdist(), Coord::sqrTorusDist(), DimensionSet::timeDomain, DimensionSet::timeFreqDomain, and useTorus.
{
  Signal& signal = frame->getSignal();
  double sqrDistance = useTorus ? receiverPos.sqrTorusDist(sendersPos, playgroundSize)
                  : receiverPos.sqrdist(sendersPos);
  splmEV << "sqrdistance is: " << sqrDistance << endl;
  if(sqrDistance <= 1.0) {
    //attenuation is negligible
    return;
  }
  // wavelength in meters (this is only used for debug purposes here
  // the actual effect of the wavelength on the attenuation is
  // calculated in SimplePathlossConstMappings "getValue()" method).
  double wavelength = (BaseWorldUtility::speedOfLight/carrierFrequency);
  splmEV << "wavelength is: " << wavelength << endl;
  // the part of the attenuation only depending on the distance
  double distFactor = pow(sqrDistance, -pathLossAlphaHalf) / (16.0 * M_PI * M_PI);
  splmEV << "distance factor is: " << distFactor << endl;
  //is our signal to attenuate defined over frequency?
  bool hasFrequency = signal.getTransmissionPower()->getDimensionSet().hasDimension(Dimension::frequency);
  splmEV << "Signal contains frequency dimension: " << (hasFrequency ? "yes" : "no") << endl;
  const DimensionSet& domain = hasFrequency ? DimensionSet::timeFreqDomain : DimensionSet::timeDomain;
  //create the Attenuation mapping which takes the distance factor as parameter
  //to calculate the attenuation from this and the frequency used for the transmission
  //see the classes "getValue()" for more
  SimplePathlossConstMapping* attMapping = new SimplePathlossConstMapping(
                          domain,
                          this,
                          distFactor);
  /* at last add the created attenuation mapping to the signal */
  signal.addAttenuation(attMapping);
}
bool SimplePathlossModel::initFromMap (const ParameterMap & params) [virtual]
Initialize the analog model from XML map data.
This method should be defined for generic analog model initialization.
Parameters:
params The parameter map which was filled by XML reader.
Returns:
true if the initialization was successfully.
Reimplemented from AnalogueModel.
References carrierFrequency, debug, pathLossAlphaHalf, playgroundSize, and useTorus.
{
    ParameterMap::const_iterator it;
    bool                         bInitSuccess = true;
    if ((it = params.find("seed")) != params.end()) {
        srand( ParameterMap::mapped_type(it->second).longValue() );
    }
    if ((it = params.find("alpha")) != params.end()) {
        pathLossAlphaHalf = ParameterMap::mapped_type(it->second).doubleValue() * .5;
    }
    else {
        bInitSuccess = false;
        opp_warning("No alpha defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("useTorus")) != params.end()) {
        useTorus = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No useTorus defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("PgsX")) != params.end()) {
        playgroundSize.x = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No PgsX defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("PgsY")) != params.end()) {
        playgroundSize.y = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No PgsY defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("PgsZ")) != params.end()) {
        playgroundSize.z = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No PgsZ defined in config.xml for SimplePathlossModel!");
    }
    if ((it = params.find("debug")) != params.end()) {
        debug = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        debug = false;
    }
    if ((it = params.find("carrierFrequency")) != params.end()) {
        carrierFrequency = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No carrierFrequency defined in config.xml for SimplePathlossModel!");
    }
    return AnalogueModel::initFromMap(params) && bInitSuccess;
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/SimplePathlossModel.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/SimplePathlossModel.cc