MiXiM: NetworkStackTrafficGen Class Reference
NetworkStackTrafficGen Class Reference
IEEE 802.15.4 Narrow band example - Classes from the ieee802154Narrow example
A module to generate traffic for the NIC, used for testing purposes.
#include <NetworkStackTrafficGen.h>
Public Types
enum TrafficGenMessageKinds { TRAFFIC_TIMER = 1, BROADCAST_MESSAGE, TARGET_MESSAGE }
typedef NetwPkt netwpkt_t
typedef netwpkt_t * netwpkt_ptr_t
Public Member Functions
virtual void initialize (int stage)
Initialization of the module and some variables.
virtual void finish ()
Called when the simulation has finished.
Protected Member Functions
virtual void handleSelfMsg (cMessage *msg)
Handle self messages such as timer...
virtual void handleLowerMsg (cMessage *msg)
Handle messages from lower layer.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
virtual void sendBroadcast ()
Send a broadcast message to lower layer.
Protected Attributes
int packetLength
simtime_t packetTime
double pppt
int burstSize
int remainingBurst
LAddress::L3Type destination
long nbPacketDropped
ArpInterface * arp
LAddress::L3Type myNetwAddr
cMessage * delayTimer
BaseWorldUtility * world
Private Member Functions
NetworkStackTrafficGen (const NetworkStackTrafficGen &)
Copy constructor is not allowed.
NetworkStackTrafficGen & operator= (const NetworkStackTrafficGen &)
Assignment operator is not allowed.
Detailed Description
A module to generate traffic for the NIC, used for testing purposes.
Member Function Documentation
void NetworkStackTrafficGen::initialize (int stage) [virtual]
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseModule. This module takes care of the gate initialization.
Reimplemented from BaseLayer.
References BaseLayer::catPacketSignal, BaseModule::findHost(), simsignalwrap_t::initialize(), and AddressingInterface::myNetwAddr().
{
  BaseLayer::initialize(stage);
  if(stage == 0) {
    world = FindModule<BaseWorldUtility*>::findGlobalModule();
    delayTimer   = new cMessage("delay-timer", TRAFFIC_TIMER);
    arp          = FindModule<ArpInterface*>::findSubModule(findHost());
    packetLength = par("packetLength");
    packetTime = par("packetTime");
    pppt = par("packetsPerPacketTime");
    burstSize = par("burstSize");
    destination = LAddress::L3Type(par("destination").longValue());
    nbPacketDropped = 0;
    BaseMacLayer::catPacketSignal.initialize();
  }
  else if (stage == 1) {
    AddressingInterface* addrScheme = FindModule<AddressingInterface*>
                                                    ::findSubModule(findHost());
    if(addrScheme) {
      myNetwAddr = addrScheme->myNetwAddr(this);
    } else {
      myNetwAddr = LAddress::L3Type( getId() );
    }
    if(burstSize > 0) {
      remainingBurst = burstSize;
      scheduleAt(dblrand() * packetTime * burstSize / pppt, delayTimer);
    }
  } else {
  }
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/examples/ieee802154Narrow/NetworkStackTrafficGen.h
D:/Projects/MiXiM/extsrc/mixim/examples/ieee802154Narrow/NetworkStackTrafficGen.cc