MiXiM: PhyLayerBattery Class Reference
PhyLayerBattery Class Reference
Power consumption - Classes using/defining power consumption | phyLayer - physical layer modules
Extends PhyLayer by adding power consumption for tx, rx and idle.
#include <PhyLayerBattery.h>
Public Types
typedef MacPkt * macpkt_ptr_t
Public Member Functions
virtual void initialize (int stage)
OMNeT++ initialization function.
virtual void drawCurrent (double amount, int activity)
Provides ability to draw power for the Decider.
virtual simtime_t setRadioState (int rs)
Captures radio switches to adjust power consumption.
Protected Types
enum Activities {
SLEEP_ACCT = 0, RX_ACCT, TX_ACCT, SWITCHING_ACCT,
DECIDER_ACCT
}
Defines the power consuming activities (accounts) of the NIC. Should be the same as defined in the decider.
Protected Member Functions
virtual Decider * getDeciderFromName (const std::string &name, ParameterMap &params)
Creates and returns an instance of the decider with the specified name.
virtual double calcTXCurrentForPacket (macpkt_ptr_t, MacToPhyControlInfo *) const
Calculates the current needed for the transmission of the passed MacPkt.
virtual void setRadioCurrent (int rs)
Updates the actual current drawn for the passed state.
virtual void setSwitchingCurrent (int from, int to)
Updates the actual current drawn for switching between the passed states.
virtual void handleUpperMessage (cMessage *msg)
Checks the hosts state and draws txCurrent from battery.
virtual void handleAirFrame (airframe_ptr_t frame)
Checks if the the host state is on and prevents reception of AirFrames if not.
virtual void handleHostState (const HostState &state)
Captures changes in host state.
virtual void finishRadioSwitching (bool bSendCtrlMsg=true)
Captures radio switches to adjust power consumption.
Protected Attributes
int numActivities
Number of power consuming activities (accounts).
The different currents in mA.
double sleepCurrent
double rxCurrent
double decodingCurrentDelta
double txCurrent
The different switching state currents in mA.
double setupRxCurrent
double setupTxCurrent
double rxTxCurrent
double txRxCurrent
Detailed Description
Extends PhyLayer by adding power consumption for tx, rx and idle.
Does two things, first before sending messages to the channel or receiving messages from the channel it checks the hosts current state. If the host is not able to send or the receive (e.g. no power) the messages are dropped.
Further it draws a current depending on the current radio state. For this it captures every call to "setRadioState()" and changes the current to previously set default values according to the new radios state. There are different currents for TX, RX, SLEEP and SWITCHING state. Its also possible to override "calcTXCurrentForPacket()" to calculate the current used during TX depending on the actual TX power instead of using the default value.
Does also provide battery access to the Decider by implementing DeciderToPhyInterfaces "drawCurrent()"-method. Using this method the Decider can define a current delta which is applied to the RX current during this radio state. This is meant to be used if the Decider wants to define different currents for "listening" and "decoding" phases in RX state.
Defines initialization for "Decider80211Battery".
Member Function Documentation
virtual double PhyLayerBattery::calcTXCurrentForPacket (macpkt_ptr_t , MacToPhyControlInfo *) const [inline, protected, virtual]
Calculates the current needed for the transmission of the passed MacPkt.
A return value below or equal zero is ignored and the default txCurrent is used instead.
Sub classing modules can override this method if they don't want to use a default TX-current for every transmission but a current depending on the actual used TX power for a packet.
Referenced by handleUpperMessage().
  { return -1.0; }
void PhyLayerBattery::drawCurrent (double amount, int activity) [virtual]
Provides ability to draw power for the Decider.
Method is defined in "DeciderToPhyInterface".
Note: This method should only be used by the Decider to draw power. The phy layer itself should call instead its protected method MiximBatteryAccess::drawCurrent()!
Reimplemented from BasePhyLayer.
References MiximRadio::getCurrentState(), BasePhyLayer::radio, and MiximRadio::RX.
Referenced by handleUpperMessage(), setRadioCurrent(), PhyLayerUWBIR::setRadioCurrent(), setSwitchingCurrent(), and PhyLayerUWBIR::setSwitchingCurrent().
{
  if(radio->getCurrentState() == MiximRadio::RX) {
    if(amount != 0.0) {
      MiximBatteryAccess::drawCurrent(rxCurrent + amount, DECIDER_ACCT + activity);
    } else {
      MiximBatteryAccess::drawCurrent(rxCurrent, RX_ACCT);
    }
  } else {
    opp_warning("Decider wanted to change power consumption while radio not in state RX.");
  }
}
Decider * PhyLayerBattery::getDeciderFromName (const std::string & name, ParameterMap & params) [protected, virtual]
Creates and returns an instance of the decider with the specified name.
Is able to initialize directly the following decider:
Decider80211Battery
Decider80211MultiChannel
Reimplemented from PhyLayer.
Reimplemented in PhyLayerUWBIR.
{
    params["decodingCurrentDelta"] = cMsgPar("decodingCurrentDelta").setDoubleValue(decodingCurrentDelta);
  if(name == "Decider80211Battery") {
    return createDecider<Decider80211Battery>(params);
  }
  if(name == "Decider80211MultiChannel") {
    return createDecider<Decider80211MultiChannel>(params);
  }
  return PhyLayer::getDeciderFromName(name, params);
}
void PhyLayerBattery::handleAirFrame (airframe_ptr_t frame) [protected, virtual]
Checks if the the host state is on and prevents reception of AirFrames if not.
Calls the base classes overriden method for normal handling.
Reimplemented from BasePhyLayer.
References MiximBatteryAccess::battery, and BaseBattery::getState().
{
  if (battery && battery->getState() != HostState::ACTIVE) {
    coreEV<< "host has FAILED, dropping air frame msg " << frame->getName() << endl;
    delete frame;
    return;
  }
  PhyLayer::handleAirFrame(frame);
}
void PhyLayerBattery::handleHostState (const HostState & state) [protected, virtual]
Captures changes in host state.
Note: Does not yet cancel any ongoing transmissions if the state changes to off.
Reimplemented from BaseModule.
References HostState::get(), MiximRadio::getCurrentState(), BasePhyLayer::radio, setRadioState(), and MiximRadio::SLEEP.
{
  if (state.get() != HostState::ACTIVE && radio->getCurrentState() != MiximRadio::SLEEP) {
    coreEV<< "host is no longer in active state (maybe FAILED, SLEEP, OFF or BROKEN), force into sleep state!" << endl;
    setRadioState(MiximRadio::SLEEP);
    // it would be good to create a radioState OFF, as well
  }
}
void PhyLayerBattery::handleUpperMessage (cMessage * msg) [protected, virtual]
Checks the hosts state and draws txCurrent from battery.
Prevents sending of AirFrames if the hosts state is not on. Sets current power consumption for TX mode. Calls the base classes overriden method for normal handling.
Reimplemented from BasePhyLayer.
References MiximBatteryAccess::battery, calcTXCurrentForPacket(), drawCurrent(), and BaseBattery::getState().
{
  if (battery && battery->getState() != HostState::ACTIVE) {
    coreEV<< "host has FAILED, dropping msg " << msg->getName() << endl;
    delete msg;
    return;
  }
  macpkt_ptr_t pkt = static_cast<macpkt_ptr_t>(msg);
  MacToPhyControlInfo* cInfo = static_cast<MacToPhyControlInfo*>(pkt->getControlInfo());
  double current = calcTXCurrentForPacket(pkt, cInfo);
  if(current > 0) {
    MiximBatteryAccess::drawCurrent(current, TX_ACCT);
  }
  PhyLayer::handleUpperMessage(msg);
}
void PhyLayerBattery::initialize (int stage) [virtual]
OMNeT++ initialization function.
Read simple parameters. Read and parse xml file for decider and analogue models configuration.
Reimplemented from BasePhyLayer.
Reimplemented in PhyLayerUWBIR.
References MiximRadio::getCurrentState(), ConnectionManagerAccess::getNic(), numActivities, BasePhyLayer::radio, MiximBatteryAccess::registerWithBattery(), and setRadioCurrent().
{
  PhyLayer::initialize(stage);
  if (stage == 0) {
    cModule *const pNic = getNic();
    numActivities = hasPar("numActivities") ? par("numActivities").longValue() : 5;
    /* parameters belong to the NIC, not just phy layer
     *
     * if/when variable transmit power is supported, txCurrent
     * should be specified as an xml table of available transmit
     * power levels and corresponding txCurrent */
    sleepCurrent   = rxCurrent      = decodingCurrentDelta = txCurrent   = 0;
    setupRxCurrent = setupTxCurrent = rxTxCurrent          = txRxCurrent = 0;
    sleepCurrent         = pNic->par( "sleepCurrent" );
    rxCurrent            = pNic->par( "rxCurrent" );
    if (pNic->hasPar("decodingCurrentDelta"))
        decodingCurrentDelta = pNic->par( "decodingCurrentDelta" );
    txCurrent            = pNic->par( "txCurrent" );
    setupRxCurrent       = pNic->par( "setupRxCurrent" );
    setupTxCurrent       = pNic->par( "setupTxCurrent" );
    rxTxCurrent          = pNic->par( "rxTxCurrent" );
    txRxCurrent          = pNic->par( "txRxCurrent" );
  } else {
    registerWithBattery("physical layer", numActivities);
    setRadioCurrent(radio->getCurrentState());
  }
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/phy/PhyLayerBattery.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/phy/PhyLayerBattery.cc