MiXiM: MobilityBase Class Reference
MobilityBase Class Reference
mobility - modules handling the mobility of the hosts
Abstract base class for mobility modules.
#include <MobilityBase.h>
Public Types
enum BorderPolicy { REFLECT, WRAP, PLACERANDOMLY, RAISEERROR }
Protected Member Functions
virtual int numInitStages () const
Returns the required number of initialize stages.
virtual void initialize (int stage)
Initializes mobility model parameters in 4 stages.
virtual void initializePosition ()
Initializes the position from the display string or from module parameters.
virtual void handleMessage (cMessage *msg)
This modules should only receive self-messages.
virtual void handleSelfMessage (cMessage *msg)=0
Called upon arrival of a self messages, subclasses must override.
virtual void updateVisualRepresentation ()
Moves the visual representation module's icon to the new position on the screen.
virtual void emitMobilityStateChangedSignal ()
Emits a signal with the updated mobility state.
virtual Coord getRandomPosition ()
Returns a new random position satisfying the constraint area.
virtual cModule * findVisualRepresentation ()
Returns the module that represents the object moved by this mobility module.
virtual bool isOutside ()
Returns true if the mobility is outside of the constraint area.
virtual void reflectIfOutside (Coord &targetPosition, Coord &speed, double &angle)
Utility function to reflect the node if it goes outside the constraint area.
virtual void wrapIfOutside (Coord &targetPosition)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the constraint area.
virtual void placeRandomlyIfOutside (Coord &targetPosition)
Utility function to place the node randomly if it goes outside the constraint area.
virtual void raiseErrorIfOutside ()
Utility function to raise an error if the node gets outside the constraint area.
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &speed, double &angle)
Invokes one of reflectIfOutside(), wrapIfOutside() and placeRandomlyIfOutside(), depending on the given border policy.
Protected Attributes
cModule * visualRepresentation
Pointer to visual representation module, to speed up repeated access.
Coord constraintAreaMin
3 dimensional position and size of the constraint area (in meters).
Coord constraintAreaMax
Coord lastPosition
The last position that was reported.
Static Protected Attributes
static simsignal_t mobilityStateChangedSignal = SIMSIGNAL_NULL
A signal used to publish mobility state changes.
Detailed Description
Abstract base class for mobility modules.
Mobility modules inheriting from this base class may be stationary or may change their mobility state over simulation time. This base class only provides a few utility methods to handle some common tasks among mobility modules.
Subclasses must redefine handleSelfMessage() to update the mobility state and schedule the next update. Subclasses must also redefine initialize() to read their specific parameters and schedule the first update.
This base class also provides random initial placement as a default mechanism. After initialization the module updates the display and emits a signal to subscribers providing the mobility state. Receivers of this signal can query the mobility state through the IMobility interface.
Author:
Daniel Willkomm, Andras Varga
Member Enumeration Documentation
enum MobilityBase::BorderPolicy
Selects how a mobility module should behave if it reaches the edge of the constraint area.
See also:
handleIfOutside()
Enumerator:
REFLECT
reflect off the wall
WRAP
reappear at the opposite edge (torus)
PLACERANDOMLY
placed at a randomly chosen position within the constraint area
RAISEERROR
stop the simulation with error
                      {
        REFLECT,
        WRAP,
        PLACERANDOMLY,
        RAISEERROR
    };
Member Function Documentation
void MobilityBase::placeRandomlyIfOutside (Coord & targetPosition) [protected, virtual]
Utility function to place the node randomly if it goes outside the constraint area.
Decision is made on lastPosition, but targetPosition will also be updated. (Pass a dummy you don't have it).
References getRandomPosition(), isOutside(), and lastPosition.
Referenced by handleIfOutside().
{
    if (isOutside())
    {
        Coord newPosition = getRandomPosition();
        targetPosition += newPosition - lastPosition;
        lastPosition = newPosition;
    }
}
void MobilityBase::reflectIfOutside (Coord & targetPosition, Coord & speed, double & angle) [protected, virtual]
Utility function to reflect the node if it goes outside the constraint area.
Decision is made on pos, but the variables passed as args will also be updated. (Pass dummies you don't have some of them).
References constraintAreaMin, and lastPosition.
Referenced by handleIfOutside().
{
    int sign;
    double dummy;
    if (lastPosition.x < constraintAreaMin.x || constraintAreaMax.x < lastPosition.x) {
        sign = reflect(constraintAreaMin.x, constraintAreaMax.x, lastPosition.x, speed.x);
        reflect(constraintAreaMin.x, constraintAreaMax.x, targetPosition.x, dummy);
        angle = 90 + sign * (angle - 90);
    }
    if (lastPosition.y < constraintAreaMin.y || constraintAreaMax.y < lastPosition.y) {
        sign = reflect(constraintAreaMin.y, constraintAreaMax.y, lastPosition.y, speed.y);
        reflect(constraintAreaMin.y, constraintAreaMax.y, targetPosition.y, dummy);
        angle = sign * angle;
    }
    if (lastPosition.z < constraintAreaMin.z || constraintAreaMax.z < lastPosition.z) {
        sign = reflect(constraintAreaMin.z, constraintAreaMax.z, lastPosition.z, speed.z);
        reflect(constraintAreaMin.z, constraintAreaMax.z, targetPosition.z, dummy);
        // NOTE: angle is not affected
    }
}
void MobilityBase::wrapIfOutside (Coord & targetPosition) [protected, virtual]
Utility function to wrap the node to the opposite edge (torus) if it goes outside the constraint area.
Decision is made on pos, but targetPosition will also be updated. (Pass a dummy you don't have it).
References constraintAreaMin, and lastPosition.
Referenced by handleIfOutside().
{
    if (lastPosition.x < constraintAreaMin.x || constraintAreaMax.x < lastPosition.x) {
        wrap(constraintAreaMin.x, constraintAreaMax.x, lastPosition.x);
        wrap(constraintAreaMin.x, constraintAreaMax.x, targetPosition.x);
    }
    if (lastPosition.y < constraintAreaMin.y || constraintAreaMax.y < lastPosition.y) {
        wrap(constraintAreaMin.y, constraintAreaMax.y, lastPosition.y);
        wrap(constraintAreaMin.y, constraintAreaMax.y, targetPosition.y);
    }
    if (lastPosition.z < constraintAreaMin.z || constraintAreaMax.z < lastPosition.z) {
        wrap(constraintAreaMin.z, constraintAreaMax.z, lastPosition.z);
        wrap(constraintAreaMin.z, constraintAreaMax.z, targetPosition.z);
    }
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/mobility/models/MobilityBase.h
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/mobility/models/MobilityBase.cc