MiXiM: MiximRadio Class Reference
MiximRadio Class Reference
phyLayer - physical layer modules
The class that represents the Radio as a state machine.
#include <PhyUtils.h>
Public Types
enum RadioState {
RX = 0, TX, SLEEP, SWITCHING,
NUM_RADIO_STATES
}
The state of the radio of the nic.
Public Member Functions
virtual ~MiximRadio ()
Destructor for the Radio class.
virtual simtime_t switchTo (int newState, simtime_t_cref now)
A function called by the Physical Layer to start the switching process to a new RadioState.
virtual void setSwitchTime (int from, int to, simtime_t_cref time)
function called by PhyLayer in order to make an entry in the switch times matrix, i.e. set the time for switching from one state to another
virtual int getCurrentState () const
Returns the state the Radio is currently in.
virtual void endSwitch (simtime_t_cref now)
called by PhyLayer when duration-time for the current switching process is up
virtual RadioStateAnalogueModel * getAnalogueModel ()
Returns a pointer to the RadioStateAnalogueModel.
virtual void cleanAnalogueModelUntil (simtime_t_cref t)
discards information in the RadioStateAnalogueModel before given time-point
void setTrackingModeTo (bool b)
sets tracking mode
void setCurrentChannel (int newChannel)
Changes the current channel of the radio.
int getCurrentChannel () const
Returns the channel the radio is currently set to.
int getNbChannels () const
Returns the number of channels.
Static Public Member Functions
static MiximRadio * createNewRadio (bool recordStats=false, int initialState=RX, Argument::mapped_type_cref minAtt=Argument::MappedOne, Argument::mapped_type_cref maxAtt=Argument::MappedZero, int currentChannel=0, int nbChannels=1)
Creates a new instance of this class.
Protected Member Functions
MiximRadio (int numRadioStates, bool recordStats, int initialState=RX, Argument::mapped_type_cref minAtt=Argument::MappedOne, Argument::mapped_type_cref maxAtt=Argument::MappedZero, int currentChannel=0, int nbChannels=1)
Intern constructor to initialize the radio.
virtual void makeRSAMEntry (simtime_t_cref time, int state)
responsible for making entries to the RSAM
virtual Argument::mapped_type_cref mapStateToAtt (int state)
maps RadioState to attenuation, the Radios receiving characteristic
Protected Attributes
cOutVector radioStates
Output vector for radio states.
cOutVector radioChannels
Output vector for radio channels.
int state
The current state the radio is in.
int nextState
The state the radio is currently switching to.
const int numRadioStates
The number of radio states this Radio can be in.
simtime_t ** swTimes
Array for storing switch-times between states.
const Argument::mapped_type minAtt
Constant to store the minimum attenuation for a Radio instance.
const Argument::mapped_type maxAtt
Constant to store the maximum attenuation for a Radio instance.
RadioStateAnalogueModel rsam
The corresponding RadioStateAnalogueModel.
int currentChannel
Currently selected channel (varies between 0 and nbChannels-1).
int nbChannels
Number of available channels.
Private Member Functions
MiximRadio (const MiximRadio &)
Copy constructor is not allowed.
MiximRadio & operator= (const MiximRadio &)
Assignment operator is not allowed.
Detailed Description
The class that represents the Radio as a state machine.
The Radio creates and updates its corresponding RadioStateAnalogueModel, that is a filter representing the radios attenuation to a Signal depending on the RadioState over time.
For this basic version we assume a minimal attenuation when the Radio is in state RX, and a maximum attenuation otherwise.
A state-machine-diagram for Radio, RadioStateAnalogueModel and ChannelInfo showing how they work together under control of BasePhyLayer as well as some documentation on how RadioStateAnalogueModel works is available in phyLayer - physical layer modules.
Member Enumeration Documentation
enum MiximRadio::RadioState
The state of the radio of the nic.
Enumerator:
RX
receiving state
TX
transmitting state
SLEEP
sleeping
SWITCHING
switching between two states
NUM_RADIO_STATES
No real radio state just a counter constant for the amount of states.
Sub-classing Radios which want to add more states can add their own states in their own enum beginning at the value of NUM_RADIO_STATES. They should also remember to update the "numRadioStates" member accordingly.
See also:
RadioUWBIR for an example.
                  {
    RX = 0,
    TX,
    SLEEP,
    SWITCHING,
    NUM_RADIO_STATES
  };
Constructor & Destructor Documentation
MiximRadio::MiximRadio (int numRadioStates, bool recordStats, int initialState = RX, Argument::mapped_type_cref minAtt = Argument::MappedOne, Argument::mapped_type_cref maxAtt = Argument::MappedZero, int currentChannel = 0, int nbChannels = 1) [protected]
Intern constructor to initialize the radio.
By defining no default constructor we assure that sub classing radios have to explicitly call this constructor which assures they pass the correct number of radio states.
The protected constructor + factory method solution assures that while sub-classing Radios HAVE to explicitly pass their correct amount of radio states to this constructor, the user (creator) of the Radio doesn't has to pass it or even know about it (which wouldn't be possible with a public constructor). Therefore sub classing Radios which could be sub-classed further should also do it this way.
References numRadioStates, radioChannels, radioStates, and swTimes.
                                          :
  radioStates(), radioChannels(), state(initialState), nextState(initialState),
  numRadioStates(numRadioStates),
  swTimes(NULL),
  minAtt(minAtt), maxAtt(maxAtt),
  rsam(mapStateToAtt(initialState)),
  currentChannel(currentChannel), nbChannels(nbChannels)
{
  assert(nbChannels > 0);
  assert(currentChannel > -1);
  assert(currentChannel < nbChannels);
  radioStates.setName("RadioState");
  radioStates.setEnabled(recordStats);
  radioStates.record(initialState);
  radioChannels.setName("RadioChannel");
  radioChannels.setEnabled(recordStats);
  radioChannels.record(currentChannel);
  // allocate memory for one dimension
  swTimes = new simtime_t* [numRadioStates];
  // go through the first dimension and
  for (int i = 0; i < numRadioStates; i++)
  {
    // allocate memory for the second dimension
    swTimes[i] = new simtime_t[numRadioStates];
  }
  // initialize all matrix entries to 0.0
  for (int i = 0; i < numRadioStates; i++)
  {
    for (int j = 0; j < numRadioStates; j++)
    {
      swTimes[i][j] = 0;
    }
  }
}
Member Function Documentation
static MiximRadio* MiximRadio::createNewRadio (bool recordStats = false, int initialState = RX, Argument::mapped_type_cref minAtt = Argument::MappedOne, Argument::mapped_type_cref maxAtt = Argument::MappedZero, int currentChannel = 0, int nbChannels = 1) [inline, static]
Creates a new instance of this class.
Since Radio hasn't a public constructor this is the only way to create an instance of this class.
This method assures that the radio is initialized with the correct number of radio states. Sub classing Radios should also define a factory method like this instead of an public constructor.
Referenced by BasePhyLayer::initializeRadio().
  {
    return new MiximRadio(NUM_RADIO_STATES,
                                 recordStats,
                                 initialState,
                                 minAtt, maxAtt,
                                 currentChannel, nbChannels);
  }
void MiximRadio::endSwitch (simtime_t_cref now) [virtual]
called by PhyLayer when duration-time for the current switching process is up
Radio checks whether it is in switching state (pre-condition) and switches to the target state
The actual simtime must be passed, to create properly RSAMEntry
References makeRSAMEntry(), nextState, radioStates, state, and SWITCHING.
Referenced by BasePhyLayer::finishRadioSwitching(), RadioUWBIR::finishReceivingFrame(), and RadioUWBIR::startReceivingFrame().
{
  // make sure we are currently switching
  assert(state == SWITCHING);
  // set the current state finally to the next state
  state = nextState;
  radioStates.record(state);
  // make entry to RSAM
  makeRSAMEntry(now, state);
  return;
}
virtual RadioStateAnalogueModel* MiximRadio::getAnalogueModel () [inline, virtual]
Returns a pointer to the RadioStateAnalogueModel.
This method is intended to be used by the PhyLayer to obtain a pointer to the corresponding RSAM to this Radio
Referenced by BasePhyLayer::getAnalogueModelFromName(), and BasePhyLayer::~BasePhyLayer().
{
    return (&rsam);
  }
int MiximRadio::getCurrentChannel () const [inline]
Returns the channel the radio is currently set to.
Returns:
The current channel of the radio, between 0 and nbChannels-1.
Referenced by PhyLayerUWBIR::encapsMsg(), BasePhyLayer::encapsMsg(), and BasePhyLayer::getCurrentRadioChannel().
{
    return currentChannel;
  }
int MiximRadio::getNbChannels () const [inline]
Returns the number of channels.
Returns:
The number of channels.
Referenced by BasePhyLayer::getNbRadioChannels().
{
    return nbChannels;
  }
void MiximRadio::setCurrentChannel (int newChannel) [inline]
Changes the current channel of the radio.
Parameters:
newChannel The new channel to switch to, between 0 and nbChannels-1
Referenced by BasePhyLayer::setCurrentRadioChannel().
{
    assert(newChannel > -1);
    assert(newChannel < nbChannels);
    currentChannel = newChannel;
    radioChannels.record(currentChannel);
  }
simtime_t MiximRadio::switchTo (int newState, simtime_t_cref now) [virtual]
A function called by the Physical Layer to start the switching process to a new RadioState.
Returns:
-1: Error code if the Radio is currently switching else: switching time from the current RadioState to the new RadioState
The actual simtime must be passed, to create properly RSAMEntry
Reimplemented in RadioUWBIR.
References makeRSAMEntry(), nextState, numRadioStates, radioStates, state, SWITCHING, and swTimes.
Referenced by BasePhyLayer::setRadioState().
{
  // state to switch to must be in a valid range, i.e. 0 <= newState < numRadioStates
  assert(0 <= newState && newState < numRadioStates);
  // state to switch to must not be SWITCHING
  assert(newState != SWITCHING);
  // return error value if newState is the same as the current state
  // if (newState == state) return -1;
  // return error value if MiximRadio is currently switching
  if (state == SWITCHING) return -1;
  /* REGULAR CASE */
  // set the nextState to the newState and the current state to SWITCHING
  nextState = newState;
  int lastState = state;
  state = SWITCHING;
  radioStates.record(state);
  // make entry to RSAM
  makeRSAMEntry(now, state);
  // return matching entry from the switch times matrix
  return swTimes[lastState][nextState];
}
Member Data Documentation
RadioStateAnalogueModel MiximRadio::rsam [protected]
The corresponding RadioStateAnalogueModel.
Depends on the characteristics of the radio
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/PhyUtils.h
D:/Projects/MiXiM/extsrc/mixim/src/base/phyLayer/PhyUtils.cc