MiXiM: IntensityModel Class Reference
IntensityModel Class Reference
analogueModels - AnalogueModel implementations
TODO: Short description for this AnalogueModel.
#include <IntensityModel.h>
Public Member Functions
void filterSignal (airframe_ptr_t frame, const Coord &sendersPos, const Coord &receiverPos)
Has to be overriden by every implementation.
Detailed Description
TODO: Short description for this AnalogueModel.
Member Function Documentation
void IntensityModel::filterSignal (airframe_ptr_t frame, const Coord & sendersPos, const Coord & receiverPos) [inline, virtual]
Has to be overriden by every implementation.
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Parameters:
frame The incomming frame.
sendersPos The position of the frame sender.
receiverPos The position of frame receiver.
Implements AnalogueModel.
References Signal::addAttenuation(), Coord::distance(), Signal::getReceptionStart(), and TimeMapping< Interpolator >::setValue().
{
            Signal& s = frame->getSignal();
            TimeMapping<Linear>* attMapping = new TimeMapping<Linear>();
            // Determine distance between sender and receiver
            assert(s.getReceptionStart() == simTime());
            double distance = sendersPos.distance(receiverPos);
            Argument arg;
            attMapping->setValue(arg, 4 * M_PI * pow(distance, 2));
            s.addAttenuation(attMapping);
        }
The documentation for this class was generated from the following file:
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/IntensityModel.h