MiXiM: UWBIRStochasticPathlossModel Class Reference
UWBIRStochasticPathlossModel Class Reference
IEEE 802.15.4A - Classes that implement the IEEE 802.15.4A UWB PHY. | analogueModels - AnalogueModel implementations
This AnalogueModel models implements the Ghassmezadeh stochastic UWB channel models.
#include <UWBIRStochasticPathlossModel.h>
Public Member Functions
virtual bool initFromMap (const ParameterMap &)
Initialize the analog model from XML map data.
void filterSignal (airframe_ptr_t, const Coord &, const Coord &)
Has to be overriden by every implementation.
Public Attributes
double PL0
double mu_gamma
double sigma_gamma
double mu_sigma
double sigma_sigma
double gamma
double S
double sigma
double n1
double n2
double n3
bool isEnabled
bool shadowing
cOutVector distances
cOutVector srcPosX
cOutVector srcPosY
cOutVector dstPosX
cOutVector dstPosY
int myIndex
std::string myName
Static Public Attributes
static const double Gtx = 1
static const double Grx = 1
static const double ntx = 1
static const double nrx = 1
static const double fc = 4492.8
static const double d0 = 1
static double n1_limit = 1.25
static double n2_limit = 2
static const double s_mu = 1.6
static const double s_sigma = 0.5
static const double kappa = 1
Protected Member Functions
double getGhassemzadehPathloss (double distance) const
double getFDPathloss (double freq, double distance) const
Static Protected Member Functions
static double getNarrowBandFreeSpacePathloss (double fc, double distance)
static double simtruncnormal (double mean, double stddev, double a, int rng)
Protected Attributes
double pathloss_exponent
double fading
Dimension frequency
cOutVector pathlosses
Detailed Description
This AnalogueModel models implements the Ghassmezadeh stochastic UWB channel models.
Citation of the following publication is appreciated if you use the MiXiM UWB PHY model for a publication of your own. J. Rousselot, J.-D. Decotignie, An ultra-wideband impulse radio PHY layer model for network simulation. SIMULATION January 2011 vol. 87 no. 1-2 82-112.
For more information, see also:
[1] J. Rousselot, J.-D. Decotignie, An ultra-wideband impulse radio PHY layer model for network simulation. SIMULATION January 2011 vol. 87 no. 1-2 82-112. http://dx.doi.org/10.1177/0037549710377767 [2] J. Rousselot, Ultra Low Power Communication Protocols for UWB Impulse Radio Wireless Sensor Networks. EPFL Thesis 4720, 2010. http://infoscience.epfl.ch/record/147987 [3] A High-Precision Ultra Wideband Impulse Radio Physical Layer Model for Network Simulation, Jérôme Rousselot, Jean-Dominique Decotignie, Second International Omnet++ Workshop,Simu'TOOLS, Rome, 6 Mar 09. http://portal.acm.org/citation.cfm?id=1537714
Member Function Documentation
void UWBIRStochasticPathlossModel::filterSignal (airframe_ptr_t frame, const Coord & sendersPos, const Coord & receiverPos) [virtual]
Has to be overriden by every implementation.
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Parameters:
frame The incomming frame.
sendersPos The position of the frame sender.
receiverPos The position of frame receiver.
Implements AnalogueModel.
References Signal::addAttenuation(), Coord::distance(), and TimeMapping< Interpolator >::setValue().
{
  if (isEnabled) {
    Signal& signal = frame->getSignal();
    // Initialize objects and variables
    TimeMapping<Linear>* attMapping = new TimeMapping<Linear> ();
    Argument arg;
    // Generate channel.
    // assume channel coherence during whole frame
    n1 = simtruncnormal(0, 1, n1_limit, 1);
    n2 = simtruncnormal(0, 1, n2_limit, 2);
    n3 = simtruncnormal(0, 1, n2_limit, 3);
    gamma = mu_gamma + n1 * sigma_gamma;
    sigma = mu_sigma + n3 * sigma_sigma;
    S = n2 * sigma;
    // Determine distance between sender and receiver
    double distance    = receiverPos.distance(sendersPos);
    /*
     srcPosX.record(senderPos.x);
     srcPosY.record(senderPos.y);
     dstPosX.record(receiverPos.x);
     dstPosY.record(receiverPos.y);
    */
     distances.record(distance);
    // Compute pathloss
    double attenuation = getGhassemzadehPathloss(distance);
    pathlosses.record(attenuation);
    //attenuation = attenuation / (4*PI*pow(distance, gamma));
    // Store scalar mapping
    attMapping->setValue(arg, attenuation);
    signal.addAttenuation(attMapping);
  }
}
bool UWBIRStochasticPathlossModel::initFromMap (const ParameterMap & params) [virtual]
Initialize the analog model from XML map data.
This method should be defined for generic analog model initialization.
Parameters:
params The parameter map which was filled by XML reader.
Returns:
true if the initialization was successfully.
Reimplemented from AnalogueModel.
{
    ParameterMap::const_iterator it;
    bool                         bInitSuccess = true;
    if ((it = params.find("seed")) != params.end()) {
        srand( ParameterMap::mapped_type(it->second).longValue() );
    }
    if ((it = params.find("PL0")) != params.end()) {
        PL0 = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No PL0 defined in config.xml for UWBIRStochasticPathlossModel!");
    }
    if ((it = params.find("mu_gamma")) != params.end()) {
        mu_gamma = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No mu_gamma defined in config.xml for UWBIRStochasticPathlossModel!");
    }
    if ((it = params.find("sigma_gamma")) != params.end()) {
        sigma_gamma = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No sigma_gamma defined in config.xml for UWBIRStochasticPathlossModel!");
    }
    if ((it = params.find("mu_sigma")) != params.end()) {
        mu_sigma = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No mu_sigma defined in config.xml for UWBIRStochasticPathlossModel!");
    }
    if ((it = params.find("sigma_sigma")) != params.end()) {
        sigma_sigma = ParameterMap::mapped_type(it->second).doubleValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No sigma_sigma defined in config.xml for UWBIRStochasticPathlossModel!");
    }
    if ((it = params.find("isEnabled")) != params.end()) {
        isEnabled = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        bInitSuccess = false;
        opp_warning("No isEnabled defined in config.xml for UWBIRStochasticPathlossModel!");
    }
    if ((it = params.find("shadowing")) != params.end()) {
        shadowing = ParameterMap::mapped_type(it->second).boolValue();
    }
    else {
        shadowing = false;
    }
    return AnalogueModel::initFromMap(params) && bInitSuccess;
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/UWBIRStochasticPathlossModel.h
D:/Projects/MiXiM/extsrc/mixim/src/modules/analogueModel/UWBIRStochasticPathlossModel.cc