MiXiM: TurtleMobility Class Reference
TurtleMobility Class Reference
mobility - modules handling the mobility of the hosts
LOGO-style movement model, with the script coming from XML. See NED file for more info.
#include <TurtleMobility.h>
Protected Member Functions
virtual void initialize (int stage)
Initializes mobility model parameters.
virtual void initializePosition ()
Initializes the position according to the mobility model.
virtual void setTargetPosition ()
Overridden from LineSegmentsMobilityBase. Invokes resumeScript().
virtual void move ()
Overridden from LineSegmentsMobilityBase.
virtual void resumeScript ()
Process next statements from script.
virtual void executeStatement (cXMLElement *nextStatement)
Execute the given statement.
virtual double getValue (const char *s)
Parse attrs in the script -- accepts things like "uniform(10,50) as well.
virtual void gotoNextStatement ()
Advance nextStatement pointer.
Protected Attributes
cXMLElement * turtleScript
cXMLElement * nextStatement
double speed
double angle
BorderPolicy borderPolicy
std::stack< long > loopVars
Detailed Description
LOGO-style movement model, with the script coming from XML. See NED file for more info.
Author:
Andras Varga
Member Function Documentation
void TurtleMobility::resumeScript () [protected, virtual]
Process next statements from script.
Will set a new nextChange and targetPosition.
References executeStatement(), gotoNextStatement(), MobilityBase::lastPosition, MovingMobilityBase::nextChange, MovingMobilityBase::stationary, and LineSegmentsMobilityBase::targetPosition.
Referenced by initializePosition(), and setTargetPosition().
{
    simtime_t now = simTime();
    do {
        if (nextStatement != NULL)
        {
            executeStatement(nextStatement);
            gotoNextStatement();
        }
        else
        {
            nextChange = -1;
            stationary = true;
            targetPosition = lastPosition;
        }
    } while (nextChange == now);
}
The documentation for this class was generated from the following files:
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/mobility/models/TurtleMobility.h
D:/Projects/MiXiM/extsrc/mixim/src/inet_stub/mobility/models/TurtleMobility.cc