MiXiM: simsignalwrap_t Class Reference
simsignalwrap_t Class Reference
Helper function to initialize signal change identifier on use and not on initializing static sections.
#include <MiXiMDefs.h>
Public Member Functions
simsignalwrap_t (const char *const pSignalName)
simsignalwrap_t (const simsignalwrap_t &pCpy)
simsignal_t initialize () const
operator simsignal_t () const
Private Attributes
volatile simsignal_t ssChangeSignal
const char *const sSignalName
Detailed Description
Helper function to initialize signal change identifier on use and not on initializing static sections.
Member Function Documentation
simsignal_t simsignalwrap_t::initialize () const [inline]
This function works like the cast operator but does a little bit more checks if we access the variable after a network rebuild!
This function should be used in the initialize methods of all modules where the signal will be used (emit, subscribe).
Referenced by DeciderUWBIRED::initFromMap(), SimpleBattery::initialize(), SensorApplLayer::initialize(), BatteryStats::initialize(), UWBIRMac::initialize(), NetworkStackTrafficGen::initialize(), TrafficGen::initialize(), BaseLayer::initialize(), LMacLayer::initialize(), csma::initialize(), BaseModule::initialize(), and ConnectionManagerAccess::initialize().
{
    if (sSignalName != NULL && (ssChangeSignal != SIMSIGNAL_NULL)) {
      const char *const sRegSigName = cComponent::getSignalName(ssChangeSignal);
      if (sRegSigName == NULL || strcmp(sSignalName, sRegSigName) != 0) {
        ssChangeSignal = SIMSIGNAL_NULL;
      }
    }
    return (*this);
  }
simsignalwrap_t::operator simsignal_t () const [inline]
Cast operator to simsignal_t, we initialize the signal here if it is empty ;).
{
    if (sSignalName != NULL && ssChangeSignal == SIMSIGNAL_NULL) {
      ssChangeSignal = cComponent::registerSignal(sSignalName);
    }
    return ssChangeSignal;
  }
The documentation for this class was generated from the following file:
D:/Projects/MiXiM/extsrc/mixim/src/base/utils/MiXiMDefs.h